#!/usr/bin/env tsx
/**
 * devloop pre-squash <branch>
 *
 * Generates a structured commit message for a squash merge that preserves
 * the workflow audit trail in the message body. Output goes to stdout
 * for piping or copying into the GitHub squash UI.
 */

import { EventLog } from "../lib/event-log.js";
import { reduce } from "../lib/reducer.js";
import { buildPrSummary } from "../lib/pr-summary.js";

function main(): void {
  const branch = process.argv[2];
  if (!branch || branch.startsWith("--")) {
    console.error("usage: devloop pre-squash <branch>");
    process.exit(1);
  }

  const log = EventLog.fromCwd(process.cwd());
  const wId = log.getActiveWorkflowId();
  if (!wId) {
    console.error("error: no active workflow in current directory");
    process.exit(1);
  }

  const events = log.loadArchivedEvents(wId);
  if (events.length === 0) {
    console.error(`error: no archived events for ${wId}`);
    process.exit(1);
  }

  const state = reduce(events);
  const summary = buildPrSummary(events);

  const phaseTotalsMs = state.phase_history
    .map((p) => `${p.phase} (${p.duration_ms ?? 0}ms)`)
    .join(" → ");
  const taskShort = state.task.length > 60 ? state.task.slice(0, 57) + "..." : state.task;

  const subject = `feat(${state.workflow_type}): ${taskShort}`;
  const body = [
    "",
    `[devloop workflow: ${wId}]`,
    `[archive: .workflow/archives/${wId}/]`,
    "",
    `Workflow type: ${state.workflow_type}`,
    `Phases: ${phaseTotalsMs}`,
    `Decisions: ${state.knowledge.adrs_approved.length} ADR(s)`,
    `Scope expansions: ${state.scope.scope_expansions_approved} approved`,
    "",
    "<dev-written description>",
    "",
    `[Generated by devloop. Audit at .workflow/archives/${wId}/]`,
    "",
    summary.block,
  ];

  console.log(subject);
  console.log(body.join("\n"));
}

main();
void undefined;
