import { discoverArtifacts } from './src/cli/contribute.js';
import { Logger } from './src/core/output/logger.js';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync = promisify(execFile);

Logger.init({ level: 'info', mode: 'human', noColor: true });

const PROJECT_DIR = process.cwd();
const CODI_REPO = 'lehidalgo/codi';
const TARGET_BRANCH = 'develop';
const SKILL_OUTPUT_FILENAME = 'SKILL.md';

console.log('\n=== Step 1: Discover artifacts ===');
const artifacts = await discoverArtifacts(path.join(PROJECT_DIR, '.codi'));
console.log(`Found ${artifacts.length} artifacts:`);
for (const a of artifacts) console.log(`  [${a.type}] ${a.name} (${a.managedBy})`);

// Select just 2 for the test PR
const selected = artifacts.slice(0, 2);
console.log(`\nSelected ${selected.length} for contribution:`);
for (const a of selected) console.log(`  [${a.type}] ${a.name}`);

console.log('\n=== Step 2: Fork, branch, convert to templates, push, PR ===');
const cloneDir = path.join(os.tmpdir(), `codi-contribute-${Date.now()}`);

try {
  console.log('Forking and cloning codi repository...');
  await execFileAsync('gh', [
    'repo', 'fork', CODI_REPO,
    '--clone', '--remote', '--default-branch-only'
  ], { cwd: os.tmpdir() });

  const { stdout: forkName } = await execFileAsync('gh', [
    'repo', 'view', '--json', 'name', '-q', '.name'
  ]);
  const forkCloneDir = path.join(os.tmpdir(), forkName.trim());
  console.log(`Fork cloned to: ${forkCloneDir}`);

  const branchName = `contrib/e2e-test-${Date.now()}`;
  await execFileAsync('git', ['checkout', '-b', branchName], { cwd: forkCloneDir });
  console.log(`Branch: ${branchName}`);

  // Convert each artifact to TypeScript template
  for (const artifact of selected) {
    const typeDir = (() => {
      switch (artifact.type) {
        case 'rule': return 'src/templates/rules';
        case 'skill': return 'src/templates/skills';
        case 'agent': return 'src/templates/agents';
        case 'command': return 'src/templates/commands';
      }
    })();

    const mdPath = artifact.type === 'skill'
      ? path.join(artifact.path, SKILL_OUTPUT_FILENAME)
      : artifact.path;
    const raw = await fs.readFile(mdPath, 'utf8');
    const escaped = raw.replace(/`/g, '\\`').replace(/\$/g, '\\$');
    const templateContent = `export const template = \`${escaped}\`;\n`;

    const destDir = path.join(forkCloneDir, typeDir);
    const destFile = path.join(destDir, `${artifact.name}.ts`);
    await fs.mkdir(destDir, { recursive: true });
    await fs.writeFile(destFile, templateContent, 'utf8');
    console.log(`  Wrote: ${typeDir}/${artifact.name}.ts (${templateContent.length} bytes)`);
  }

  // Commit + push
  await execFileAsync('git', ['add', '.'], { cwd: forkCloneDir });
  const names = selected.map(a => `${a.type}:${a.name}`).join(', ');
  await execFileAsync('git', [
    'commit', '-m', `feat: contribute ${names}`
  ], { cwd: forkCloneDir });
  console.log('\nCommitted.');

  await execFileAsync('git', ['push', 'origin', branchName], { cwd: forkCloneDir });
  console.log('Pushed.');

  // Create PR against develop branch
  const { stdout: prUrl } = await execFileAsync('gh', [
    'pr', 'create',
    '--repo', CODI_REPO,
    '--base', TARGET_BRANCH,
    '--title', `feat: contribute ${names}`,
    '--body', `## Contributed Artifacts\n\n${selected.map(a => `- **${a.type}**: ${a.name}`).join('\n')}\n\nGenerated by \`codi contribute\` E2E test.\n\n> This is a test PR — please close without merging.`,
  ], { cwd: forkCloneDir });

  console.log(`\n✅ PR created: ${prUrl.trim()}`);
  console.log(`   Target: ${CODI_REPO} -> ${TARGET_BRANCH}`);

  // Clean up fork clone
  await fs.rm(forkCloneDir, { recursive: true, force: true }).catch(() => {});
} catch (error) {
  console.error('Failed:', error instanceof Error ? error.message : String(error));
  process.exit(1);
} finally {
  await fs.rm(cloneDir, { recursive: true, force: true }).catch(() => {});
}
