import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import path from "node:path";
import { PROJECT_DIR, MANIFEST_FILENAME, PROJECT_NAME_DISPLAY } from "#src/constants.js";
import { runCli, createTempProject, fileExists, readFile } from "./helpers/cli-harness.js";

// E2E tests spawn real subprocesses; each runCli call builds the template hash registry
// from scratch. Under parallel test load (150 workers), disk I/O contention can push
// multi-step tests past 30 s. 60 s gives enough headroom without masking true hangs.
vi.setConfig({ testTimeout: 60_000 });

let projectDir: string;
let cleanup: () => Promise<void>;

beforeEach(async () => {
  const project = await createTempProject();
  projectDir = project.projectDir;
  cleanup = project.cleanup;
});

afterEach(async () => {
  await cleanup();
});

describe("E2E: init → generate → verify lifecycle", () => {
  it(`init creates ${PROJECT_DIR}/ directory structure`, async () => {
    const result = await runCli(projectDir, ["init"]);

    expect(result.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, PROJECT_DIR))).toBe(true);
    expect(await fileExists(path.join(projectDir, PROJECT_DIR, MANIFEST_FILENAME))).toBe(true);
    expect(await fileExists(path.join(projectDir, PROJECT_DIR, "flags.yaml"))).toBe(true);
    expect(await fileExists(path.join(projectDir, PROJECT_DIR, "rules"))).toBe(true);
  });

  it("generate produces adapter files after init with --agents", async () => {
    await runCli(projectDir, ["init", "--agents", "claude-code"]);
    const result = await runCli(projectDir, ["generate", "--force"]);

    expect(result.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, "CLAUDE.md"))).toBe(true);
  });

  it("validate passes after init", async () => {
    await runCli(projectDir, ["init"]);
    const result = await runCli(projectDir, ["validate"]);

    expect(result.exitCode).toBe(0);
  });

  it("validate fails without init", async () => {
    const result = await runCli(projectDir, ["validate"]);

    expect(result.exitCode).not.toBe(0);
  });

  it("status reports no drift after init", async () => {
    await runCli(projectDir, ["init"]);
    const result = await runCli(projectDir, ["status"]);

    expect(result.exitCode).toBe(0);
  });

  it("init with --force reinitializes existing project", async () => {
    await runCli(projectDir, ["init"]);

    const updateResult = await runCli(projectDir, ["init"]);
    expect(updateResult.exitCode).toBe(0);

    const forceResult = await runCli(projectDir, ["init", "--force"]);
    expect(forceResult.exitCode).toBe(0);
  });

  it("generated CLAUDE.md contains verification token", async () => {
    await runCli(projectDir, ["init", "--agents", "claude-code"]);
    await runCli(projectDir, ["generate"]);

    const content = await readFile(path.join(projectDir, "CLAUDE.md"));
    expect(content).toContain(`Generated by ${PROJECT_NAME_DISPLAY}`);
    expect(content).toContain(`${PROJECT_NAME_DISPLAY}`);
  });

  it("clean removes generated files", async () => {
    await runCli(projectDir, ["init", "--agents", "claude-code"]);
    await runCli(projectDir, ["generate"]);

    expect(await fileExists(path.join(projectDir, "CLAUDE.md"))).toBe(true);

    const cleanResult = await runCli(projectDir, ["clean"]);
    expect(cleanResult.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, "CLAUDE.md"))).toBe(false);
    expect(await fileExists(path.join(projectDir, PROJECT_DIR))).toBe(true);
  });

  it(`clean --all removes everything including ${PROJECT_DIR}/`, async () => {
    await runCli(projectDir, ["init", "--agents", "claude-code"]);
    await runCli(projectDir, ["generate"]);

    const cleanResult = await runCli(projectDir, ["clean", "--all"]);
    expect(cleanResult.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, PROJECT_DIR))).toBe(false);
  });
});
