import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import path from "node:path";
import {
  runCodi,
  createTempProject,
  fileExists,
  readFile,
} from "./helpers/cli-harness.js";

// E2E tests are slower — extend timeout
vi.setConfig({ testTimeout: 30_000 });

let projectDir: string;
let cleanup: () => Promise<void>;

beforeEach(async () => {
  const project = await createTempProject();
  projectDir = project.projectDir;
  cleanup = project.cleanup;
});

afterEach(async () => {
  await cleanup();
});

describe("E2E: init → generate → verify lifecycle", () => {
  it("init creates .codi/ directory structure", async () => {
    const result = await runCodi(projectDir, ["init"]);

    expect(result.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, ".codi"))).toBe(true);
    expect(await fileExists(path.join(projectDir, ".codi", "codi.yaml"))).toBe(
      true,
    );
    expect(await fileExists(path.join(projectDir, ".codi", "flags.yaml"))).toBe(
      true,
    );
    expect(await fileExists(path.join(projectDir, ".codi", "rules"))).toBe(
      true,
    );
  });

  it("generate produces adapter files after init with --agents", async () => {
    await runCodi(projectDir, ["init", "--agents", "claude-code"]);
    const result = await runCodi(projectDir, ["generate"]);

    expect(result.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, "CLAUDE.md"))).toBe(true);
  });

  it("validate passes after init", async () => {
    await runCodi(projectDir, ["init"]);
    const result = await runCodi(projectDir, ["validate"]);

    expect(result.exitCode).toBe(0);
  });

  it("validate fails without init", async () => {
    const result = await runCodi(projectDir, ["validate"]);

    expect(result.exitCode).not.toBe(0);
  });

  it("status reports no drift after init", async () => {
    await runCodi(projectDir, ["init"]);
    const result = await runCodi(projectDir, ["status"]);

    expect(result.exitCode).toBe(0);
  });

  it("init with --force reinitializes existing project", async () => {
    await runCodi(projectDir, ["init"]);

    const failResult = await runCodi(projectDir, ["init"]);
    expect(failResult.exitCode).not.toBe(0);

    const forceResult = await runCodi(projectDir, ["init", "--force"]);
    expect(forceResult.exitCode).toBe(0);
  });

  it("generated CLAUDE.md contains verification token", async () => {
    await runCodi(projectDir, ["init", "--agents", "claude-code"]);
    await runCodi(projectDir, ["generate"]);

    const content = await readFile(path.join(projectDir, "CLAUDE.md"));
    expect(content).toContain("Generated by Codi");
    expect(content).toContain("codi-");
  });

  it("clean removes generated files", async () => {
    await runCodi(projectDir, ["init", "--agents", "claude-code"]);
    await runCodi(projectDir, ["generate"]);

    expect(await fileExists(path.join(projectDir, "CLAUDE.md"))).toBe(true);

    const cleanResult = await runCodi(projectDir, ["clean"]);
    expect(cleanResult.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, "CLAUDE.md"))).toBe(false);
    expect(await fileExists(path.join(projectDir, ".codi"))).toBe(true);
  });

  it("clean --all removes everything including .codi/", async () => {
    await runCodi(projectDir, ["init", "--agents", "claude-code"]);
    await runCodi(projectDir, ["generate"]);

    const cleanResult = await runCodi(projectDir, ["clean", "--all"]);
    expect(cleanResult.exitCode).toBe(0);
    expect(await fileExists(path.join(projectDir, ".codi"))).toBe(false);
  });
});
