import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { stringify as stringifyYaml } from "yaml";
import { resolveConfig } from "#src/core/config/resolver.js";
import { generate } from "#src/core/generator/generator.js";
import { registerAllAdapters } from "#src/adapters/index.js";
import { clearAdapters } from "#src/core/generator/adapter-registry.js";
import { Logger } from "#src/core/output/logger.js";
import {
  PROJECT_NAME,
  PROJECT_NAME_DISPLAY,
  PROJECT_DIR,
  MANIFEST_FILENAME,
} from "#src/constants.js";

let tmpDir: string;

async function fileExists(p: string): Promise<boolean> {
  return fs
    .access(p)
    .then(() => true)
    .catch(() => false);
}

beforeEach(async () => {
  const base = await fs.mkdtemp(
    path.join(os.tmpdir(), `${PROJECT_NAME}-adapter-gen-`),
  );
  tmpDir = path.join(base, "test-project");
  await fs.mkdir(tmpDir, { recursive: true });
  clearAdapters();
  registerAllAdapters();
  Logger.init({ level: "error", mode: "human", noColor: true });
});

afterEach(async () => {
  await fs.rm(path.dirname(tmpDir), { recursive: true, force: true });
  clearAdapters();
});

async function createProjectWithAgents(agents: string[]): Promise<void> {
  const configDir = path.join(tmpDir, PROJECT_DIR);
  await fs.mkdir(configDir, { recursive: true });
  await fs.writeFile(
    path.join(configDir, MANIFEST_FILENAME),
    stringifyYaml({ name: "gen-test", version: "1", agents }),
    "utf-8",
  );

  // Add a rule so there's content to generate
  const rulesDir = path.join(configDir, "rules");
  await fs.mkdir(rulesDir, { recursive: true });
  await fs.writeFile(
    path.join(rulesDir, "security.md"),
    `---\nname: security\ndescription: Security rules\npriority: high\nmanaged_by: ${PROJECT_NAME}\n---\n\nFollow security best practices.`,
    "utf-8",
  );

  // Add a skill
  const skillDir = path.join(configDir, "skills", "commit");
  await fs.mkdir(skillDir, { recursive: true });
  await fs.writeFile(
    path.join(skillDir, "SKILL.md"),
    "---\nname: commit\ndescription: Commit workflow\n---\n\nCommit steps here.",
    "utf-8",
  );
}

describe("Adapter Generation: single agent", () => {
  it("generates Claude Code output (CLAUDE.md + rules dir)", async () => {
    await createProjectWithAgents(["claude-code"]);
    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.data.agents).toContain("claude-code");
    expect(await fileExists(path.join(tmpDir, "CLAUDE.md"))).toBe(true);

    const claudeMd = await fs.readFile(path.join(tmpDir, "CLAUDE.md"), "utf-8");
    expect(claudeMd).toContain(`Generated by ${PROJECT_NAME_DISPLAY}`);
    expect(claudeMd).toContain(`${PROJECT_NAME}-`);
  });

  it("generates Cursor output (.cursorrules)", async () => {
    await createProjectWithAgents(["cursor"]);
    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.data.agents).toContain("cursor");
    expect(await fileExists(path.join(tmpDir, ".cursorrules"))).toBe(true);

    const cursorRules = await fs.readFile(
      path.join(tmpDir, ".cursorrules"),
      "utf-8",
    );
    expect(cursorRules).toContain(`Generated by ${PROJECT_NAME_DISPLAY}`);
  });

  it("generates Codex output (.codex/ directory)", async () => {
    await createProjectWithAgents(["codex"]);
    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.data.agents).toContain("codex");
    expect(await fileExists(path.join(tmpDir, "AGENTS.md"))).toBe(true);
  });

  it("generates Cline output (.clinerules)", async () => {
    await createProjectWithAgents(["cline"]);
    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.data.agents).toContain("cline");
    expect(await fileExists(path.join(tmpDir, ".clinerules"))).toBe(true);
  });

  it("generates Windsurf output (.windsurfrules)", async () => {
    await createProjectWithAgents(["windsurf"]);
    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.data.agents).toContain("windsurf");
    expect(await fileExists(path.join(tmpDir, ".windsurfrules"))).toBe(true);
  });
});

describe("Adapter Generation: multi-agent", () => {
  it("generates output for all 5 adapters simultaneously", async () => {
    const allAgents = ["claude-code", "cursor", "codex", "cline", "windsurf"];
    await createProjectWithAgents(allAgents);

    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.data.agents.sort()).toEqual(allAgents.sort());
    expect(result.data.files.length).toBeGreaterThan(5);

    // Verify each adapter's primary file
    expect(await fileExists(path.join(tmpDir, "CLAUDE.md"))).toBe(true);
    expect(await fileExists(path.join(tmpDir, ".cursorrules"))).toBe(true);
    expect(await fileExists(path.join(tmpDir, "AGENTS.md"))).toBe(true);
    expect(await fileExists(path.join(tmpDir, ".clinerules"))).toBe(true);
    expect(await fileExists(path.join(tmpDir, ".windsurfrules"))).toBe(true);
  });

  it("all adapters include the security rule content", async () => {
    const allAgents = ["claude-code", "cursor", "cline", "windsurf"];
    await createProjectWithAgents(allAgents);

    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    // Each agent should have the security rule in its output
    for (const agentId of allAgents) {
      const agentFiles = result.data.filesByAgent[agentId];
      expect(agentFiles).toBeDefined();
      expect(agentFiles!.length).toBeGreaterThan(0);

      // At least one file should reference security
      const allContent = agentFiles!.map((f) => f.content).join("\n");
      expect(allContent.toLowerCase()).toContain("security");
    }
  });

  it("all adapters include verification token", async () => {
    const allAgents = ["claude-code", "cursor", "cline", "windsurf"];
    await createProjectWithAgents(allAgents);

    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    for (const agentId of allAgents) {
      const agentFiles = result.data.filesByAgent[agentId];
      const instructionContent = agentFiles!.map((f) => f.content).join("\n");
      expect(instructionContent).toContain(`${PROJECT_NAME}-`);
    }
  });
});

describe("Adapter Generation: dry-run mode", () => {
  it("dry-run returns files without writing to disk", async () => {
    await createProjectWithAgents(["claude-code"]);
    const config = await resolveConfig(tmpDir);
    expect(config.ok).toBe(true);
    if (!config.ok) return;

    const result = await generate(config.data, tmpDir, { dryRun: true });
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.data.files.length).toBeGreaterThan(0);
    // Files should NOT have been written
    expect(await fileExists(path.join(tmpDir, "CLAUDE.md"))).toBe(false);
  });
});
