import { access } from 'node:fs/promises';
import { join } from 'node:path';
import type {
  AgentAdapter,
  AgentCapabilities,
  AgentPaths,
  GeneratedFile,
  GenerateOptions,
} from '../types/agent.js';
import type { NormalizedConfig } from '../types/config.js';
import { hashContent } from '../utils/hash.js';
import { buildFlagInstructions } from './flag-instructions.js';
import { addGeneratedHeader } from './generated-header.js';
import { generateSkillFiles } from './skill-generator.js';
import { CONTEXT_TOKENS_LARGE, MANIFEST_FILENAME, MCP_FILENAME } from '../constants.js';

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

export const codexAdapter: AgentAdapter = {
  id: 'codex',
  name: 'Codex',

  paths: {
    configRoot: '.codex',
    rules: '.',
    skills: '.agents/skills',
    commands: null,
    agents: '.codex/agents',
    instructionFile: 'AGENTS.md',
    mcpConfig: '.codex/mcp.toml',
  } satisfies AgentPaths,

  capabilities: {
    rules: true,
    skills: true,
    commands: false,
    mcp: true,
    frontmatter: false,
    progressiveLoading: false,
    agents: true,
    maxContextTokens: CONTEXT_TOKENS_LARGE,
  } satisfies AgentCapabilities,

  async detect(projectRoot: string): Promise<boolean> {
    const hasFile = await exists(join(projectRoot, 'AGENTS.md'));
    const hasDir = await exists(join(projectRoot, '.agents'));
    return hasFile || hasDir;
  },

  async generate(config: NormalizedConfig, _options: GenerateOptions): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];
    const flagText = buildFlagInstructions(config.flags);

    // AGENTS.md — behavior guidance only (rules + flags, NOT skills)
    const sections: string[] = [];
    if (flagText) {
      sections.push('## Permissions\n\n' + flagText);
    }
    for (const rule of config.rules) {
      sections.push(`## ${rule.name}\n\n${rule.content}`);
    }
    const content = addGeneratedHeader(sections.join('\n\n'));
    files.push({
      path: 'AGENTS.md',
      content,
      sources: [MANIFEST_FILENAME],
      hash: hashContent(content),
    });

    // Generate .agents/skills/{name}/SKILL.md (auto-discovered by Codex)
    files.push(...generateSkillFiles(config.skills, '.agents/skills'));

    // Generate .codex/agents/{name}.toml (Codex TOML format)
    for (const agent of config.agents) {
      const lines: string[] = [];
      lines.push(`name = "${agent.name}"`);
      lines.push(`description = "${agent.description}"`);
      lines.push(`developer_instructions = """\n${agent.content}\n"""`);
      if (agent.model) lines.push(`model = "${agent.model}"`);
      const tomlContent = addGeneratedHeader(lines.join('\n'), 'toml');
      const fileName = agent.name.toLowerCase().replace(/\s+/g, '-') + '.toml';
      files.push({
        path: `.codex/agents/${fileName}`,
        content: tomlContent,
        sources: [MANIFEST_FILENAME],
        hash: hashContent(tomlContent),
      });
    }

    // Generate .codex/mcp.toml if MCP servers are configured
    if (config.mcp && Object.keys(config.mcp.servers).length > 0) {
      const tomlLines: string[] = ['# Generated by codi | Do not edit — run: codi generate'];
      for (const [name, server] of Object.entries(config.mcp.servers)) {
        tomlLines.push(`\n[mcp_servers.${name}]`);
        tomlLines.push(`command = "${server.command}"`);
        if (server.args) tomlLines.push(`args = [${server.args.map(a => `"${a}"`).join(', ')}]`);
        if (server.env) {
          for (const [k, v] of Object.entries(server.env)) {
            tomlLines.push(`env.${k} = "${v}"`);
          }
        }
      }
      const mcpContent = tomlLines.join('\n');
      files.push({
        path: '.codex/mcp.toml',
        content: mcpContent,
        sources: [MCP_FILENAME],
        hash: hashContent(mcpContent),
      });
    }

    return files;
  },
};
