import { PROJECT_CLI, PROJECT_NAME_DISPLAY } from "../constants.js";

type MarkerFormat = "markdown" | "toml";

export function addGeneratedFooter(
  content: string,
  format: MarkerFormat = "markdown",
): string {
  const text = `Generated by ${PROJECT_NAME_DISPLAY} | Do not edit — run: ${PROJECT_CLI} generate`;
  const marker = format === "toml" ? `# ${text}` : `<!-- ${text} -->`;
  return content + "\n\n" + marker + "\n";
}

/** @deprecated Use addGeneratedFooter */
export const addGeneratedHeader = addGeneratedFooter;
