type MarkerFormat = 'markdown' | 'toml';

export function addGeneratedFooter(
  content: string,
  format: MarkerFormat = 'markdown',
): string {
  const marker =
    format === 'toml'
      ? '# Generated by Codi | Do not edit — run: codi generate'
      : '<!-- Generated by Codi | Do not edit — run: codi generate -->';
  return content + '\n\n' + marker + '\n';
}

/** @deprecated Use addGeneratedFooter */
export const addGeneratedHeader = addGeneratedFooter;
