type HeaderFormat = 'markdown' | 'toml';

export function addGeneratedHeader(
  content: string,
  format: HeaderFormat = 'markdown',
): string {
  const header =
    format === 'toml'
      ? '# Generated by codi | Do not edit — run: codi generate\n\n'
      : '<!-- Generated by codi | Do not edit — run: codi generate -->\n\n';
  return header + content;
}
