import fs from "node:fs/promises";
import path from "node:path";
import { ok, err } from "#src/types/result.js";
import type { Result } from "#src/types/result.js";
import { createError } from "../output/errors.js";
import { hashBuffer, EMPTY_INPUT_SHA256 } from "#src/utils/hash.js";
import { STATE_FILENAME } from "#src/constants.js";

/**
 * State record for a single file generated by a Codi adapter.
 *
 * Stored in `state.json` and used for drift detection: the `generatedHash`
 * is compared against the current on-disk hash to detect user edits.
 */
export interface GeneratedFileState {
  /** Relative path of the generated file (relative to project root). */
  path: string;
  /** Hash of the source artifacts that produced this file. */
  sourceHash: string;
  /** Hash of the file content at generation time. Changes indicate user edits (drift). */
  generatedHash: string;
  /** Names of the source artifacts (rules, skills) that contributed to this file. */
  sources: string[];
  /** ISO 8601 timestamp of when this file was last generated. */
  timestamp: string;
}

/**
 * State record for a single file installed from a preset.
 *
 * Tracks which preset each installed file came from, enabling targeted cleanup
 * when a preset is removed.
 */
export interface ArtifactFileState {
  /** Relative path of the installed artifact file (relative to project root). */
  path: string;
  /** Hash of the file content at installation time. */
  hash: string;
  /** Name of the preset that installed this file. */
  preset: string;
  /** ISO 8601 timestamp of when this file was last installed. */
  timestamp: string;
}

/**
 * The complete state stored in `.codi/state.json`.
 *
 * Tracks all generated files and their hashes to enable drift detection,
 * incremental generation, and preset artifact cleanup.
 */
export interface StateData {
  /** Schema version for forward-compatibility checks. */
  version: "1";
  /** ISO 8601 timestamp of the most recent generation run. */
  lastGenerated: string;
  /** Generated file records keyed by agent id (e.g. "claude-code"). */
  agents: Record<string, GeneratedFileState[]>;
  /** Generated file records for hook scripts. */
  hooks: GeneratedFileState[];
  /** File records for artifacts installed from presets. */
  presetArtifacts?: ArtifactFileState[];
}

/**
 * Drift status for a single generated file.
 *
 * Produced by `StateManager.detectDrift()` by comparing the stored hash
 * against the current on-disk file content.
 */
export interface DriftFile {
  /** Relative path of the file being checked. */
  path: string;
  /**
   * Result of the hash comparison:
   * - `"synced"` - file matches the stored hash (no changes)
   * - `"drifted"` - file exists but its hash differs (user-edited)
   * - `"missing"` - file does not exist on disk
   */
  status: "synced" | "drifted" | "missing";
  /** The hash stored at generation time (present when status is "drifted"). */
  expectedHash?: string;
  /** The hash of the current on-disk content (present when status is "drifted"). */
  currentHash?: string;
}

/**
 * Drift report for all files belonging to a single agent.
 *
 * Returned by `StateManager.detectDrift()`.
 */
export interface DriftReport {
  /** The agent id this report covers (e.g. "claude-code"). */
  agentId: string;
  /** Per-file drift status entries. */
  files: DriftFile[];
}

const EMPTY_STATE: StateData = {
  version: "1",
  lastGenerated: new Date().toISOString(),
  agents: {},
  hooks: [],
};

/**
 * Manages the Codi state file at `.codi/state.json`.
 *
 * The state file tracks all generated files and their hashes, enabling:
 * - **Drift detection**: identify files modified by the user since last generation
 * - **Incremental generation**: skip unchanged files
 * - **Preset cleanup**: remove only files installed by a specific preset
 *
 * @example
 * ```ts
 * const manager = new StateManager('/path/to/.codi', '/path/to/project');
 * const report = await manager.detectDrift('claude-code');
 * if (isOk(report)) {
 *   const drifted = report.data.files.filter(f => f.status === 'drifted');
 *   console.log(`${drifted.length} files modified since last generation`);
 * }
 * ```
 */
export class StateManager {
  private readonly statePath: string;
  private readonly projectRoot: string;

  constructor(configDir: string, projectRoot?: string) {
    this.statePath = path.join(configDir, STATE_FILENAME);
    this.projectRoot = projectRoot ?? path.dirname(configDir);
  }

  /** Reads the state file. Returns an empty state if the file does not exist. */
  async read(): Promise<Result<StateData>> {
    try {
      const raw = await fs.readFile(this.statePath, "utf8");
      const parsed = JSON.parse(raw) as StateData;
      return ok(parsed);
    } catch (cause) {
      if (isNodeError(cause) && cause.code === "ENOENT") {
        return ok(structuredClone(EMPTY_STATE));
      }
      return err([
        createError(
          "E_CONFIG_PARSE_FAILED",
          {
            file: this.statePath,
          },
          cause as Error,
        ),
      ]);
    }
  }

  /** Writes the state file atomically using a temp file + rename. */
  async write(state: StateData): Promise<Result<void>> {
    try {
      const dir = path.dirname(this.statePath);
      await fs.mkdir(dir, { recursive: true });
      const tmpPath = `${this.statePath}.tmp.${Date.now()}`;
      await fs.writeFile(tmpPath, JSON.stringify(state, null, 2), "utf8");
      await fs.rename(tmpPath, this.statePath);
      return ok(undefined);
    } catch (cause) {
      return err([
        createError(
          "E_CONFIG_PARSE_FAILED",
          {
            file: this.statePath,
          },
          cause as Error,
        ),
      ]);
    }
  }

  /** Updates the generated file records for a single agent. */
  async updateAgent(agentId: string, files: GeneratedFileState[]): Promise<Result<void>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;

    const state = stateResult.data;
    state.agents[agentId] = files;
    state.lastGenerated = new Date().toISOString();
    return this.write(state);
  }

  /** Updates the generated file records for multiple agents in a single write. */
  async updateAgentsBatch(updates: Record<string, GeneratedFileState[]>): Promise<Result<void>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;

    const state = stateResult.data;
    for (const [agentId, files] of Object.entries(updates)) {
      state.agents[agentId] = files;
    }
    state.lastGenerated = new Date().toISOString();
    return this.write(state);
  }

  /**
   * Removes agent entries that no longer appear in the active configuration.
   * Called by apply.ts after a customize that unselects one or more agents,
   * so stale entries do not linger and inflate future orphan counts.
   */
  async removeAgents(agentIds: readonly string[]): Promise<Result<void>> {
    if (agentIds.length === 0) return ok(undefined);
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;
    const state = stateResult.data;
    let changed = false;
    for (const id of agentIds) {
      if (id in state.agents) {
        delete state.agents[id];
        changed = true;
      }
    }
    if (!changed) return ok(undefined);
    state.lastGenerated = new Date().toISOString();
    return this.write(state);
  }

  /**
   * Detects orphaned generated files — files that exist in the previous state
   * but are not present in the next generation run. Called BEFORE
   * `updateAgentsBatch` so the previous state is still readable.
   *
   * An orphan is only returned as deletable if its current on-disk hash matches
   * the previously recorded `generatedHash` (meaning no user edits). Drifted
   * orphans (user-edited after generation) are returned in `drifted` so the
   * caller can warn or force-delete via `force: true`.
   *
   * The method does not touch the filesystem or state — it is a pure
   * diff+inspect. Call `deleteOrphans()` to actually unlink the files.
   *
   * @param nextAgents - The new agent-to-files map that will be written on this run.
   */
  async detectOrphans(
    nextAgents: Record<string, GeneratedFileState[]>,
  ): Promise<Result<{ clean: GeneratedFileState[]; drifted: GeneratedFileState[] }>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;

    const prevState = stateResult.data.agents;
    const clean: GeneratedFileState[] = [];
    const drifted: GeneratedFileState[] = [];

    for (const [agentId, prevFiles] of Object.entries(prevState)) {
      const nextPaths = new Set((nextAgents[agentId] ?? []).map((f) => f.path));
      const orphans = prevFiles.filter((f) => !nextPaths.has(f.path));
      for (const orphan of orphans) {
        // Generators that skip hashing binary assets (fonts, PDFs, archives,
        // images) store EMPTY_INPUT_SHA256 as the placeholder. Any current
        // on-disk hash will differ, which would misclassify them as drifted
        // and survive agent unselect. Treat them as clean orphans.
        if (orphan.generatedHash === EMPTY_INPUT_SHA256) {
          clean.push(orphan);
          continue;
        }
        const fullPath = path.resolve(this.projectRoot, orphan.path);
        try {
          const bytes = await fs.readFile(fullPath);
          const currentHash = hashBuffer(bytes);
          if (currentHash === orphan.generatedHash) {
            clean.push(orphan);
          } else {
            drifted.push(orphan);
          }
        } catch (cause) {
          if (isNodeError(cause) && cause.code === "ENOENT") {
            // Already gone from disk — still count as clean so state gets trimmed.
            clean.push(orphan);
          } else {
            // Unreadable for another reason — treat as drifted (keep) to be safe.
            drifted.push(orphan);
          }
        }
      }
    }

    return ok({ clean, drifted });
  }

  /**
   * Unlinks the given orphaned files from disk. Silently ignores files that
   * were already removed. Returns the paths that were actually deleted so the
   * caller can report them.
   *
   * @param orphans - Files returned by `detectOrphans()` (either clean or forced drifted).
   */
  async deleteOrphans(orphans: GeneratedFileState[]): Promise<string[]> {
    const deleted: string[] = [];
    for (const orphan of orphans) {
      const fullPath = path.resolve(this.projectRoot, orphan.path);
      try {
        await fs.unlink(fullPath);
        deleted.push(orphan.path);
        // Prune any now-empty parent dirs up to the project root (non-recursive sweep).
        let dir = path.dirname(fullPath);
        while (dir !== this.projectRoot && dir.startsWith(this.projectRoot)) {
          try {
            await fs.rmdir(dir);
          } catch {
            break; // non-empty or permissions — stop climbing
          }
          dir = path.dirname(dir);
        }
      } catch (cause) {
        if (isNodeError(cause) && cause.code === "ENOENT") {
          deleted.push(orphan.path);
        }
      }
    }
    return deleted;
  }

  /** Updates the generated hook file records. */
  async updateHooks(files: GeneratedFileState[]): Promise<Result<void>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;

    const state = stateResult.data;
    state.hooks = files;
    state.lastGenerated = new Date().toISOString();
    return this.write(state);
  }

  /** Returns the generated file records for a single agent. */
  async getAgentFiles(agentId: string): Promise<Result<GeneratedFileState[]>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;
    return ok(stateResult.data.agents[agentId] ?? []);
  }

  /**
   * Compares the current on-disk files for an agent against their stored hashes.
   *
   * @param agentId - The agent id to check (e.g. "claude-code")
   * @returns A DriftReport listing synced, drifted, and missing files
   */
  async detectDrift(agentId: string): Promise<Result<DriftReport>> {
    const filesResult = await this.getAgentFiles(agentId);
    if (!filesResult.ok) return filesResult;

    const storedFiles = filesResult.data;
    const driftFiles: DriftFile[] = [];

    for (const stored of storedFiles) {
      try {
        const fullPath = path.resolve(this.projectRoot, stored.path);
        const bytes = await fs.readFile(fullPath);
        const currentHash = hashBuffer(bytes);
        if (currentHash === stored.generatedHash) {
          driftFiles.push({ path: stored.path, status: "synced" });
        } else {
          driftFiles.push({
            path: stored.path,
            status: "drifted",
            expectedHash: stored.generatedHash,
            currentHash,
          });
        }
      } catch {
        driftFiles.push({ path: stored.path, status: "missing" });
      }
    }

    return ok({ agentId, files: driftFiles });
  }

  /** Merges new preset artifact records into the state, updating existing entries by path. */
  async updatePresetArtifacts(files: ArtifactFileState[]): Promise<Result<void>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;

    const state = stateResult.data;
    // Merge: update existing entries by path, add new ones
    const existing = new Map((state.presetArtifacts ?? []).map((f) => [f.path, f]));
    for (const file of files) {
      existing.set(file.path, file);
    }
    state.presetArtifacts = [...existing.values()];
    return this.write(state);
  }

  /** Compares the current on-disk preset artifact files against their stored hashes. */
  async detectPresetArtifactDrift(): Promise<Result<DriftFile[]>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;

    const stored = stateResult.data.presetArtifacts ?? [];
    const driftFiles: DriftFile[] = [];

    for (const entry of stored) {
      try {
        const fullPath = path.resolve(this.projectRoot, entry.path);
        const bytes = await fs.readFile(fullPath);
        const currentHash = hashBuffer(bytes);
        if (currentHash === entry.hash) {
          driftFiles.push({ path: entry.path, status: "synced" });
        } else {
          driftFiles.push({
            path: entry.path,
            status: "drifted",
            expectedHash: entry.hash,
            currentHash,
          });
        }
      } catch {
        driftFiles.push({ path: entry.path, status: "missing" });
      }
    }

    return ok(driftFiles);
  }

  /** Compares the current on-disk hook files against their stored hashes. */
  async detectHookDrift(): Promise<Result<DriftFile[]>> {
    const stateResult = await this.read();
    if (!stateResult.ok) return stateResult;

    const storedHooks = stateResult.data.hooks;
    const driftFiles: DriftFile[] = [];

    for (const stored of storedHooks) {
      try {
        const fullPath = path.resolve(this.projectRoot, stored.path);
        const bytes = await fs.readFile(fullPath);
        const currentHash = hashBuffer(bytes);
        if (currentHash === stored.generatedHash) {
          driftFiles.push({ path: stored.path, status: "synced" });
        } else {
          driftFiles.push({
            path: stored.path,
            status: "drifted",
            expectedHash: stored.generatedHash,
            currentHash,
          });
        }
      } catch {
        driftFiles.push({ path: stored.path, status: "missing" });
      }
    }

    return ok(driftFiles);
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
