/* eslint-disable @typescript-eslint/no-unused-vars */
// ====== Presets — style templates with full slide decks ======
// Browser-served globals: PRESETS and FONTS_LINK are consumed by app.js via script concatenation.
// Each preset has type (social | slides | document), native format, and 3-4 slides.

const FONTS_LINK =
  '<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=Geist+Mono:wght@300;400;500&display=swap" rel="stylesheet">';

const PRESETS = [
  {
    id: "dark-editorial",
    name: "Dark Editorial",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Deep dark base, gradient italic accents, progress track",
    css: [
      "body{background:#070a0f;font-family:'Outfit',sans-serif;color:#e6edf3}",
      ".c{width:100%;height:100%;display:flex;flex-direction:column;padding:52px;position:relative;background:#070a0f}",
      ".tag{font-family:'Geist Mono',monospace;font-size:22px;color:#56b6c2;margin-bottom:24px;letter-spacing:.08em}",
      ".h{font-size:80px;font-weight:800;line-height:1.1;letter-spacing:-.03em;margin-bottom:28px}",
      "em{font-style:italic;padding-right:0.12em;background:linear-gradient(135deg,#56b6c2,#61afef);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}",
      ".b{font-size:32px;font-weight:300;color:rgba(230,237,243,.7);line-height:1.5;flex:1}",
      ".bar{position:absolute;bottom:0;left:0;right:0;height:80px;background:rgba(0,0,0,.28);border-top:1px solid rgba(255,255,255,.07);display:flex;align-items:center;padding:0 52px;gap:12px}",
      ".hn{font-family:'Geist Mono',monospace;font-size:22px;color:#e6edf3}",
      ".dots{display:flex;gap:8px;margin-left:auto}",
      ".dot{width:28px;height:6px;border-radius:3px;background:rgba(255,255,255,.12)}",
      ".dot.on{background:linear-gradient(135deg,#56b6c2,#61afef)}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="tag">01 · INTRO</div><div class="h">Your rules,<br><em>your agents</em></div><div class="b">One config source.<br>All AI tools, in sync.</div><div class="bar"><span class="hn">@handle</span><div class="dots"><div class="dot on"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div></div></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="tag">02 · PROBLEM</div><div class="h">5 configs.<br><em>One mess.</em></div><div class="b">Claude, Cursor, Copilot, Gemini — each needs its own rules file. Manually synced.</div><div class="bar"><span class="hn">@handle</span><div class="dots"><div class="dot"></div><div class="dot on"></div><div class="dot"></div><div class="dot"></div></div></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "03",
        html: '<div class="c"><div class="tag">03 · SOLUTION</div><div class="h">codi<br><em>fixes this.</em></div><div class="b">Write once in .codi/<br>Generate config for every tool.</div><div class="bar"><span class="hn">@handle</span><div class="dots"><div class="dot"></div><div class="dot"></div><div class="dot on"></div><div class="dot"></div></div></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "04",
        html: '<div class="c"><div class="tag">04 · START</div><div class="h">Ship<br><em>today.</em></div><div class="b">npm install -g codi-cli<br>codi init</div><div class="bar"><span class="hn">@handle</span><div class="dots"><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot on"></div></div></div></div>',
      },
    ],
  },

  {
    id: "minimal-mono",
    name: "Minimal Mono",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Monospace type, thin accent border, high contrast hierarchy",
    css: [
      "body{background:#0a0e13;font-family:'Geist Mono',monospace;color:#e6edf3}",
      ".c{width:100%;height:100%;display:flex;flex-direction:column;padding:60px;border:1px solid rgba(86,182,194,.18);background:#0a0e13}",
      ".tag{font-size:18px;font-weight:300;color:rgba(86,182,194,.7);margin-bottom:auto;letter-spacing:.12em;text-transform:uppercase}",
      ".h{font-size:100px;font-weight:300;line-height:1.1;letter-spacing:-.04em;margin-bottom:24px}",
      ".ac{color:#56b6c2}",
      ".b{font-size:26px;font-weight:300;color:rgba(230,237,243,.5);line-height:1.6;margin-bottom:48px}",
      ".foot{display:flex;justify-content:space-between;align-items:flex-end}",
      ".hn{font-size:20px;color:rgba(86,182,194,.5)}",
      ".num{font-size:80px;font-weight:200;color:rgba(86,182,194,.1);line-height:1}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="tag">INTRODUCING</div><div class="h">codi<span class="ac">.</span></div><div class="b">Unified config platform<br>for AI coding agents</div><div class="foot"><span class="hn">@handle</span><span class="num">01</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="tag">FEATURES</div><div class="h">one<span class="ac">/</span>all</div><div class="b">· rules &amp; skills<br>· agents &amp; tools<br>· every AI tool</div><div class="foot"><span class="hn">@handle</span><span class="num">02</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div class="tag">GET STARTED</div><div class="h">npm<span class="ac">.</span></div><div class="b">npm i -g codi-cli<br>codi init</div><div class="foot"><span class="hn">@handle</span><span class="num">03</span></div></div>',
      },
    ],
  },

  {
    id: "poster-bold",
    name: "Poster Bold",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Oversized type, maximum graphic impact, full-bleed layout",
    css: [
      "body{background:#070a0f;font-family:'Outfit',sans-serif;color:#e6edf3;overflow:hidden}",
      ".c{width:100%;height:100%;display:flex;flex-direction:column;justify-content:space-between;padding:60px 60px 0}",
      ".h{font-size:156px;font-weight:900;line-height:1.1;letter-spacing:-.05em}",
      "em{font-style:italic;padding-right:0.12em;background:linear-gradient(135deg,#56b6c2,#61afef);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}",
      ".sub{font-size:36px;font-weight:300;color:rgba(230,237,243,.45)}",
      ".bar{height:100px;background:linear-gradient(90deg,rgba(86,182,194,.1),transparent);border-top:2px solid rgba(86,182,194,.25);display:flex;align-items:center;padding:0 60px;margin:0 -60px}",
      ".hn{font-family:'Geist Mono',monospace;font-size:24px;color:rgba(86,182,194,.6)}",
      ".mark{font-family:'Geist Mono',monospace;font-size:24px;font-weight:500;background:linear-gradient(135deg,#56b6c2,#61afef);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-left:auto}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div><div class="h">One<br><em>config.</em></div><div class="sub">Every AI tool.</div></div><div class="bar"><span class="hn">@handle</span><span class="mark">codi</span></div></div>',
      },
      {
        dataType: "stat",
        dataIndex: "02",
        html: '<div class="c"><div><div class="h"><em>5x</em><br>faster.</div><div class="sub">Config sync across all agents.</div></div><div class="bar"><span class="hn">@handle</span><span class="mark">codi</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div><div class="h">Start<br><em>now.</em></div><div class="sub">npm install -g codi-cli</div></div><div class="bar"><span class="hn">@handle</span><span class="mark">codi</span></div></div>',
      },
    ],
  },

  {
    id: "clean-slides",
    name: "Clean Slides",
    type: "slides",
    format: { w: 1280, h: 720 },
    desc: "16:9 presentation deck, dark base, accent headlines",
    css: [
      "body{background:#0d1117;font-family:'Outfit',sans-serif;color:#e6edf3;margin:0;overflow:hidden}",
      ".c{width:1280px;height:720px;display:flex;flex-direction:column;padding:64px 80px;position:relative;background:#0d1117}",
      ".tag{font-family:'Geist Mono',monospace;font-size:16px;color:rgba(86,182,194,.6);margin-bottom:20px;letter-spacing:.1em;text-transform:uppercase}",
      ".h{font-size:72px;font-weight:800;line-height:1.1;letter-spacing:-.03em;margin-bottom:20px}",
      "em{font-style:italic;padding-right:0.12em;background:linear-gradient(135deg,#56b6c2,#61afef);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}",
      ".b{font-size:26px;font-weight:300;color:rgba(230,237,243,.65);line-height:1.5;flex:1}",
      ".bar{position:absolute;bottom:0;left:0;right:0;height:60px;background:rgba(0,0,0,.3);border-top:1px solid rgba(255,255,255,.06);display:flex;align-items:center;padding:0 80px}",
      ".hn{font-family:'Geist Mono',monospace;font-size:16px;color:rgba(230,237,243,.45)}",
      ".num{font-family:'Geist Mono',monospace;font-size:16px;color:rgba(86,182,194,.35);margin-left:auto}",
      "ul{list-style:none;padding:0;font-size:26px;font-weight:300;color:rgba(230,237,243,.7);line-height:1.9}",
      "li::before{content:'→ ';color:#56b6c2}",
    ].join(""),
    slides: [
      {
        dataType: "title",
        dataIndex: "01",
        html: '<div class="c"><div class="tag">CODI</div><div class="h">Your rules,<br><em>your agents</em></div><div class="b">One config source — all AI tools in sync</div><div class="bar"><span class="hn">@handle</span><span class="num">01</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="tag">THE PROBLEM</div><div class="h">Too many<br><em>configs.</em></div><ul><li>Claude, Cursor, Copilot</li><li>Each needs its own rules file</li><li>Manually synced — or drifted</li></ul><div class="bar"><span class="hn">@handle</span><span class="num">02</span></div></div>',
      },
      {
        dataType: "closing",
        dataIndex: "03",
        html: '<div class="c"><div class="tag">SHIP TODAY</div><div class="h">npm i -g<br><em>codi-cli</em></div><div class="b">codi init · codi generate · done</div><div class="bar"><span class="hn">@handle</span><span class="num">03</span></div></div>',
      },
    ],
  },

  {
    id: "doc-article",
    name: "Doc Article",
    type: "document",
    format: { w: 794, h: 1123 },
    desc: "A4 document layout, clean editorial, print-ready",
    css: [
      "body{background:#fff;font-family:'Outfit',sans-serif;color:#0d1117;margin:0;overflow:hidden}",
      ".c{width:794px;height:1123px;display:flex;flex-direction:column;padding:72px;position:relative;background:#fff}",
      ".accent{height:4px;background:linear-gradient(90deg,#56b6c2,#61afef);margin:-72px -72px 56px;width:calc(100% + 144px)}",
      ".tag{font-family:'Geist Mono',monospace;font-size:13px;color:rgba(86,182,194,.75);margin-bottom:16px;letter-spacing:.1em;text-transform:uppercase}",
      ".h{font-size:52px;font-weight:800;line-height:1.1;letter-spacing:-.02em;margin-bottom:24px;color:#0d1117}",
      "em{font-style:italic;padding-right:0.12em;background:linear-gradient(135deg,#56b6c2,#61afef);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}",
      ".b{font-size:19px;font-weight:300;color:#444d56;line-height:1.75;flex:1}",
      "p{margin:0 0 18px}",
      "code{font-family:'Geist Mono',monospace;font-size:15px;background:#f1f3f5;padding:2px 8px;border-radius:4px;color:#0d1117}",
      ".foot{font-family:'Geist Mono',monospace;font-size:12px;color:rgba(86,182,194,.5);padding-top:20px;border-top:1px solid #e1e4e8;display:flex;justify-content:space-between}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="accent"></div><div class="tag">ARTICLE</div><div class="h">Your rules,<br><em>your agents</em></div><div class="b"><p>One config source. All AI coding tools, in sync.</p><p>codi manages rules, skills, and agent configuration across Claude, Cursor, Copilot, and more — from a single source of truth.</p></div><div class="foot"><span>@handle</span><span>01 / 03</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="accent"></div><div class="tag">THE PROBLEM</div><div class="h">Config<br><em>sprawl</em></div><div class="b"><p>Every AI coding tool ships with its own config format. Claude uses CLAUDE.md, Cursor uses .cursorrules, Copilot uses its own instructions file.</p><p>Teams end up manually maintaining 5 separate config files with duplicate rules, diverging conventions, and no single source of truth.</p></div><div class="foot"><span>@handle</span><span>02 / 03</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div class="accent"></div><div class="tag">GET STARTED</div><div class="h">Ship<br><em>today</em></div><div class="b"><p>Getting started takes two commands:</p><p><code>npm install -g codi-cli</code><br><code>codi init</code></p><p>codi detects your project stack, generates starter rules, and sets up config for every AI tool you use.</p></div><div class="foot"><span>@handle</span><span>03 / 03</span></div></div>',
      },
    ],
  },

  // ── Earthy Bold ──────────────────────────────────────────────────────────
  {
    id: "earthy-bold",
    name: "Earthy Bold",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Olive green base, heavy all-caps headline, warm gold italic accent",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#636642;font-family:'Outfit',sans-serif;color:#fff}",
      ".c{width:100%;height:100%;background:#636642;display:flex;flex-direction:column;padding:64px 68px;overflow:hidden}",
      ".sp{flex:1}",
      ".sp-sm{height:32px;flex-shrink:0}",
      ".cat{font-size:16px;font-weight:600;letter-spacing:.22em;text-transform:uppercase;color:rgba(255,255,255,.60);margin-bottom:20px;flex-shrink:0}",
      ".h{font-size:110px;font-weight:900;line-height:1.0;letter-spacing:-.03em;text-transform:uppercase;color:#fff;margin-bottom:28px;flex-shrink:0}",
      ".bod{font-size:25px;font-weight:800;line-height:1.35;letter-spacing:-.01em;text-transform:uppercase;color:rgba(255,255,255,.90);margin-bottom:20px;flex-shrink:0}",
      ".gold{font-size:28px;font-weight:700;font-style:italic;color:#d4a96a;line-height:1.3;padding-right:.12em;display:block;flex-shrink:0}",
      ".div{height:1px;background:rgba(255,255,255,.22);margin-bottom:22px;flex-shrink:0}",
      ".bar{display:flex;justify-content:space-between;align-items:center;flex-shrink:0}",
      ".hn{font-size:15px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:rgba(255,255,255,.50)}",
      ".sw{font-size:15px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.50)}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="sp"></div><div class="cat">The Big Idea</div><div class="h">Your AI<br>Finally<br>Listens.</div><p class="bod">Stop repeating yourself.<br>Codi installs best practices<br>that actually stick.</p><em class="gold">Here\'s what that looks like...</em><div class="sp-sm"></div><div class="div"></div><div class="bar"><span class="hn">@handle</span><span class="sw">Swipe →</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="sp"></div><div class="cat">The Rules</div><div class="h">No More<br>Repeating<br>Yourself.</div><p class="bod">Codi installs standards that<br>follow your AI everywhere,<br>automatically.</p><em class="gold">TypeScript, testing, security, architecture — covered.</em><div class="sp-sm"></div><div class="div"></div><div class="bar"><span class="hn">@handle</span><span class="sw">Swipe →</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div class="sp"></div><div class="cat">The Move</div><div class="h">Two<br>Commands.<br>Done.</div><p class="bod">Install codi-cli globally.<br>Run codi init in your project.<br>Done in 30 seconds.</p><em class="gold">Open source. github.com/lehidalgo/codi</em><div class="sp-sm"></div><div class="div"></div><div class="bar"><span class="hn">@handle</span><span class="sw">Get Started →</span></div></div>',
      },
    ],
  },

  // ── Terminal Green ────────────────────────────────────────────────────────
  {
    id: "terminal-green",
    name: "Terminal Green",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Dark terminal aesthetic with scanlines, neon green accents, and corner brackets",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#030a04;font-family:'Outfit',sans-serif;color:#e8f5e8}",
      ".c{width:100%;height:100%;overflow:hidden;display:flex;flex-direction:column;padding:48px 52px;position:relative;background:radial-gradient(ellipse at 38% 38%,rgba(0,55,5,.50) 0%,transparent 58%),repeating-linear-gradient(0deg,transparent,transparent 3px,rgba(0,0,0,.13) 3px,rgba(0,0,0,.13) 4px),#030a04}",
      ".cr{position:absolute;width:34px;height:34px;border-color:#39ff7a;border-style:solid;border-width:0}",
      ".tl{top:36px;left:36px;border-top-width:2px;border-left-width:2px}",
      ".tr{top:36px;right:36px;border-top-width:2px;border-right-width:2px}",
      ".bl{bottom:92px;left:36px;border-bottom-width:2px;border-left-width:2px}",
      ".br{bottom:92px;right:36px;border-bottom-width:2px;border-right-width:2px}",
      ".top{display:flex;align-items:flex-start;flex-shrink:0}",
      ".pill{display:inline-flex;align-items:center;background:#39ff7a;color:#030a04;font-family:'Geist Mono',monospace;font-size:16px;font-weight:500;padding:7px 16px;border-radius:4px;letter-spacing:.05em}",
      ".main{flex:1;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:0 40px}",
      ".h{font-size:84px;font-weight:800;line-height:1.1;letter-spacing:-.03em;color:#fff;margin-bottom:28px}",
      ".sub{font-size:26px;font-weight:400;line-height:1.5;color:rgba(232,245,232,.55);max-width:680px}",
      ".hm{font-family:'Geist Mono',monospace;font-size:58px;font-weight:500;line-height:1.15;letter-spacing:-.02em;color:#39ff7a;margin-bottom:28px}",
      ".foot{flex-shrink:0}",
      ".sr{text-align:right;font-family:'Geist Mono',monospace;font-size:13px;letter-spacing:.12em;color:#39ff7a;margin-bottom:14px}",
      ".dv{height:1px;background:rgba(57,255,122,.18);margin-bottom:16px}",
      ".bar{display:flex;justify-content:space-between;align-items:flex-end}",
      ".brand{font-family:'Geist Mono',monospace;font-size:13px;font-weight:500;color:rgba(232,245,232,.75);letter-spacing:.07em;text-transform:uppercase;line-height:1.0}",
      ".bsub{display:block;font-size:11px;font-weight:400;color:rgba(232,245,232,.38);margin-top:4px;letter-spacing:.04em;text-transform:none}",
      ".cnt{font-family:'Geist Mono',monospace;font-size:13px;color:rgba(232,245,232,.38);letter-spacing:.06em}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="cr tl"></div><div class="cr tr"></div><div class="cr bl"></div><div class="cr br"></div><div class="top"><div class="pill">&gt; codi.exe</div></div><div class="main"><div class="h">Your AI Tools<br>Finally Agree</div><p class="sub">One config. All your AI assistants.<br>Zero repeated setup.</p></div><div class="foot"><div class="sr">SWIPE →</div><div class="dv"></div><div class="bar"><div class="brand">CODI<span class="bsub">github.com/lehidalgo/codi · @handle</span></div><div class="cnt">01 / 03</div></div></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="cr tl"></div><div class="cr tr"></div><div class="cr bl"></div><div class="cr br"></div><div class="top"><div class="pill">&gt; features.exe</div></div><div class="main"><div class="h">Rules. Skills.<br>Agents.</div><p class="sub">The three primitives that make your AI<br>actually good at its job.</p></div><div class="foot"><div class="sr">SWIPE →</div><div class="dv"></div><div class="bar"><div class="brand">CODI<span class="bsub">github.com/lehidalgo/codi · @handle</span></div><div class="cnt">02 / 03</div></div></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div class="cr tl"></div><div class="cr tr"></div><div class="cr bl"></div><div class="cr br"></div><div class="top"><div class="pill">&gt; install.exe</div></div><div class="main"><div class="hm">npm install -g codi-cli<br>codi init</div><p class="sub">Claude Code · Cursor · Windsurf · GitHub Copilot<br>All your AI tools, one config.</p></div><div class="foot"><div class="sr">GET STARTED →</div><div class="dv"></div><div class="bar"><div class="brand">CODI<span class="bsub">github.com/lehidalgo/codi · @handle</span></div><div class="cnt">03 / 03</div></div></div></div>',
      },
    ],
  },

  // ── Glass Card ────────────────────────────────────────────────────────────
  {
    id: "glass-card",
    name: "Glass Card",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Space-purple gradient, frosted glass panels, violet/blue gradient accents, image placeholders",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#111;font-family:'Outfit',sans-serif;color:#fff}",
      ".c{position:relative;width:100%;height:100%;overflow:hidden;display:flex;flex-direction:column;background:linear-gradient(135deg,#0f0c29 0%,#302b63 50%,#24243e 100%)}",
      ".bg{position:absolute;inset:0;background:linear-gradient(135deg,#0f0c29 0%,#302b63 50%,#24243e 100%)}",
      ".orb{position:absolute;border-radius:50%;pointer-events:none}",
      ".o1{top:-100px;right:-80px;width:380px;height:380px;background:rgba(139,92,246,.40);filter:blur(90px)}",
      ".o2{bottom:-80px;left:-60px;width:300px;height:300px;background:rgba(59,130,246,.28);filter:blur(80px)}",
      ".o3{top:45%;left:35%;width:220px;height:220px;background:rgba(236,72,153,.18);filter:blur(80px)}",
      ".inn{position:relative;z-index:2;flex:1;display:flex;flex-direction:column;padding:56px;justify-content:center;align-items:center}",
      ".gp{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.13);border-radius:24px;backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px)}",
      ".lbl{font-family:'Geist Mono',monospace;font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:rgba(167,139,250,.70);margin-bottom:32px}",
      ".h{font-size:92px;font-weight:800;line-height:1.1;letter-spacing:-.04em;margin-bottom:28px}",
      "em.acc{font-style:italic;font-weight:800;padding-right:.12em;background:linear-gradient(135deg,#a78bfa,#60a5fa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}",
      ".sub{font-size:24px;color:rgba(255,255,255,.80);line-height:1.55;max-width:620px}",
      ".fbar{position:relative;z-index:2;height:80px;background:rgba(0,0,0,.25);border-top:1px solid rgba(255,255,255,.13);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);flex-shrink:0;display:flex;align-items:center;justify-content:space-between;padding:0 56px}",
      ".hn{font-family:'Geist Mono',monospace;font-size:20px;color:rgba(255,255,255,.80)}",
      ".dots{display:flex;gap:8px;align-items:center}",
      ".dot{width:8px;height:8px;border-radius:50%;background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.18)}",
      ".dot.on{background:rgba(167,139,250,.70);border-color:rgba(167,139,250,.90)}",
      ".fr{display:flex;align-items:flex-start;gap:20px;padding:20px 0;border-bottom:1px solid rgba(255,255,255,.13)}",
      ".fr:last-child{border-bottom:none}",
      ".fd{width:8px;height:8px;border-radius:50%;background:linear-gradient(135deg,#a78bfa,#60a5fa);flex-shrink:0;margin-top:8px}",
      ".cb{background:rgba(0,0,0,.35);border:1px solid rgba(167,139,250,.20);border-radius:12px;padding:22px 28px;font-family:'Geist Mono',monospace;font-size:22px;color:#a78bfa;display:flex;align-items:center;gap:12px}",
      ".cp{color:rgba(255,255,255,.25)}",
      ".ph{background:rgba(255,255,255,.04);border:1.5px dashed rgba(255,255,255,.18);border-radius:16px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;color:rgba(255,255,255,.30)}",
      ".ph-lbl{font-family:'Geist Mono',monospace;font-size:13px;letter-spacing:.12em;text-transform:uppercase}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div><div class="inn"><div class="gp" style="width:880px;padding:72px 68px 68px;display:flex;flex-direction:column;align-items:flex-start"><p class="lbl">Introducing codi</p><h1 class="h">Your AI,<br><em class="acc">finally in sync.</em></h1><p class="sub">One unified config source for every AI coding tool — rules, skills, and agents in sync.</p></div></div><div class="fbar"><span class="hn">@handle</span><div class="dots"><div class="dot on"></div><div class="dot"></div><div class="dot"></div></div></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="orb o1" style="top:-60px;right:-40px;width:300px;height:300px"></div><div class="orb o2"></div><div class="inn"><div class="gp" style="width:900px;padding:40px 48px 48px;display:flex;flex-direction:column;gap:28px"><div class="ph" style="height:260px"><svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg><span class="ph-lbl">Photo / Video</span></div><div style="display:flex;flex-direction:column"><div class="fr"><div class="fd" style="margin-top:10px"></div><div><p style="font-size:22px;font-weight:700;margin-bottom:4px">Rules</p><p style="font-size:18px;color:rgba(255,255,255,.80);line-height:1.5">Coding standards that propagate to every tool automatically.</p></div></div><div class="fr"><div class="fd" style="margin-top:10px"></div><div><p style="font-size:22px;font-weight:700;margin-bottom:4px">Skills</p><p style="font-size:18px;color:rgba(255,255,255,.80);line-height:1.5">Reusable workflows triggered by intent — commit, review, deploy.</p></div></div><div class="fr"><div class="fd" style="margin-top:10px"></div><div><p style="font-size:22px;font-weight:700;margin-bottom:4px">Agents</p><p style="font-size:18px;color:rgba(255,255,255,.80);line-height:1.5">Domain experts that activate on the right task, every time.</p></div></div></div></div></div><div class="fbar"><span class="hn">@handle</span><div class="dots"><div class="dot"></div><div class="dot on"></div><div class="dot"></div></div></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div class="orb o1"></div><div class="orb o2" style="bottom:-40px;left:-40px;width:360px;height:360px;background:rgba(59,130,246,.32)"></div><div class="orb o3" style="top:30%;left:20%;background:rgba(236,72,153,.22)"></div><div class="inn"><div class="gp" style="width:880px;padding:64px 68px;display:flex;flex-direction:column;gap:32px"><div><p class="lbl">Get started</p><h2 style="font-size:80px;font-weight:800;line-height:1.1;letter-spacing:-.04em;margin-bottom:16px">Ship in<br><em class="acc">30 seconds.</em></h2><p class="sub" style="font-size:21px">Install codi, run init, and every AI tool gets your config.</p></div><div style="display:flex;flex-direction:column;gap:12px"><div class="cb"><span class="cp">$</span> npm install -g codi-cli</div><div class="cb"><span class="cp">$</span> codi init &amp;&amp; codi generate</div></div></div></div><div class="fbar"><span class="hn">@handle</span><div class="dots"><div class="dot"></div><div class="dot"></div><div class="dot on"></div></div></div></div>',
      },
    ],
  },

  // ── Split Photo ───────────────────────────────────────────────────────────
  {
    id: "split-photo",
    name: "Split Photo",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "White background, split-column layout with image placeholder, gradient left column",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#e5e7eb;font-family:'Outfit',sans-serif;color:#0d1117}",
      ".c{position:relative;width:100%;height:100%;background:#fff;overflow:hidden;display:flex;flex-direction:row}",
      ".ic{position:relative;flex-shrink:0;display:flex;align-items:center;justify-content:center;overflow:hidden}",
      ".ic-in{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;color:rgba(255,255,255,.55)}",
      ".cc{flex:1;display:flex;flex-direction:column;padding:60px 56px;position:relative}",
      ".tag{font-family:'Geist Mono',monospace;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:#56b6c2;margin-bottom:24px}",
      ".h{font-size:80px;font-weight:900;line-height:1.1;letter-spacing:-.04em;color:#0d1117;margin-bottom:28px}",
      ".h2{font-size:60px;font-weight:900;line-height:1.1;letter-spacing:-.04em;color:#0d1117;margin-bottom:36px}",
      ".sub{font-size:22px;color:#6b7280;line-height:1.6}",
      ".hbar{margin-top:auto;display:flex;align-items:center;justify-content:space-between}",
      ".hn{font-family:'Geist Mono',monospace;font-size:18px;color:#6b7280}",
      ".bi{display:flex;align-items:flex-start;gap:16px;padding:18px 0;border-bottom:1px solid #f0f0f0}",
      ".bi:last-child{border-bottom:none}",
      ".ba{width:4px;height:4px;border-radius:50%;background:#56b6c2;flex-shrink:0;margin-top:11px}",
      ".cp{display:inline-block;background:#f3f4f6;border:1px solid #e5e7eb;border-radius:8px;padding:14px 20px;font-family:'Geist Mono',monospace;font-size:19px;color:#0d1117}",
      ".cam{opacity:.45}",
      ".il{font-family:'Geist Mono',monospace;font-size:12px;letter-spacing:.15em;text-transform:uppercase}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="ic" style="width:540px;height:1080px;background:linear-gradient(160deg,#667eea 0%,#764ba2 100%)"><div class="ic-in"><svg class="cam" width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg><span class="il" style="color:rgba(255,255,255,.45)">Photo / Video</span></div></div><div class="cc"><div class="tag">Unified AI config</div><div style="flex:1;display:flex;flex-direction:column;justify-content:center"><h1 class="h">One config.<br>All your AI.</h1><p class="sub">Write rules, skills, and agents once. Codi generates every tool\'s config automatically.</p></div><div class="hbar"><span class="hn">@handle</span><span style="font-family:\'Geist Mono\',monospace;font-size:13px;color:#d1d5db">1 / 3</span></div></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="cc"><div class="tag">How it works</div><h2 class="h2">Rules, Skills,<br>Agents.</h2><div style="display:flex;flex-direction:column"><div class="bi"><div class="ba"></div><div><p style="font-size:20px;font-weight:700;color:#0d1117;margin-bottom:4px">Rules</p><p style="font-size:17px;color:#6b7280;line-height:1.5">Coding standards pushed to Claude Code, Cursor, Windsurf, and more.</p></div></div><div class="bi"><div class="ba"></div><div><p style="font-size:20px;font-weight:700;color:#0d1117;margin-bottom:4px">Skills</p><p style="font-size:17px;color:#6b7280;line-height:1.5">Reusable workflows — commit, review, refactor — triggered by intent.</p></div></div><div class="bi"><div class="ba"></div><div><p style="font-size:20px;font-weight:700;color:#0d1117;margin-bottom:4px">Agents</p><p style="font-size:17px;color:#6b7280;line-height:1.5">Domain experts — security, performance, architecture — ready on demand.</p></div></div></div><div class="hbar"><span class="hn">@handle</span><span style="font-family:\'Geist Mono\',monospace;font-size:13px;color:#d1d5db">2 / 3</span></div></div><div class="ic" style="width:540px;height:1080px;background:linear-gradient(160deg,#f093fb 0%,#f5576c 100%)"><div class="ic-in"><svg class="cam" width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg><span class="il" style="color:rgba(255,255,255,.45)">Photo / Video</span></div></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c" style="flex-direction:column"><div style="position:absolute;inset:0;background:linear-gradient(160deg,#4facfe 0%,#00f2fe 100%);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px"><svg width="56" height="56" viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,.30)" stroke-width="1.1" stroke-linecap="round" stroke-linejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg><span style="font-family:\'Geist Mono\',monospace;font-size:12px;letter-spacing:.15em;text-transform:uppercase;color:rgba(255,255,255,.30)">Photo / Video</span></div><div style="position:absolute;bottom:0;left:0;right:0;height:320px;background:#fff;padding:40px 60px 44px;display:flex;flex-direction:column;justify-content:space-between"><div><h2 style="font-size:52px;font-weight:900;line-height:1.1;letter-spacing:-.04em;color:#0d1117;margin-bottom:20px">Start in 30 seconds.</h2><div class="cp">npm install -g codi-cli &nbsp;·&nbsp; codi init</div></div><div style="display:flex;align-items:center;justify-content:space-between"><span class="hn">@handle</span><span style="font-family:\'Geist Mono\',monospace;font-size:13px;color:#56b6c2">3 / 3</span></div></div></div>',
      },
    ],
  },

  // ── BBVA Social ───────────────────────────────────────────────────────────
  {
    id: "bbva-social",
    name: "BBVA Social",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "BBVA navy brand, aqua gradient accent bar, feature cards, bold italic gradient headline",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#001a45;font-family:'Outfit',sans-serif;color:#fff}",
      ".c{position:relative;width:100%;height:100%;background:#002C6E;overflow:hidden;display:flex;flex-direction:column}",
      ".ab{width:100%;height:3px;background:linear-gradient(90deg,#1CA0D4,#49C4E5,transparent);flex-shrink:0}",
      ".inn{flex:1;padding:40px 60px 36px;display:flex;flex-direction:column;position:relative}",
      ".ft{height:76px;border-top:1px solid rgba(255,255,255,.10);background:rgba(0,0,0,.18);flex-shrink:0;display:flex;align-items:center;justify-content:space-between;padding:0 60px}",
      ".hn{font-family:'Geist Mono',monospace;font-size:18px;color:rgba(255,255,255,.60)}",
      ".url{font-family:'Geist Mono',monospace;font-size:16px;color:rgba(28,160,212,.65)}",
      ".bl{font-family:'Geist Mono',monospace;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:rgba(28,160,212,.65)}",
      "em.acc{font-style:italic;font-weight:800;padding-right:.12em;background:linear-gradient(135deg,#1CA0D4,#49C4E5);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}",
      ".fc{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.10);border-radius:14px;padding:24px 28px;display:flex;align-items:flex-start;gap:20px}",
      ".fi{width:44px;height:44px;border-radius:10px;background:rgba(28,160,212,.15);border:1px solid rgba(28,160,212,.25);flex-shrink:0;display:flex;align-items:center;justify-content:center}",
      ".cb{border:2px solid rgba(28,160,212,.50);border-radius:14px;padding:24px 36px;display:flex;align-items:center;justify-content:center;background:rgba(28,160,212,.06)}",
      ".gl{position:absolute;border-radius:50%;pointer-events:none}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="ab"></div><div class="gl" style="top:-120px;right:-80px;width:500px;height:500px;background:radial-gradient(ellipse,rgba(28,160,212,.12) 0%,transparent 65%)"></div><div class="inn" style="justify-content:space-between"><div><p class="bl">BBVA Digital Banking</p></div><div><h1 style="font-size:86px;font-weight:800;line-height:1.1;letter-spacing:-.04em;margin-bottom:32px">Built for the<br>future of<br><em class="acc">finance.</em></h1><p style="font-size:24px;color:rgba(255,255,255,.75);line-height:1.55;max-width:800px">Real-time payments, instant decisions, and personalized experiences — all powered by a digital-first platform.</p></div><div style="display:flex;align-items:center;gap:16px"><div style="width:120px;height:3px;background:linear-gradient(90deg,#1CA0D4,#49C4E5);border-radius:2px"></div><p style="font-size:18px;color:rgba(255,255,255,.40)">Innovation in every transaction</p></div></div><div class="ft"><span class="hn">@handle</span><span class="url">bbva.com</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="ab"></div><div class="gl" style="bottom:-80px;left:-60px;width:450px;height:450px;background:radial-gradient(ellipse,rgba(73,196,229,.10) 0%,transparent 65%)"></div><div class="inn" style="justify-content:space-between"><div style="display:flex;align-items:baseline;gap:20px;margin-bottom:8px"><span style="font-size:72px;font-weight:800;font-style:italic;padding-right:.12em;background:linear-gradient(135deg,#1CA0D4,#49C4E5);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;line-height:1">02</span><p class="bl">Digital capabilities</p></div><div style="display:flex;flex-direction:column;gap:16px;flex:1;justify-content:center"><div class="fc"><div class="fi"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#1CA0D4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg></div><div><p style="font-size:20px;font-weight:700;margin-bottom:6px">Instant Payments</p><p style="font-size:17px;color:rgba(255,255,255,.75);line-height:1.5">Real-time transfers across borders with zero hidden fees and full transparency.</p></div></div><div class="fc"><div class="fi"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#1CA0D4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg></div><div><p style="font-size:20px;font-weight:700;margin-bottom:6px">AI-Powered Security</p><p style="font-size:17px;color:rgba(255,255,255,.75);line-height:1.5">Fraud detection that learns in real time, protecting every customer interaction.</p></div></div><div class="fc"><div class="fi"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#1CA0D4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg></div><div><p style="font-size:20px;font-weight:700;margin-bottom:6px">Smart Analytics</p><p style="font-size:17px;color:rgba(255,255,255,.75);line-height:1.5">Personalized financial insights that help customers make better decisions daily.</p></div></div></div></div><div class="ft"><span class="hn">@handle</span><span class="url">bbva.com</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div class="ab"></div><div class="gl" style="top:-60px;right:-60px;width:600px;height:600px;background:radial-gradient(ellipse,rgba(28,160,212,.10) 0%,transparent 60%)"></div><div class="gl" style="bottom:-100px;left:-80px;width:500px;height:500px;background:radial-gradient(ellipse,rgba(73,196,229,.08) 0%,transparent 60%)"></div><div class="inn" style="justify-content:center;align-items:center;text-align:center;gap:48px"><div><p class="bl" style="margin-bottom:28px;text-align:center">Join the movement</p><h2 style="font-size:80px;font-weight:800;line-height:1.1;letter-spacing:-.04em;margin-bottom:28px">Join the BBVA<br><em class="acc" style="font-size:80px">ecosystem.</em></h2><p style="font-size:22px;color:rgba(255,255,255,.75);line-height:1.55;max-width:700px;margin:0 auto">Open your account today and access the full suite of digital banking tools built for the modern world.</p></div><div class="cb" style="width:600px"><p style="font-family:\'Geist Mono\',monospace;font-size:22px;font-weight:500;color:#1CA0D4;letter-spacing:.04em">bbva.com / open-account</p></div></div><div class="ft"><span class="hn">@handle</span><span class="url">bbva.com</span></div></div>',
      },
    ],
  },

  // ── Minimal Carousel ─────────────────────────────────────────────────────
  {
    id: "minimal-carousel",
    name: "Minimal Carousel",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Clean alternating layout — photo splits, teal quote cards, stat cards",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#e8ecf0;font-family:'Outfit',sans-serif;color:#0f172a}",
      ".c{width:100%;height:100%;overflow:hidden;display:flex;flex-direction:column;position:relative}",
      ".bar{flex-shrink:0;height:76px;display:flex;align-items:center;padding:0 56px;gap:16px}",
      ".bar-t{background:rgba(0,0,0,0.10);border-top:1px solid rgba(255,255,255,0.20)}",
      ".bar-w{background:rgba(244,246,248,0.70);border-top:1px solid rgba(20,184,166,0.12)}",
      ".hn{font-family:'Geist Mono',monospace;font-size:20px;font-weight:400;color:#64748b;line-height:1}",
      ".hn-w{color:rgba(255,255,255,0.75)}",
      ".sp{flex:1}",
      ".cb{flex:1;padding:64px 64px 48px 80px;display:flex;flex-direction:column;justify-content:space-between}",
      ".ca{position:absolute;top:0;left:0;width:4px;height:100%;background:#14b8a6}",
      ".cn{font-family:'Geist Mono',monospace;font-size:22px;font-weight:400;color:#14b8a6;letter-spacing:.04em}",
      ".ch{font-family:'Outfit',sans-serif;font-size:112px;font-weight:900;line-height:1.0;letter-spacing:-.04em;color:#0f172a;text-transform:uppercase}",
      ".csw{font-family:'Geist Mono',monospace;font-size:18px;font-weight:400;color:#64748b;letter-spacing:.05em}",
      ".sw{flex:1;display:flex;min-height:0}",
      ".ic{flex-shrink:0;width:45%;position:relative;background:#f4f6f8}",
      ".ic-in{position:absolute;inset:32px;border:2px dashed #cbd5e1;border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px}",
      ".ic-ico{font-size:48px;color:#94a3b8;line-height:1}",
      ".ic-lbl{font-family:'Geist Mono',monospace;font-size:16px;color:#94a3b8;letter-spacing:.06em;text-transform:uppercase}",
      ".cc{flex:1;display:flex;flex-direction:column;justify-content:center;padding:56px 56px 40px 52px;gap:20px}",
      ".ccr{flex:1;display:flex;flex-direction:column;justify-content:center;padding:56px 52px 40px 56px;gap:20px}",
      ".sn{font-family:'Geist Mono',monospace;font-size:20px;color:#14b8a6;letter-spacing:.04em}",
      ".sh{font-family:'Outfit',sans-serif;font-size:56px;font-weight:800;line-height:1.1;letter-spacing:-.03em;color:#0f172a}",
      ".sb{font-size:20px;font-weight:400;color:#64748b;line-height:1.6}",
      ".qb{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:72px 96px 32px;text-align:center}",
      ".qm{font-family:'Outfit',sans-serif;font-size:180px;font-weight:900;line-height:.75;color:rgba(255,255,255,0.25);margin-bottom:24px}",
      ".qt{font-family:'Outfit',sans-serif;font-size:38px;font-weight:700;font-style:italic;line-height:1.35;color:#ffffff;max-width:800px}",
      ".qc{font-family:'Geist Mono',monospace;font-size:18px;color:rgba(255,255,255,0.55);letter-spacing:.06em}",
      ".stb{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:64px 80px 32px;text-align:center;gap:16px}",
      ".stn{font-family:'Outfit',sans-serif;font-size:160px;font-weight:900;line-height:1.0;letter-spacing:-.04em;color:#14b8a6}",
      ".stl{font-family:'Outfit',sans-serif;font-size:32px;font-weight:700;line-height:1.2;color:#0f172a}",
      ".std{font-size:22px;font-weight:400;color:#64748b;line-height:1.55;max-width:680px}",
      ".stc{font-family:'Geist Mono',monospace;font-size:18px;color:#64748b;letter-spacing:.06em}",
      ".ctab{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:72px 80px 32px;text-align:center;gap:20px}",
      ".ctah{font-family:'Outfit',sans-serif;font-size:90px;font-weight:900;line-height:1.0;letter-spacing:-.04em;color:#ffffff;text-transform:uppercase}",
      ".ctas{font-size:24px;font-weight:400;color:rgba(255,255,255,0.70);line-height:1.5}",
      ".ctaf{font-family:'Geist Mono',monospace;font-size:20px;color:rgba(255,255,255,0.75);letter-spacing:.06em;text-transform:uppercase}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c" style="background:#f4f6f8"><div class="ca"></div><div class="cb"><div style="display:flex;justify-content:flex-end"><span class="cn">01</span></div><h1 class="ch">YOUR<br>CONTENT<br><span style="color:#14b8a6">FINALLY</span><br>WORKS</h1><div style="display:flex;align-items:center;justify-content:space-between"><span class="hn">@handle</span><span class="csw">SWIPE →</span></div></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c" style="background:#ffffff"><div class="sw"><div class="ic"><div class="ic-in"><div class="ic-ico">📷</div><span class="ic-lbl">Photo / Video</span></div></div><div class="cc"><span class="sn">02</span><h2 class="sh">The story<br>starts here.</h2><p class="sb">Drop your photo or video on the left. This text block sits opposite — clean, readable, on brand.</p></div></div><div class="bar bar-w"><span class="hn">@handle</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "03",
        html: '<div class="c" style="background:#14b8a6"><div class="qb"><div class="qm">&ldquo;</div><p class="qt">The best content is the kind that makes someone stop scrolling and actually think.</p></div><div class="bar bar-t" style="justify-content:space-between"><span class="hn hn-w">@handle</span><span class="qc">03 / 06</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "04",
        html: '<div class="c" style="background:#ffffff"><div class="sw"><div class="ccr"><span class="sn">04</span><h2 class="sh">Flip the<br>layout here.</h2><p class="sb">Alternating sides keeps the carousel moving. Your audience stays curious card after card.</p></div><div class="ic"><div class="ic-in"><div class="ic-ico">📷</div><span class="ic-lbl">Photo / Video</span></div></div></div><div class="bar bar-w"><span class="hn">@handle</span></div></div>',
      },
      {
        dataType: "stat",
        dataIndex: "05",
        html: '<div class="c" style="background:#f4f6f8"><div class="stb"><div class="stn">10×</div><div class="stl">More productive</div><p class="std">Teams who batch their content creation ship 10x more posts with the same effort — without sacrificing quality.</p></div><div class="bar bar-w" style="justify-content:flex-end"><span class="stc">05 / 06</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "06",
        html: '<div class="c" style="background:#14b8a6"><div class="ctab"><h2 class="ctah">THANKS<br>FOR<br>READING!</h2><p class="ctas">Follow for more tips, templates, and tools.</p></div><div class="bar bar-t" style="justify-content:space-between"><span class="hn hn-w">@handle</span><span class="ctaf">FOLLOW →</span></div></div>',
      },
    ],
  },

  // ── Navy Waves ────────────────────────────────────────────────────────────
  {
    id: "navy-waves",
    name: "Navy Waves",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Deep navy alternating with clean white — corporate, education, finance",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#080d17;font-family:'Outfit',sans-serif;color:#fff}",
      ".c{width:100%;height:100%;overflow:hidden;display:flex;flex-direction:column;position:relative;background:#0f1729}",
      ".c.lgt{background:#ffffff;color:#0f1729}",
      ".body{flex:1;padding:64px 68px 32px;display:flex;flex-direction:column;position:relative;z-index:1}",
      ".bar{height:88px;flex-shrink:0;display:flex;align-items:center;justify-content:space-between;padding:0 68px;position:relative;z-index:2}",
      ".c .bar{border-top:1px solid rgba(255,255,255,.08);background:rgba(0,0,0,.18)}",
      ".c.lgt .bar{border-top:1px solid rgba(15,23,41,.1);background:rgba(248,250,252,.9)}",
      ".hn{font-family:'Geist Mono',monospace;font-size:20px;color:rgba(255,255,255,.55)}",
      ".lgt .hn{color:rgba(15,23,41,.45)}",
      ".ct{font-family:'Geist Mono',monospace;font-size:18px;font-weight:300;letter-spacing:.04em;color:rgba(255,255,255,.35)}",
      ".lgt .ct{color:rgba(15,23,41,.3)}",
      ".ml{font-family:'Geist Mono',monospace;font-size:18px;letter-spacing:.1em;text-transform:uppercase;color:#2563eb}",
      ".ar{width:80px;height:3px;background:linear-gradient(90deg,#2563eb,#60a5fa);border-radius:2px;margin-top:32px}",
      ".br{display:flex;align-items:flex-start;gap:20px;padding:22px 0;border-bottom:1px solid rgba(15,23,41,.08)}",
      ".br:last-child{border-bottom:none}",
      ".bsq{width:8px;height:8px;background:#2563eb;border-radius:1px;flex-shrink:0;margin-top:7px}",
      ".bt{font-size:22px;font-weight:700;color:#0f1729;line-height:1.3;margin-bottom:4px}",
      ".bb{font-size:18px;color:#94a3b8;line-height:1.5}",
      ".ip{width:400px;border:1.5px dashed #cbd5e1;border-radius:8px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;background:#f8fafc;flex-shrink:0}",
      ".ip-lbl{font-family:'Geist Mono',monospace;font-size:14px;color:#94a3b8;letter-spacing:.06em}",
      ".cp{display:inline-flex;align-items:center;gap:10px;background:#f1f5f9;border:1px solid #e2e8f0;border-radius:8px;padding:14px 22px;font-family:'Geist Mono',monospace;font-size:22px;color:#2563eb;margin-top:28px}",
      ".qm{font-size:160px;font-weight:900;color:#2563eb;line-height:1;text-align:center;margin-bottom:-20px}",
      ".qt{font-size:40px;font-weight:700;font-style:italic;color:#fff;line-height:1.3;text-align:center;max-width:780px;margin:0 auto}",
      ".qs{font-family:'Geist Mono',monospace;font-size:18px;color:#94a3b8;text-align:center;margin-top:28px;letter-spacing:.06em}",
      ".sr{display:flex;align-items:stretch;justify-content:center;margin-bottom:36px}",
      ".si{flex:1;display:flex;flex-direction:column;align-items:center;padding:0 32px;position:relative}",
      ".si+.si::before{content:'';position:absolute;left:0;top:10%;height:80%;width:1px;background:rgba(255,255,255,.12)}",
      ".sn{font-size:72px;font-weight:900;color:#2563eb;line-height:1.1;letter-spacing:-.04em}",
      ".sl{font-size:18px;color:#94a3b8;margin-top:8px;text-align:center}",
      ".cb{background:rgba(0,0,0,.4);border:1px solid rgba(37,99,235,.3);border-radius:10px;padding:22px 32px;font-family:'Geist Mono',monospace;font-size:24px;color:#60a5fa;display:flex;align-items:center;gap:16px;margin-top:32px}",
      ".cbp{color:rgba(255,255,255,.25)}",
      ".wd{position:absolute;bottom:0;right:0;pointer-events:none;opacity:.18;z-index:0}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><svg class="wd" width="380" height="380" viewBox="0 0 380 380"><polygon points="380,0 380,380 0,380" fill="#2563eb"/></svg><div class="body" style="justify-content:space-between"><div class="ml">codi · rules</div><div><h1 style="font-size:92px;font-weight:900;line-height:1.1;letter-spacing:-.04em;color:#fff">THE RULES<br>THAT MAKE<br>AI WORK.</h1><div class="ar"></div></div><div></div></div><div class="bar"><span class="hn">@handle</span><span class="ct">01 / 06</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c lgt"><div class="body"><div class="ml" style="margin-bottom:28px">02 · RULES</div><h2 style="font-size:72px;font-weight:900;line-height:1.1;letter-spacing:-.04em;color:#0f1729;margin-bottom:40px">Write once.<br>Sync everywhere.</h2><div style="flex:1;display:flex;flex-direction:column;justify-content:center"><div class="br"><div class="bsq"></div><div><div class="bt">One source of truth</div><div class="bb">Define rules in .codi/ — propagated to every AI tool automatically.</div></div></div><div class="br"><div class="bsq"></div><div><div class="bt">No manual syncing</div><div class="bb">Claude, Cursor, Copilot and Gemini stay aligned without extra work.</div></div></div><div class="br"><div class="bsq"></div><div><div class="bt">Version controlled</div><div class="bb">Rules live in your repo — reviewed, tested, and deployed with your code.</div></div></div></div></div><div class="bar"><span class="hn">@handle</span><span class="ct">02 / 06</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "03",
        html: '<div class="c"><svg class="wd" width="380" height="380" viewBox="0 0 380 380"><polygon points="380,0 380,380 0,380" fill="#2563eb"/></svg><div class="body" style="align-items:center;justify-content:center"><div class="qm">"</div><p class="qt">The teams shipping fastest are the ones whose AI tools follow the same rules as their engineers.</p><p class="qs">— Engineering lead, Series B startup</p></div><div class="bar"><span class="hn">@handle</span><span class="ct">03 / 06</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "04",
        html: '<div class="c lgt"><div class="body"><div class="ml" style="margin-bottom:28px">04 · AGENTS</div><div style="flex:1;display:flex;gap:40px;align-items:stretch"><div style="flex:1;display:flex;flex-direction:column;justify-content:space-between"><div><h2 style="font-size:64px;font-weight:900;line-height:1.1;letter-spacing:-.04em;color:#0f1729;margin-bottom:20px">Agents that know your standards.</h2><p style="font-size:20px;color:#94a3b8;line-height:1.6">Specialized agents ship pre-configured with domain expertise. Drop them into your project in seconds.</p></div><div class="cp"><span style="color:#94a3b8">$</span>codi init</div></div><div class="ip"><svg width="48" height="48" viewBox="0 0 48 48" fill="none"><rect x="4" y="10" width="40" height="28" rx="4" stroke="#cbd5e1" stroke-width="2"/><circle cx="24" cy="24" r="7" stroke="#cbd5e1" stroke-width="2"/><circle cx="24" cy="24" r="3" fill="#cbd5e1"/><circle cx="38" cy="15" r="2" fill="#cbd5e1"/></svg><span class="ip-lbl">IMAGE</span></div></div></div><div class="bar"><span class="hn">@handle</span><span class="ct">04 / 06</span></div></div>',
      },
      {
        dataType: "stat",
        dataIndex: "05",
        html: '<div class="c"><svg class="wd" width="380" height="380" viewBox="0 0 380 380"><polygon points="380,0 380,380 0,380" fill="#2563eb"/></svg><div class="body" style="align-items:center;justify-content:center"><div class="sr" style="width:100%"><div class="si"><div class="sn">5x</div><div class="sl">faster config<br>setup</div></div><div class="si"><div class="sn">10+</div><div class="sl">AI tools<br>supported</div></div><div class="si"><div class="sn">0</div><div class="sl">manual files<br>to maintain</div></div></div><p style="font-size:24px;color:#fff;text-align:center;max-width:720px;line-height:1.5;margin-top:16px">Teams using codi spend less time on config and more time shipping.</p></div><div class="bar"><span class="hn">@handle</span><span class="ct">05 / 06</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "06",
        html: '<div class="c"><svg class="wd" width="380" height="380" viewBox="0 0 380 380"><polygon points="380,0 380,380 0,380" fill="#2563eb"/></svg><div class="body" style="align-items:center;justify-content:center"><h2 style="font-size:110px;font-weight:900;line-height:1.05;letter-spacing:-.04em;color:#fff;text-align:center;text-transform:uppercase">START<br>TODAY.</h2><div class="cb"><span class="cbp">$</span>npm install -g codi-cli</div><p style="font-family:\'Geist Mono\',monospace;font-size:22px;color:#2563eb;margin-top:24px;letter-spacing:.04em">codi.tools</p></div><div class="bar"><span class="hn">@handle</span><span class="ct">06 / 06</span></div></div>',
      },
    ],
  },

  // ── Purple Split ──────────────────────────────────────────────────────────
  {
    id: "purple-split",
    name: "Purple Split",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "Deep purple base, alternating full-bleed and split-panel layouts with photo placeholders",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#0d0a1a;font-family:'Outfit',sans-serif;color:#fff}",
      ".c{width:100%;height:100%;overflow:hidden;display:flex;flex-direction:column;background:#1e1b4b;position:relative}",
      ".split{display:flex;flex-direction:row;flex:1;min-height:0}",
      ".ph{flex-shrink:0;width:540px;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;background:linear-gradient(160deg,#5b21b6,#1e1b4b)}",
      ".ph-lbl{font-family:'Geist Mono',monospace;font-size:14px;letter-spacing:.15em;text-transform:uppercase;color:rgba(255,255,255,.40)}",
      ".tc{flex:1;background:#fff;padding:60px 52px;display:flex;flex-direction:column;height:100%}",
      ".fbar{display:flex;align-items:center;justify-content:space-between;padding:0 60px;height:72px;border-top:1px solid rgba(255,255,255,.12);flex-shrink:0}",
      ".fbar-h{font-family:'Geist Mono',monospace;font-size:18px;color:rgba(255,255,255,.55)}",
      ".fbar-n{font-family:'Geist Mono',monospace;font-size:14px;color:rgba(167,139,250,.70)}",
      ".fbar-hd{font-family:'Geist Mono',monospace;font-size:15px;color:rgba(91,33,182,.55);margin-top:24px;flex-shrink:0}",
      ".snum{font-family:'Geist Mono',monospace;font-size:14px;color:#5b21b6;letter-spacing:.12em;margin-bottom:28px;flex-shrink:0}",
      ".sh{font-size:64px;font-weight:900;line-height:1.1;letter-spacing:-.03em;color:#1e1b4b;margin-bottom:24px;flex-shrink:0}",
      ".sb{font-size:20px;font-weight:400;line-height:1.55;color:#374151;flex:1}",
      ".blist{list-style:none;padding:0;margin:16px 0 0}",
      ".blist li{display:flex;align-items:center;gap:14px;font-size:20px;color:#374151;line-height:1.55;margin-bottom:14px}",
      ".blist li::before{content:'';display:inline-block;width:6px;height:6px;border-radius:50%;background:#5b21b6;flex-shrink:0}",
      ".cam-icon{stroke:rgba(255,255,255,.35);fill:none;stroke-width:1.1;stroke-linecap:round;stroke-linejoin:round}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c" style="background:#1e1b4b"><div style="position:absolute;top:52px;left:60px;width:30px;height:30px;border-radius:50%;background:rgba(91,33,182,.50)"></div><div style="flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:0 80px"><h1 style="font-family:\'Outfit\',sans-serif;font-size:94px;font-weight:900;line-height:1.05;letter-spacing:-.04em;color:#fff;margin-bottom:28px">ONE CODEBASE.<br>ALL YOUR AI<br>IN SYNC.</h1><p style="font-family:\'Outfit\',sans-serif;font-size:24px;font-weight:400;color:#a78bfa;line-height:1.5;max-width:700px">Rules, skills, and agents — one source of truth for every AI tool.</p></div><div class="fbar"><span class="fbar-h">@handle</span><span class="fbar-n">01 / 06</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c" style="flex-direction:column"><div class="split"><div class="ph" style="background:linear-gradient(160deg,#5b21b6,#1e1b4b)"><svg width="72" height="72" viewBox="0 0 24 24" class="cam-icon"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg><span class="ph-lbl">Image / Video</span></div><div class="tc"><div class="snum">02</div><div class="sh">Write rules.<br>Get results.</div><div class="sb">Define coding standards once in <code style="font-family:\'Geist Mono\',monospace;font-size:17px;background:#ede9fe;color:#5b21b6;padding:2px 6px;border-radius:4px">.codi/</code> and every AI tool follows them automatically.</div><div class="fbar-hd">@handle</div></div></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "03",
        html: '<div class="c" style="background:#5b21b6"><div style="position:absolute;top:0;left:0;right:0;bottom:72px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:80px"><div style="font-family:\'Outfit\',sans-serif;font-size:200px;font-weight:900;line-height:.8;color:rgba(255,255,255,.15);align-self:flex-start;padding-left:40px;margin-bottom:-40px">"</div><blockquote style="font-family:\'Outfit\',sans-serif;font-size:42px;font-weight:700;font-style:italic;line-height:1.3;color:#fff;max-width:820px;margin-bottom:36px">The best AI coding setup is the one every teammate uses the same way.</blockquote><p style="font-family:\'Geist Mono\',monospace;font-size:16px;color:rgba(255,255,255,.60);letter-spacing:.08em">— codi team · github.com/lehidalgo/codi</p></div><div class="fbar"><span class="fbar-h">@handle</span><span class="fbar-n">03 / 06</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "04",
        html: '<div class="c" style="flex-direction:column"><div class="split"><div class="tc"><div class="snum">04</div><div class="sh">One config.<br>Every tool.</div><div class="sb">codi syncs your standards across Claude, Cursor, Copilot, and more.<ul class="blist"><li>Rules propagate automatically</li><li>Skills follow your workflow</li><li>Agents stay consistent</li></ul></div><div class="fbar-hd">@handle</div></div><div class="ph" style="background:linear-gradient(160deg,#7c3aed,#5b21b6)"><svg width="72" height="72" viewBox="0 0 24 24" class="cam-icon"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg><span class="ph-lbl">Image / Video</span></div></div></div>',
      },
      {
        dataType: "stat",
        dataIndex: "05",
        html: '<div class="c" style="background:#2d1b69"><div style="flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:60px"><div style="display:flex;flex-direction:row;align-items:stretch;width:100%;max-width:900px;margin-bottom:52px"><div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:12px;padding:0 32px"><span style="font-family:\'Outfit\',sans-serif;font-size:80px;font-weight:900;line-height:1;color:#fff">5+</span><span style="font-family:\'Geist Mono\',monospace;font-size:18px;color:#a78bfa;letter-spacing:.06em;text-align:center">AI tools synced</span></div><div style="width:1px;background:rgba(167,139,250,.25);flex-shrink:0;margin:12px 0"></div><div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:12px;padding:0 32px"><span style="font-family:\'Outfit\',sans-serif;font-size:80px;font-weight:900;line-height:1;color:#fff">1</span><span style="font-family:\'Geist Mono\',monospace;font-size:18px;color:#a78bfa;letter-spacing:.06em;text-align:center">source of truth</span></div><div style="width:1px;background:rgba(167,139,250,.25);flex-shrink:0;margin:12px 0"></div><div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:12px;padding:0 32px"><span style="font-family:\'Outfit\',sans-serif;font-size:80px;font-weight:900;line-height:1;color:#fff">30s</span><span style="font-family:\'Geist Mono\',monospace;font-size:18px;color:#a78bfa;letter-spacing:.06em;text-align:center">to get started</span></div></div><p style="font-family:\'Outfit\',sans-serif;font-size:24px;font-weight:400;line-height:1.55;color:rgba(255,255,255,.80);text-align:center;max-width:760px">Stop maintaining separate configs for every AI tool. Set it once, use it everywhere.</p></div><div class="fbar"><span class="fbar-h">@handle</span><span class="fbar-n">05 / 06</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "06",
        html: '<div class="c" style="background:#1e1b4b"><div style="flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:0 80px;gap:32px"><div style="width:80px;height:2px;background:#7c3aed;border-radius:2px"></div><h2 style="font-family:\'Outfit\',sans-serif;font-size:100px;font-weight:900;line-height:1.0;letter-spacing:-.04em;color:#fff">FOLLOW<br>FOR MORE.</h2><p style="font-family:\'Outfit\',sans-serif;font-size:22px;font-weight:400;color:rgba(255,255,255,.60);line-height:1.5">Content about AI, dev tools, and productivity.</p><div style="border:2px solid rgba(124,58,237,.60);padding:20px 48px;border-radius:8px"><span style="font-family:\'Geist Mono\',monospace;font-size:18px;color:#a78bfa;letter-spacing:.04em">github.com/lehidalgo/codi</span></div></div><div class="fbar"><span class="fbar-h">@handle</span><span class="fbar-n">06 / 06</span></div></div>',
      },
    ],
  },

  // ── RL3 Social ────────────────────────────────────────────────────────────
  {
    id: "rl3-social",
    name: "RL3 Social",
    type: "social",
    format: { w: 1080, h: 1080 },
    desc: "RL3 brand — near-black base, orange accent, heavy Outfit headlines, service rows",
    css: [
      "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}",
      "body{background:#07070a;font-family:'Outfit',sans-serif;color:#f0f0f5}",
      ".c{position:relative;width:100%;height:100%;background:#0c0c10;overflow:hidden;display:flex;flex-direction:column}",
      ".inn{flex:1;padding:52px 60px 44px;display:flex;flex-direction:column;position:relative}",
      ".ft{height:72px;border-top:1px solid rgba(255,255,255,.07);flex-shrink:0;display:flex;align-items:center;justify-content:space-between;padding:0 60px}",
      ".hn{font-family:'Geist Mono',monospace;font-size:18px;color:#6b6b7a}",
      ".url{font-family:'Geist Mono',monospace;font-size:16px;color:rgba(249,115,22,.50)}",
      "em.acc{font-style:italic;font-weight:900;padding-right:.12em;background:linear-gradient(135deg,#f97316,#fb923c);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}",
      ".ml{font-family:'Geist Mono',monospace;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:#6b6b7a}",
      ".sr{display:flex;align-items:flex-start;gap:0;padding:24px 0;border-bottom:1px solid rgba(255,255,255,.07)}",
      ".sr:last-child{border-bottom:none}",
      ".sa{width:3px;background:#f97316;border-radius:2px;flex-shrink:0;align-self:stretch;margin-right:24px}",
      ".cb{border:2px solid #f97316;border-radius:12px;padding:22px 44px;display:inline-flex;align-items:center;justify-content:center;background:rgba(249,115,22,.06)}",
      ".no{position:absolute;inset:0;pointer-events:none;opacity:.025;background-image:url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\");background-size:180px}",
      ".og{position:absolute;border-radius:50%;pointer-events:none}",
    ].join(""),
    slides: [
      {
        dataType: "cover",
        dataIndex: "01",
        html: '<div class="c"><div class="no"></div><div class="og" style="top:-100px;right:-80px;width:480px;height:480px;background:radial-gradient(ellipse,rgba(249,115,22,.10) 0%,transparent 65%)"></div><div class="inn" style="justify-content:space-between"><div><span class="ml">RL3</span></div><div><h1 style="font-size:100px;font-weight:900;line-height:1.1;letter-spacing:-.045em;margin-bottom:28px">AI that works<br><em class="acc">in production.</em></h1><p style="font-size:28px;font-weight:700;color:#a0a0af;line-height:1.3;letter-spacing:-.01em">We don\'t consult. We build.</p></div><div style="width:60px;height:2px;background:#f97316;border-radius:2px"></div></div><div class="ft"><span class="hn">@handle</span><span class="url">rl3.ai</span></div></div>',
      },
      {
        dataType: "content",
        dataIndex: "02",
        html: '<div class="c"><div class="no"></div><div class="og" style="bottom:-120px;left:-80px;width:420px;height:420px;background:radial-gradient(ellipse,rgba(249,115,22,.08) 0%,transparent 65%)"></div><div class="inn" style="justify-content:space-between"><div><p class="ml" style="margin-bottom:16px">01 · WHAT WE DO</p><h2 style="font-size:72px;font-weight:900;line-height:1.1;letter-spacing:-.04em">From strategy<br>to shipped.</h2></div><div style="display:flex;flex-direction:column;flex:1;justify-content:center;padding:32px 0"><div class="sr"><div class="sa"></div><div><p style="font-size:22px;font-weight:800;color:#f0f0f5;margin-bottom:6px;letter-spacing:-.01em">AI Architecture</p><p style="font-size:18px;color:#a0a0af;line-height:1.5">We design the system end-to-end. Models, pipelines, infra, evals — all connected.</p></div></div><div class="sr"><div class="sa"></div><div><p style="font-size:22px;font-weight:800;color:#f0f0f5;margin-bottom:6px;letter-spacing:-.01em">Product Engineering</p><p style="font-size:18px;color:#a0a0af;line-height:1.5">Full-stack teams that ship AI features in weeks, not quarters.</p></div></div><div class="sr"><div class="sa"></div><div><p style="font-size:22px;font-weight:800;color:#f0f0f5;margin-bottom:6px;letter-spacing:-.01em">Embedded AI Teams</p><p style="font-size:18px;color:#a0a0af;line-height:1.5">We join your team, own the AI layer, and deliver measurable output.</p></div></div></div></div><div class="ft"><span class="hn">@handle</span><span class="url">rl3.ai</span></div></div>',
      },
      {
        dataType: "cta",
        dataIndex: "03",
        html: '<div class="c"><div class="no"></div><div class="og" style="top:-80px;right:-60px;width:520px;height:520px;background:radial-gradient(ellipse,rgba(249,115,22,.09) 0%,transparent 60%)"></div><div class="og" style="bottom:-80px;left:-60px;width:380px;height:380px;background:radial-gradient(ellipse,rgba(251,146,60,.07) 0%,transparent 60%)"></div><div class="inn" style="justify-content:space-between"><div><span class="ml">Ready?</span></div><div style="display:flex;flex-direction:column;gap:28px"><h2 style="font-size:100px;font-weight:900;line-height:1.05;letter-spacing:-.045em">Ready to<br>move fast?</h2><p style="font-size:24px;color:#a0a0af;line-height:1.55;max-width:780px">Book a discovery call. Get an implementation plan in 48 hours.</p></div><div><div class="cb"><span style="font-family:\'Outfit\',sans-serif;font-size:26px;font-weight:800;color:#f97316;letter-spacing:-.01em">Book a Call →</span></div></div></div><div class="ft"><span class="hn">@handle</span><span class="url">rl3.ai</span></div></div>',
      },
    ],
  },
];
