/**
 * Brain-side hook scripts for Codi Brain Week 2B.
 *
 * SessionStart — flushes `.codi/brain-outbox/` and injects /hot + recent
 *                decisions into the agent context as `additionalContext`.
 * Stop         — parses CODI-* markers (L1) and, if opt-in via
 *                `.codi/config.yaml` `brain.auto_extract: true`, redacts the
 *                transcript + calls Gemini (L3) with evidence-quote
 *                verification + dedup against L1.
 * PostCommit   — on PostToolUse for `git commit`, POSTs /vault/reconcile.
 *
 * Written to `.codi/hooks/` by `codi generate`; wired into
 * `.claude/settings.json` by `src/adapters/claude-code.ts`.
 *
 * NOTE: REDACTION_PATTERNS below MUST be kept in sync with
 *       src/brain-client/redactor-patterns.ts (tested in
 *       tests/unit/core/hooks/brain-hooks.test.ts via the stop script).
 */

import { PROJECT_NAME } from "#src/constants.js";

export const BRAIN_SESSION_START_FILENAME = `${PROJECT_NAME}-brain-session-start.cjs`;
export const BRAIN_STOP_FILENAME = `${PROJECT_NAME}-brain-stop.cjs`;
export const BRAIN_POST_COMMIT_FILENAME = `${PROJECT_NAME}-brain-post-commit.cjs`;

/** Inlined redaction patterns — mirrored from redactor-patterns.ts. */
const INLINE_REDACTION_PATTERNS = [
  {
    name: "anthropic_key",
    source: "sk-ant-[A-Za-z0-9_-]{32,}",
    flags: "g",
    replacement: "[REDACTED:anthropic_key]",
  },
  {
    name: "openai_key",
    source: "sk-[A-Za-z0-9_-]{32,}",
    flags: "g",
    replacement: "[REDACTED:openai_key]",
  },
  {
    name: "google_key",
    source: "AIza[A-Za-z0-9_-]{35}",
    flags: "g",
    replacement: "[REDACTED:google_key]",
  },
  {
    name: "github_pat",
    source: "gh[opusr]_[A-Za-z0-9]{36,}",
    flags: "g",
    replacement: "[REDACTED:github_pat]",
  },
  {
    name: "slack_token",
    source: "xox[abprs]-[A-Za-z0-9-]{10,}",
    flags: "g",
    replacement: "[REDACTED:slack_token]",
  },
  {
    name: "aws_access_key",
    source: "\\bAKIA[0-9A-Z]{16}\\b",
    flags: "g",
    replacement: "[REDACTED:aws_access_key]",
  },
  {
    name: "jwt",
    source: "eyJ[A-Za-z0-9_-]{10,}\\.eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}",
    flags: "g",
    replacement: "[REDACTED:jwt]",
  },
  {
    name: "bearer_token_header",
    source: "[Aa]uthorization:\\s*[Bb]earer\\s+[A-Za-z0-9._-]+",
    flags: "g",
    replacement: "Authorization: Bearer [REDACTED]",
  },
  {
    name: "url_password",
    source: "://[^\\s:/@]+:[^@\\s]+@",
    flags: "g",
    replacement: "://[REDACTED]@",
  },
  {
    name: "email",
    source: "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}",
    flags: "g",
    replacement: "[REDACTED:email]",
  },
];

export function buildBrainSessionStartScript(): string {
  return `#!/usr/bin/env node
// Codi Brain — SessionStart hook (async)
// Flushes outbox + injects /hot + recent decisions into agent context.
// Do not edit — regenerated by: codi generate

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const OUTBOX_DIR = path.join(PROJECT_ROOT, '.codi', 'brain-outbox');

function log(msg) { try { console.error('[codi-brain] ' + msg); } catch {} }

function readCfg() {
  let url = process.env.BRAIN_URL || 'http://127.0.0.1:8000';
  let token = process.env.BRAIN_BEARER_TOKEN || null;
  try {
    const p = path.join(PROJECT_ROOT, '.codi', 'config.yaml');
    if (fs.existsSync(p)) {
      const YAML = require(path.join(PROJECT_ROOT, 'node_modules', 'yaml'));
      const cfg = YAML.parse(fs.readFileSync(p, 'utf-8')) || {};
      if (cfg.brain) {
        if (!process.env.BRAIN_URL && cfg.brain.url) url = cfg.brain.url;
        if (!process.env.BRAIN_BEARER_TOKEN && cfg.brain.bearer_token) token = cfg.brain.bearer_token;
      }
    }
  } catch (e) { log('config parse error: ' + e.message); }
  return { url, token };
}

async function fetchJson(url, token, method, pathPart, body) {
  const res = await fetch(url + pathPart, {
    method,
    headers: {
      'Accept': 'application/json',
      ...(token && { 'Authorization': 'Bearer ' + token }),
      ...(body && { 'Content-Type': 'application/json' }),
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(5000),
  });
  if (!res.ok) throw new Error('HTTP ' + res.status);
  return res.json();
}

async function flushOutbox(cfg) {
  if (!fs.existsSync(OUTBOX_DIR)) return 0;
  const files = fs.readdirSync(OUTBOX_DIR).filter(f => f.endsWith('.json'));
  let drained = 0;
  for (const f of files) {
    const full = path.join(OUTBOX_DIR, f);
    try {
      const entry = JSON.parse(fs.readFileSync(full, 'utf-8'));
      await fetchJson(cfg.url, cfg.token, entry.method, entry.path, entry.body);
      fs.unlinkSync(full);
      drained++;
    } catch (e) { log('outbox flush failed for ' + f + ': ' + e.message); }
  }
  return drained;
}

async function main() {
  const cfg = readCfg();
  if (!cfg.token) {
    console.log(JSON.stringify({ additionalContext: '' }));
    return;
  }

  const contextLines = [];
  try {
    const drained = await flushOutbox(cfg);
    if (drained > 0) contextLines.push('(Codi Brain: flushed ' + drained + ' queued writes.)');
  } catch (e) { log('outbox skip: ' + e.message); }

  try {
    const hot = await fetchJson(cfg.url, cfg.token, 'GET', '/hot');
    if (hot && hot.body) {
      contextLines.push('Hot state: ' + hot.body);
    }
  } catch (e) { log('hot fetch skip: ' + e.message); }

  try {
    const recent = await fetchJson(cfg.url, cfg.token, 'GET', '/notes/search?kind=decision&recent_days=7&limit=10');
    if (recent && Array.isArray(recent.results) && recent.results.length > 0) {
      contextLines.push('Recent decisions (last 7 days):');
      for (const n of recent.results) {
        const date = (n.created_at || '').slice(0, 10);
        const excerpt = n.body ? ' — ' + String(n.body).slice(0, 80) : '';
        contextLines.push('- [' + date + '] ' + n.title + excerpt);
      }
    }
  } catch (e) { log('recall skip: ' + e.message); }

  const additionalContext = contextLines.length
    ? '<codi-brain-context>\\n' + contextLines.join('\\n') + '\\n</codi-brain-context>'
    : '';
  console.log(JSON.stringify({ additionalContext }));
}

main().catch(e => { log('fatal: ' + e.message); console.log(JSON.stringify({ additionalContext: '' })); });
`;
}

export function buildBrainStopScript(): string {
  const patternsJson = JSON.stringify(INLINE_REDACTION_PATTERNS);
  return `#!/usr/bin/env node
// Codi Brain — Stop hook (synchronous)
// 1. Parse CODI-DECISION/HOT/NOTE markers from transcript, POST each. (L1)
// 2. If auto_extract is enabled, redact + Gemini-extract + dedup + POST survivors. (L3)
// Do not edit — regenerated by: codi generate

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const OUTBOX_DIR = path.join(PROJECT_ROOT, '.codi', 'brain-outbox');
const LOG_DIR = path.join(PROJECT_ROOT, '.codi', 'brain-logs');
const PENDING_DIR = path.join(PROJECT_ROOT, '.codi', 'pending-notes');

function log(msg) { try { console.error('[codi-brain-stop] ' + msg); } catch {} }
function ensureDir(d) { try { fs.mkdirSync(d, { recursive: true }); } catch {} }

function readCfg() {
  let url = process.env.BRAIN_URL || 'http://127.0.0.1:8000';
  let token = process.env.BRAIN_BEARER_TOKEN || null;
  let autoExtract = process.env.BRAIN_AUTO_EXTRACT === 'true';
  let threshold = 0.8;
  let model = 'gemini-2.5-flash';
  let geminiKey = process.env.GEMINI_API_KEY || null;
  try {
    const p = path.join(PROJECT_ROOT, '.codi', 'config.yaml');
    if (fs.existsSync(p)) {
      const YAML = require(path.join(PROJECT_ROOT, 'node_modules', 'yaml'));
      const c = YAML.parse(fs.readFileSync(p, 'utf-8')) || {};
      if (c.brain) {
        if (!process.env.BRAIN_URL && c.brain.url) url = c.brain.url;
        if (!process.env.BRAIN_BEARER_TOKEN && c.brain.bearer_token) token = c.brain.bearer_token;
        if (process.env.BRAIN_AUTO_EXTRACT === undefined && c.brain.auto_extract === true) autoExtract = true;
        if (c.brain.auto_extract_confidence_threshold) threshold = c.brain.auto_extract_confidence_threshold;
        if (c.brain.auto_extract_model) model = c.brain.auto_extract_model;
        if (!geminiKey && c.brain.gemini_api_key) geminiKey = c.brain.gemini_api_key;
      }
    }
  } catch (e) {
    log('config parse error (fail-closed on extraction): ' + e.message);
    autoExtract = false;
  }
  return { url, token, autoExtract, threshold, model, geminiKey };
}

async function postNote(cfg, body) {
  try {
    const res = await fetch(cfg.url + '/notes', {
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + cfg.token, 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) throw new Error('HTTP ' + res.status);
    return await res.json();
  } catch (e) {
    ensureDir(OUTBOX_DIR);
    const f = path.join(OUTBOX_DIR, Date.now() + '_' + (body.session_id || 'unknown') + '.json');
    fs.writeFileSync(f, JSON.stringify({ method: 'POST', path: '/notes', body, sessionId: body.session_id || 'unknown' }));
    throw e;
  }
}

async function putHot(cfg, body) {
  try {
    const res = await fetch(cfg.url + '/hot', {
      method: 'PUT',
      headers: { 'Authorization': 'Bearer ' + cfg.token, 'Content-Type': 'application/json' },
      body: JSON.stringify({ body }),
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) throw new Error('HTTP ' + res.status);
    return await res.json();
  } catch (e) {
    ensureDir(OUTBOX_DIR);
    const f = path.join(OUTBOX_DIR, Date.now() + '_hot.json');
    fs.writeFileSync(f, JSON.stringify({ method: 'PUT', path: '/hot', body: { body }, sessionId: 'hot' }));
    throw e;
  }
}

function parseMarkers(transcript) {
  const re = /<CODI-(DECISION|HOT|NOTE)@v1>\\s*([\\s\\S]+?)\\s*<\\/CODI-\\1@v1>/g;
  const markers = [];
  for (const m of transcript.matchAll(re)) {
    try { markers.push({ type: m[1], payload: JSON.parse(m[2]) }); }
    catch (e) { log('malformed marker: ' + e.message); }
  }
  return markers;
}

function readTranscriptFromInput(data) {
  if (typeof data?.transcript === 'string') return data.transcript;
  if (Array.isArray(data?.messages)) {
    return data.messages
      .map(m => (typeof m.content === 'string' ? m.content : JSON.stringify(m.content)))
      .join('\\n');
  }
  return '';
}

const REDACTION_PATTERNS = ${patternsJson};

function redact(text, homeDir) {
  const counts = {};
  let out = text;
  if (homeDir) {
    const escaped = homeDir.replace(/[.*+?^$\\{\\}()|[\\]\\\\]/g, '\\\\$&');
    const hr = new RegExp(escaped + '[^\\\\s"\\']*', 'g');
    const hm = out.match(hr);
    if (hm) { counts.home_path = hm.length; out = out.replace(hr, '[REDACTED:home_path]'); }
  }
  for (const p of REDACTION_PATTERNS) {
    const re = new RegExp(p.source, p.flags);
    const m = out.match(re);
    if (m) { counts[p.name] = m.length; out = out.replace(re, p.replacement); }
  }
  return { redacted: out, counts };
}

async function extract(cfg, redactedTranscript) {
  try {
    // Gemini package require is INSIDE the L3 branch — a user without
    // @google/generative-ai installed still runs L1 successfully.
    const { GoogleGenerativeAI } = require(path.join(PROJECT_ROOT, 'node_modules', '@google', 'generative-ai'));
    const ai = new GoogleGenerativeAI(cfg.geminiKey);
    const m = ai.getGenerativeModel({ model: cfg.model, generationConfig: { responseMimeType: 'application/json' } });
    const prompt = 'Extract durable decisions from the transcript. Return JSON: {"candidates":[{"title":"...","body":"...","tags":["..."],"evidence_quote":"...","confidence":0.0,"type":"decision"}]}\\n\\n---TRANSCRIPT---\\n' + redactedTranscript + '\\n---END---';
    const res = await m.generateContent(prompt);
    const raw = res.response.text();
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed.candidates)) return [];
    const tnorm = redactedTranscript.toLowerCase().replace(/\\s+/g, ' ');
    return parsed.candidates.map(c => {
      const qnorm = (c.evidence_quote || '').toLowerCase().replace(/\\s+/g, ' ');
      const ok = qnorm && tnorm.includes(qnorm);
      return Object.assign({}, c, { confidence: ok ? Math.max(0, Math.min(1, c.confidence || 0)) : 0 });
    });
  } catch (e) { log('extraction failed: ' + e.message); return []; }
}

async function main() {
  let input = '';
  process.stdin.setEncoding('utf-8');
  for await (const chunk of process.stdin) input += chunk;

  let data;
  try { data = JSON.parse(input); } catch { data = {}; }
  const sessionId = data.session_id || 'unknown';
  const transcript = readTranscriptFromInput(data);

  const cfg = readCfg();
  if (!cfg.token) { log('no token, skipping'); return; }

  // L1 — markers
  const markers = parseMarkers(transcript);
  const markerTitles = new Set();
  for (const mk of markers) {
    try {
      if (mk.type === 'HOT') {
        await putHot(cfg, mk.payload.body || '');
      } else {
        await postNote(cfg, {
          kind: 'decision',
          title: mk.payload.title || '',
          body: mk.payload.body || mk.payload.reason || '',
          tags: mk.payload.tags || [],
          links: [],
          session_id: sessionId,
        });
        markerTitles.add((mk.payload.title || '').toLowerCase().trim().replace(/\\s+/g, ' '));
      }
    } catch (e) { log('L1 post failed: ' + e.message); }
  }

  // L3 — opt-in extraction (gated on auto_extract + GEMINI_API_KEY)
  if (cfg.autoExtract && cfg.geminiKey && transcript.length > 0) {
    ensureDir(LOG_DIR);
    const { redacted, counts } = redact(transcript, process.env.HOME || '');
    fs.appendFileSync(
      path.join(LOG_DIR, 'redaction-' + sessionId + '.jsonl'),
      JSON.stringify({ ts: new Date().toISOString(), counts }) + '\\n'
    );
    const candidates = await extract(cfg, redacted);
    const surviving = candidates.filter(c => {
      const norm = (c.title || '').toLowerCase().trim().replace(/\\s+/g, ' ');
      return !markerTitles.has(norm);
    });
    for (const c of surviving) {
      if (c.confidence >= cfg.threshold) {
        try {
          await postNote(cfg, {
            kind: 'decision',
            title: c.title,
            body: c.body || '',
            tags: (c.tags || []).concat(['auto-extracted', 'auto-extract-' + sessionId]),
            links: [],
            session_id: sessionId,
          });
        } catch (e) { log('L3 post failed: ' + e.message); }
      } else if (c.confidence >= 0.5) {
        ensureDir(PENDING_DIR);
        fs.appendFileSync(path.join(PENDING_DIR, sessionId + '.jsonl'), JSON.stringify(c) + '\\n');
      } else {
        ensureDir(LOG_DIR);
        fs.appendFileSync(path.join(LOG_DIR, 'low-confidence-' + sessionId + '.jsonl'), JSON.stringify(c) + '\\n');
      }
    }
  }
}

main().catch(e => { log('fatal: ' + e.message); process.exit(0); });
`;
}

export function buildBrainPostCommitScript(): string {
  return `#!/usr/bin/env node
// Codi Brain — PostToolUse hook for git commit
// Fires /vault/reconcile after a successful commit.
// Do not edit — regenerated by: codi generate

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..', '..');

function log(msg) { try { console.error('[codi-brain-post-commit] ' + msg); } catch {} }

async function main() {
  let input = '';
  process.stdin.setEncoding('utf-8');
  for await (const chunk of process.stdin) input += chunk;

  let data;
  try { data = JSON.parse(input); } catch { return; }

  const tool = data.tool_name || data.tool || '';
  const cmd = (data && data.tool_input && data.tool_input.command) || data.command || '';
  if (tool !== 'Bash' && tool !== 'bash') return;
  if (!/^\\s*git\\s+commit/.test(cmd)) return;

  let url = process.env.BRAIN_URL || 'http://127.0.0.1:8000';
  let token = process.env.BRAIN_BEARER_TOKEN || null;
  try {
    const p = path.join(PROJECT_ROOT, '.codi', 'config.yaml');
    if (fs.existsSync(p)) {
      const YAML = require(path.join(PROJECT_ROOT, 'node_modules', 'yaml'));
      const c = YAML.parse(fs.readFileSync(p, 'utf-8')) || {};
      if (c.brain) {
        if (!process.env.BRAIN_URL && c.brain.url) url = c.brain.url;
        if (!process.env.BRAIN_BEARER_TOKEN && c.brain.bearer_token) token = c.brain.bearer_token;
      }
    }
  } catch {}

  if (!token) return;

  try {
    await fetch(url + '/vault/reconcile', {
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
      signal: AbortSignal.timeout(5000),
    });
  } catch (e) { log('reconcile skip: ' + e.message); }
}

main().catch(e => { log('fatal: ' + e.message); });
`;
}
