/**
 * Mini-installer for codi's git-native `core.hooksPath` approach.
 *
 * ADR-013 Paso 9. Replaces the runner-branching `installHooks()` flow
 * with a single git-native path:
 *
 *   1. `git config core.hooksPath .githooks/`
 *   2. Write 3 stub scripts (`.githooks/pre-commit`, `commit-msg`,
 *      `pre-push`) that exec the corresponding `codi hook git-<event>`
 *      dispatcher.
 *   3. `chmod +x` the stubs.
 *
 * The actual check logic lives in `src/runtime/hooks/git/` modules
 * invoked by the dispatcher — this installer only sets up the
 * delegation surface.
 *
 * **Coexistence policy**: if the project already has a hook runner
 * configured (Husky / Lefthook / pre-commit-framework), this installer
 * does NOT touch `core.hooksPath` or write `.githooks/`. The codi
 * UserPromptSubmit hook (`hook-conflict-detection.ts`) then nudges
 * the agent to invoke the `${PROJECT_NAME}-dev-migrate-hooks` skill,
 * which migrates safely.
 *
 * Caller is `src/cli/init-helpers.ts` (or any handler that wants to
 * apply codi's hook integration). The installer is idempotent: re-
 * running on an already-migrated project is a no-op.
 */

import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { ok, err } from "#src/types/result.js";
import type { Result } from "#src/types/result.js";
import { createError } from "../output/errors.js";
import { PROJECT_NAME } from "#src/constants.js";

export interface CoreHooksPathInstallResult {
  /** Paths of files written (relative to projectRoot). */
  files: string[];
  /** True when the installer skipped because of a conflicting runner. */
  skipped: boolean;
  /** Human-readable reason when `skipped === true`. */
  skipReason?: string;
}

const HOOKS_DIR = ".githooks";
const STUB_SCRIPTS: ReadonlyArray<{ kind: string; dispatcher: string }> = [
  { kind: "pre-commit", dispatcher: "git-pre-commit" },
  { kind: "commit-msg", dispatcher: "git-commit-msg" },
  { kind: "pre-push", dispatcher: "git-pre-push" },
];

function stubContent(dispatcherName: string): string {
  return `#!/bin/sh
# Generated by codi (ADR-013 Paso 9). Delegates to the codi binary on PATH.
# Do not edit — re-run \`codi init\` to refresh.
exec ${PROJECT_NAME} hook ${dispatcherName} "$@"
`;
}

function detectRunner(projectRoot: string): string | null {
  if (existsSync(path.join(projectRoot, ".husky"))) return "Husky";
  if (
    existsSync(path.join(projectRoot, "lefthook.yml")) ||
    existsSync(path.join(projectRoot, "lefthook.yaml"))
  ) {
    return "Lefthook";
  }
  if (existsSync(path.join(projectRoot, ".pre-commit-config.yaml"))) {
    return "pre-commit-framework";
  }
  return null;
}

/**
 * Install codi's git-native hooks via `core.hooksPath`. Idempotent.
 */
export async function installCoreHooksPath(
  projectRoot: string,
): Promise<Result<CoreHooksPathInstallResult>> {
  // 1. Detect conflicting runner. If present, skip silently — the
  //    UserPromptSubmit conflict detector will nudge the agent to run
  //    the migration skill.
  const runner = detectRunner(projectRoot);
  if (runner !== null) {
    return ok({
      files: [],
      skipped: true,
      skipReason: `Detected ${runner} in the project. Deferring git-hook installation to the ${PROJECT_NAME}-dev-migrate-hooks skill (auto-prompt fires on next agent turn).`,
    });
  }

  // 2. Set core.hooksPath. This is the single source of truth — git
  //    natively reads from this path. No npm dep, no shell wrapper.
  try {
    execFileSync("git", ["config", "core.hooksPath", HOOKS_DIR], {
      cwd: projectRoot,
      stdio: ["ignore", "ignore", "pipe"],
    });
  } catch (cause) {
    return err([
      createError(
        "E_HOOK_FAILED",
        {
          hook: "core-hooks-path-installer",
          reason: `git config core.hooksPath ${HOOKS_DIR} failed (is this a git repo?)`,
        },
        cause instanceof Error ? cause : undefined,
      ),
    ]);
  }

  // 3. Write the 3 stub scripts.
  const written: string[] = [];
  const hooksDir = path.join(projectRoot, HOOKS_DIR);
  try {
    await fs.mkdir(hooksDir, { recursive: true });
    for (const { kind, dispatcher } of STUB_SCRIPTS) {
      const filePath = path.join(hooksDir, kind);
      await fs.writeFile(filePath, stubContent(dispatcher), {
        encoding: "utf-8",
        mode: 0o755,
      });
      written.push(path.relative(projectRoot, filePath));
    }
  } catch (cause) {
    return err([
      createError(
        "E_HOOK_FAILED",
        {
          hook: "core-hooks-path-installer",
          reason: `failed to write stub script under ${HOOKS_DIR}/`,
        },
        cause instanceof Error ? cause : undefined,
      ),
    ]);
  }

  return ok({ files: written, skipped: false });
}
