/**
 * Heartbeat hook scripts for codi's self-improvement feedback loop.
 *
 * skill-tracker  — InstructionsLoaded hook (async): records which codi skills are
 *                  active in the current session to .codi/.session/active-skills.json
 *
 * skill-observer — Stop hook (synchronous): scans the transcript for
 *                  [CODI-OBSERVATION: ...] markers and writes structured JSON to
 *                  .codi/feedback/. When 5+ observations accumulate, outputs an
 *                  additionalContext hint to prompt the user to run /codi-refine-rules.
 *
 * Both scripts are written to .codi/hooks/ during `codi generate`.
 * Claude Code wires them via .claude/settings.json; Codex via .codex/hooks.json.
 */

import { PROJECT_NAME, PROJECT_DIR, PROJECT_NAME_DISPLAY } from "#src/constants.js";

/** File name of the generated skill-tracker hook script. */
export const SKILL_TRACKER_FILENAME = `${PROJECT_NAME}-skill-tracker.cjs`;

/** File name of the generated skill-observer hook script. */
export const SKILL_OBSERVER_FILENAME = `${PROJECT_NAME}-skill-observer.cjs`;

/** Directory inside PROJECT_DIR where hook scripts are written. */
export const HOOKS_SUBDIR = "hooks";

/** Directory inside PROJECT_DIR where session state is stored. */
export const SESSION_SUBDIR = ".session";

/** File name of the active-skills session state file. */
export const ACTIVE_SKILLS_FILENAME = "active-skills.json";

/** Observation threshold above which the hint fires. */
export const OBSERVATION_HINT_THRESHOLD = 5;

/**
 * Build the skill-tracker script content.
 *
 * Fires on InstructionsLoaded — appends the skill name and timestamp to
 * .codi/.session/active-skills.json when a codi skill SKILL.md is loaded.
 */
export function buildSkillTrackerScript(): string {
  return `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} skill-tracker — InstructionsLoaded hook (async)
// Tracks which codi skills are active in the current session.
// Do not edit — regenerated by: ${PROJECT_NAME} generate

const fs = require('fs');
const path = require('path');
const readline = require('readline');

async function main() {
  let payload = '';
  const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
  for await (const line of rl) payload += line;

  let data;
  try { data = JSON.parse(payload); } catch { process.exit(0); }

  const filePath = data?.file_path ?? '';
  const sessionId = data?.session_id ?? 'unknown';

  // Only track codi skill SKILL.md files
  if (!filePath.includes('/.claude/skills/${PROJECT_NAME}-') || !filePath.endsWith('/SKILL.md')) {
    process.exit(0);
  }

  // Extract skill name: .claude/skills/codi-commit/SKILL.md -> codi-commit
  const parts = filePath.split('/');
  const skillsIdx = parts.lastIndexOf('skills');
  if (skillsIdx < 0 || skillsIdx + 1 >= parts.length) process.exit(0);
  const skillName = parts[skillsIdx + 1];
  if (!skillName) process.exit(0);

  const sessionFile = path.join(
    process.cwd(),
    '${PROJECT_DIR}',
    '${SESSION_SUBDIR}',
    '${ACTIVE_SKILLS_FILENAME}'
  );
  fs.mkdirSync(path.dirname(sessionFile), { recursive: true });

  let state = { session_id: sessionId, skills: [] };
  try { state = JSON.parse(fs.readFileSync(sessionFile, 'utf-8')); } catch {}
  if (!Array.isArray(state.skills)) state.skills = [];

  if (!state.skills.some(s => s.name === skillName)) {
    state.skills.push({ name: skillName, loaded_at: new Date().toISOString() });
    fs.writeFileSync(sessionFile, JSON.stringify(state, null, 2), 'utf-8');
  }
  process.exit(0);
}

main().catch(() => process.exit(0));
`;
}

/** Pattern text for CODI-OBSERVATION markers (used in generated script). */
const MARKER_PATTERN_TEXT =
  "\\\\[CODI-OBSERVATION:\\\\s*([^|\\\\]]+)\\\\|([^|\\\\]]+)\\\\|([^\\\\]]+)\\\\]";

/**
 * Build the skill-observer script content.
 *
 * Fires on Stop — scans the transcript for [CODI-OBSERVATION: ...] markers,
 * writes structured JSON to .codi/feedback/, and emits an additionalContext hint
 * when the feedback threshold is reached.
 */
export function buildSkillObserverScript(): string {
  return `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} skill-observer — Stop hook (synchronous)
// Extracts CODI-OBSERVATION markers from the transcript and writes feedback JSON.
// Do not edit — regenerated by: ${PROJECT_NAME} generate

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const crypto = require('crypto');

const OBSERVATION_RE = new RegExp('${MARKER_PATTERN_TEXT}', 'g');
const SEVERITY_MAP = { 'user-correction': 'high', 'trigger-miss': 'medium', 'trigger-false': 'medium' };
const HINT_THRESHOLD = ${OBSERVATION_HINT_THRESHOLD};

async function main() {
  let payload = '';
  const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
  for await (const line of rl) payload += line;

  const sessionFile = path.join(process.cwd(), '${PROJECT_DIR}', '${SESSION_SUBDIR}', '${ACTIVE_SKILLS_FILENAME}');
  const feedbackDir = path.join(process.cwd(), '${PROJECT_DIR}', 'feedback');

  // Step 1: exit immediately if this is not a codi session
  if (!fs.existsSync(sessionFile)) { console.log('{}'); process.exit(0); }

  let sessionId = 'unknown';
  try {
    const s = JSON.parse(fs.readFileSync(sessionFile, 'utf-8'));
    sessionId = s.session_id ?? 'unknown';
    if (!Array.isArray(s.skills) || s.skills.length === 0) {
      try { fs.unlinkSync(sessionFile); } catch {}
      console.log('{}'); process.exit(0);
    }
  } catch {
    try { fs.unlinkSync(sessionFile); } catch {}
    console.log('{}'); process.exit(0);
  }

  const observations = [];

  try {
    let data;
    try { data = JSON.parse(payload); } catch { data = null; }

    const transcriptPath = data?.transcript_path;
    if (transcriptPath && fs.existsSync(transcriptPath)) {
      const lines = fs.readFileSync(transcriptPath, 'utf-8').split('\\n');
      for (const line of lines) {
        if (!line.trim()) continue;
        let event;
        try { event = JSON.parse(line); } catch { continue; }

        if (event.type !== 'assistant') continue;
        const content = event.message?.content ?? [];
        for (const block of content) {
          if (block.type !== 'text') continue;
          const text = block.text ?? '';
          const matches = [...text.matchAll(OBSERVATION_RE)];
          for (const m of matches) {
            const artifactName = (m[1] ?? '').trim();
            const category = (m[2] ?? '').trim();
            const observation = (m[3] ?? '').trim();
            if (artifactName && category && observation) {
              observations.push({ artifactName, category, observation });
            }
          }
        }
      }
    }
  } catch { /* transcript unreadable — proceed to cleanup */ }

  // Step 3: write feedback files
  let wrote = 0;
  if (observations.length > 0) {
    try {
      fs.mkdirSync(feedbackDir, { recursive: true });
      for (const obs of observations) {
        const id = crypto.randomUUID();
        const severity = SEVERITY_MAP[obs.category] ?? 'low';
        const feedback = {
          id,
          skillName: obs.artifactName,
          timestamp: new Date().toISOString(),
          session_id: sessionId,
          category: obs.category,
          observation: obs.observation,
          severity,
          source: 'hook-transcript-scan',
          resolved: false,
        };
        const ts = new Date().toISOString().replace(/[:.]/g, '-');
        const filename = \`\${ts}-\${obs.artifactName}-\${id.slice(0, 8)}.json\`;
        fs.writeFileSync(path.join(feedbackDir, filename), JSON.stringify(feedback, null, 2), 'utf-8');
        wrote++;
      }
    } catch { /* non-critical */ }
  }

  // Step 4: clear session state (always)
  try { fs.unlinkSync(sessionFile); } catch {}

  // Step 5: check threshold and emit hint
  if (wrote > 0) {
    let count = 0;
    try { count = fs.readdirSync(feedbackDir).filter(f => f.endsWith('.json')).length; } catch {}
    if (count >= HINT_THRESHOLD) {
      console.log(JSON.stringify({
        additionalContext: \`[${PROJECT_NAME_DISPLAY}] \${count} observations in ${PROJECT_DIR}/feedback/ — run /${PROJECT_NAME}-refine-rules to review\`,
      }));
      process.exit(0);
    }
  }

  console.log('{}');
  process.exit(0);
}

main().catch(() => {
  console.log('{}');
  process.exit(0);
});
`;
}
