/**
 * Heartbeat hook scripts for codi's self-improvement feedback loop.
 *
 * skill-tracker  — InstructionsLoaded hook (async): records which codi skills are
 *                  active in the current session to .codi/.session/active-skills.json
 *
 * skill-observer — Stop hook (synchronous): scans the transcript for
 *                  [CODI-OBSERVATION: ...] markers and writes structured JSON to
 *                  .codi/feedback/. When 5+ observations accumulate, outputs an
 *                  additionalContext hint to prompt the user to run /codi-refine-rules.
 *
 * Both scripts are written to .codi/hooks/ during `codi generate`.
 * Claude Code wires them via .claude/settings.json; Codex via .codex/hooks.json.
 */

import { PROJECT_NAME, PROJECT_DIR, PROJECT_NAME_DISPLAY } from "#src/constants.js";

/** File name of the generated skill-tracker hook script. */
export const SKILL_TRACKER_FILENAME = `${PROJECT_NAME}-skill-tracker.cjs`;

/** File name of the generated skill-observer hook script. */
export const SKILL_OBSERVER_FILENAME = `${PROJECT_NAME}-skill-observer.cjs`;

/**
 * File name of the POSIX node-resolver launcher.
 *
 * Hooks run in non-interactive shells that do not source ~/.zshrc / ~/.bashrc,
 * so PATH-injecting tools (nvm, fnm) are not loaded. Invoking `node` directly
 * fails with "command not found" for users on those toolchains. Adapters wrap
 * the hook command as `/bin/sh <LAUNCHER> <SCRIPT>` so the launcher can walk a
 * fallback chain to locate a node binary across common install methods.
 */
export const LAUNCHER_FILENAME = "_run-node";

/** Directory inside PROJECT_DIR where hook scripts are written. */
export const HOOKS_SUBDIR = "hooks";

/** Directory inside PROJECT_DIR where session state is stored. */
export const SESSION_SUBDIR = ".session";

/** File name of the active-skills session state file. */
export const ACTIVE_SKILLS_FILENAME = "active-skills.json";

/** Observation threshold above which the hint fires. */
export const OBSERVATION_HINT_THRESHOLD = 5;

/**
 * Build the skill-tracker script content.
 *
 * Fires on InstructionsLoaded — appends the skill name and timestamp to
 * .codi/.session/active-skills.json when a codi skill SKILL.md is loaded.
 */
export function buildSkillTrackerScript(): string {
  return `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} skill-tracker — InstructionsLoaded hook (async)
// Tracks which codi skills are active in the current session.
// Do not edit — regenerated by: ${PROJECT_NAME} generate

const fs = require('fs');
const path = require('path');
const readline = require('readline');

// Resolve project root from script location: .codi/hooks/ -> project root
// This makes the hook work regardless of the cwd Claude Code uses.
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');

async function main() {
  let payload = '';
  const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
  for await (const line of rl) payload += line;

  let data;
  try { data = JSON.parse(payload); } catch { process.exit(0); }

  const filePath = data?.file_path ?? '';
  const sessionId = data?.session_id ?? 'unknown';

  // Only track codi skill SKILL.md files
  if (!filePath.includes('/.claude/skills/${PROJECT_NAME}-') || !filePath.endsWith('/SKILL.md')) {
    process.exit(0);
  }

  // Extract skill name: .claude/skills/codi-commit/SKILL.md -> codi-commit
  const parts = filePath.split('/');
  const skillsIdx = parts.lastIndexOf('skills');
  if (skillsIdx < 0 || skillsIdx + 1 >= parts.length) process.exit(0);
  const skillName = parts[skillsIdx + 1];
  if (!skillName) process.exit(0);

  const sessionFile = path.join(
    PROJECT_ROOT,
    '${PROJECT_DIR}',
    '${SESSION_SUBDIR}',
    '${ACTIVE_SKILLS_FILENAME}'
  );
  fs.mkdirSync(path.dirname(sessionFile), { recursive: true });

  let state = { session_id: sessionId, skills: [] };
  try { state = JSON.parse(fs.readFileSync(sessionFile, 'utf-8')); } catch {}
  if (!Array.isArray(state.skills)) state.skills = [];

  if (!state.skills.some(s => s.name === skillName)) {
    state.skills.push({ name: skillName, loaded_at: new Date().toISOString() });
    fs.writeFileSync(sessionFile, JSON.stringify(state, null, 2), 'utf-8');
  }
  process.exit(0);
}

main().catch(() => process.exit(0));
`;
}

/** Pattern text for CODI-OBSERVATION markers (used in generated script). */
const MARKER_PATTERN_TEXT =
  "\\\\[CODI-OBSERVATION:\\\\s*([^|\\\\]]+)\\\\|([^|\\\\]]+)\\\\|([^\\\\]]+)\\\\]";

/**
 * Build the skill-observer script content.
 *
 * Fires on Stop — scans the transcript for [CODI-OBSERVATION: ...] markers,
 * writes structured JSON to .codi/feedback/, and emits an additionalContext hint
 * when the feedback threshold is reached.
 */
export function buildSkillObserverScript(): string {
  return `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} skill-observer — Stop hook (synchronous)
// Extracts CODI-OBSERVATION markers from the transcript and writes feedback JSON.
// Do not edit — regenerated by: ${PROJECT_NAME} generate

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const crypto = require('crypto');

// Resolve project root from script location: .codi/hooks/ -> project root
// This makes the hook work regardless of the cwd Claude Code uses.
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');

const OBSERVATION_RE = new RegExp('${MARKER_PATTERN_TEXT}', 'g');
const SEVERITY_MAP = { 'user-correction': 'high', 'trigger-miss': 'medium', 'trigger-false': 'medium' };
const HINT_THRESHOLD = ${OBSERVATION_HINT_THRESHOLD};

async function main() {
  let payload = '';
  const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
  for await (const line of rl) payload += line;

  const sessionFile = path.join(PROJECT_ROOT, '${PROJECT_DIR}', '${SESSION_SUBDIR}', '${ACTIVE_SKILLS_FILENAME}');
  const feedbackDir = path.join(PROJECT_ROOT, '${PROJECT_DIR}', 'feedback');

  // Step 1: exit immediately if this is not a codi session
  if (!fs.existsSync(sessionFile)) { console.log('{}'); process.exit(0); }

  let sessionId = 'unknown';
  try {
    const s = JSON.parse(fs.readFileSync(sessionFile, 'utf-8'));
    sessionId = s.session_id ?? 'unknown';
    if (!Array.isArray(s.skills) || s.skills.length === 0) {
      try { fs.unlinkSync(sessionFile); } catch {}
      console.log('{}'); process.exit(0);
    }
  } catch {
    try { fs.unlinkSync(sessionFile); } catch {}
    console.log('{}'); process.exit(0);
  }

  const observations = [];

  try {
    let data;
    try { data = JSON.parse(payload); } catch { data = null; }

    const transcriptPath = data?.transcript_path;
    if (transcriptPath && fs.existsSync(transcriptPath)) {
      const lines = fs.readFileSync(transcriptPath, 'utf-8').split('\\n');
      for (const line of lines) {
        if (!line.trim()) continue;
        let event;
        try { event = JSON.parse(line); } catch { continue; }

        if (event.type !== 'assistant') continue;
        const content = event.message?.content ?? [];
        for (const block of content) {
          if (block.type !== 'text') continue;
          const text = block.text ?? '';
          const matches = [...text.matchAll(OBSERVATION_RE)];
          for (const m of matches) {
            const artifactName = (m[1] ?? '').trim();
            const category = (m[2] ?? '').trim();
            const observation = (m[3] ?? '').trim();
            if (artifactName && category && observation) {
              observations.push({ artifactName, category, observation });
            }
          }
        }
      }
    }
  } catch { /* transcript unreadable — proceed to cleanup */ }

  // Step 3: write feedback files
  let wrote = 0;
  if (observations.length > 0) {
    try {
      fs.mkdirSync(feedbackDir, { recursive: true });
      for (const obs of observations) {
        const id = crypto.randomUUID();
        const severity = SEVERITY_MAP[obs.category] ?? 'low';
        const feedback = {
          id,
          skillName: obs.artifactName,
          timestamp: new Date().toISOString(),
          session_id: sessionId,
          category: obs.category,
          observation: obs.observation,
          severity,
          source: 'hook-transcript-scan',
          resolved: false,
        };
        const ts = new Date().toISOString().replace(/[:.]/g, '-');
        const filename = \`\${ts}-\${obs.artifactName}-\${id.slice(0, 8)}.json\`;
        fs.writeFileSync(path.join(feedbackDir, filename), JSON.stringify(feedback, null, 2), 'utf-8');
        wrote++;
      }
    } catch { /* non-critical */ }
  }

  // Step 4: clear session state (always)
  try { fs.unlinkSync(sessionFile); } catch {}

  // Step 5: check threshold and emit hint
  if (wrote > 0) {
    let count = 0;
    try { count = fs.readdirSync(feedbackDir).filter(f => f.endsWith('.json')).length; } catch {}
    if (count >= HINT_THRESHOLD) {
      console.log(JSON.stringify({
        additionalContext: \`[${PROJECT_NAME_DISPLAY}] \${count} observations in ${PROJECT_DIR}/feedback/ — run /${PROJECT_NAME}-refine-rules to review\`,
      }));
      process.exit(0);
    }
  }

  console.log('{}');
  process.exit(0);
}

main().catch(() => {
  console.log('{}');
  process.exit(0);
});
`;
}

/**
 * Build the POSIX shell launcher that resolves a node binary across nvm, fnm,
 * Volta, asdf, Homebrew, and standard system locations. Adapters invoke this
 * via `/bin/sh <launcher> <script.cjs>` so non-interactive hook shells (which
 * do not source ~/.zshrc) can still find node.
 *
 * Targets macOS + Linux only. Codi does not support Windows; see README.
 */
export function buildLauncherScript(): string {
  return `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} ${LAUNCHER_FILENAME} — locate a node binary, then exec the supplied script.
# Do not edit — regenerated by: ${PROJECT_NAME} generate
#
# Hooks run in non-interactive shells that do not source ~/.zshrc or ~/.bashrc,
# so PATH-injecting tools (nvm, fnm) are not loaded. This launcher walks the
# most common install locations until it finds a node binary, then transfers
# control via exec.

set -e

# 1. Fast path — node is already on PATH (covers Homebrew, system installs,
#    asdf/Volta when their shims are on PATH at hook spawn time).
if command -v node >/dev/null 2>&1; then
  exec node "$@"
fi

# 2. Common static install locations.
for candidate in \\
  /opt/homebrew/bin/node \\
  /usr/local/bin/node \\
  /usr/bin/node \\
  "$HOME/.local/bin/node" \\
  "$HOME/.volta/bin/node" \\
  "$HOME/.asdf/shims/node"; do
  if [ -x "$candidate" ]; then
    exec "$candidate" "$@"
  fi
done

# 3. nvm — source the loader, retry; fall back to globbed installed versions.
if [ -s "$HOME/.nvm/nvm.sh" ]; then
  # shellcheck disable=SC1091
  . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1 || true
  if command -v node >/dev/null 2>&1; then
    exec node "$@"
  fi
fi
for nvm_node in "$HOME"/.nvm/versions/node/v*/bin/node; do
  if [ -x "$nvm_node" ]; then
    exec "$nvm_node" "$@"
  fi
done

# 4. fnm.
for fnm_node in "$HOME"/.fnm/node-versions/v*/installation/bin/node; do
  if [ -x "$fnm_node" ]; then
    exec "$fnm_node" "$@"
  fi
done

printf '${PROJECT_NAME_DISPLAY}: cannot find node executable.\\n' >&2
printf 'Install Node 24+ or add it to PATH.\\n' >&2
printf 'Searched: command -v node; static paths (homebrew, /usr, ~/.local, volta, asdf); nvm; fnm.\\n' >&2
exit 127
`;
}

/**
 * Build the hook command string that invokes the launcher with a target script.
 *
 * @param launcherPathExpr  Shell-quoted path expression to the launcher (e.g. `"\${CLAUDE_PROJECT_DIR:-.}/.codi/hooks/_run-node"`).
 * @param scriptPathExpr    Shell-quoted path expression to the .cjs script the launcher should exec.
 *
 * Returns: `/bin/sh <launcher> <script>` — `/bin/sh` is POSIX-guaranteed on
 * macOS and Linux, and the launcher does not need executable permission when
 * invoked this way.
 */
export function launcherCommand(launcherPathExpr: string, scriptPathExpr: string): string {
  return `/bin/sh ${launcherPathExpr} ${scriptPathExpr}`;
}

/**
 * Build the GeneratedFile entry for the launcher under .codi/hooks/.
 * Adapters call this once per generate() so the launcher is shipped alongside
 * the heartbeat scripts that depend on it.
 */
export function buildLauncherFile(): { path: string; content: string } {
  return {
    path: `${PROJECT_DIR}/${HOOKS_SUBDIR}/${LAUNCHER_FILENAME}`,
    content: buildLauncherScript(),
  };
}
