import {
  GIT_COMMIT_FIRST_LINE_LIMIT,
  PROJECT_CLI,
  PROJECT_NAME,
  PROJECT_NAME_DISPLAY,
} from "#src/constants.js";

/**
 * Pre-push documentation checkpoint hook.
 * Blocks pushes to protected branches when docs/project/.doc-stamp is outdated.
 * {{PROTECTED_BRANCHES}} is replaced with a space-separated list of branch patterns at install time.
 */
export const PRE_PUSH_DOC_CHECK_TEMPLATE = `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} documentation checkpoint — Auto-generated by ${PROJECT_CLI} init
# Blocks pushes to protected branches when documentation has not been verified.
# To verify: review docs/project/, update if needed, then run: codi docs-stamp

STAMP_FILE="docs/project/.doc-stamp"
PROTECTED_BRANCHES="{{PROTECTED_BRANCHES}}"

is_protected() {
  target="$1"
  for pat in $PROTECTED_BRANCHES; do
    case "$target" in
      $pat) return 0 ;;
    esac
  done
  return 1
}

blocked=0

while IFS=' ' read -r _local_ref _local_sha remote_ref _remote_sha; do
  [ -z "$remote_ref" ] && continue
  branch="\${remote_ref#refs/heads/}"

  if is_protected "$branch"; then
    if [ ! -f "$STAMP_FILE" ]; then
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  No stamp found at %s\\n' "$STAMP_FILE"
      printf '  Run: ${PROJECT_CLI} docs-stamp\\n'
      printf '  Then commit the stamp and push again.\\n\\n'
      blocked=1
      continue
    fi

    stamp_hash=\$(node -e "try{const s=JSON.parse(require('fs').readFileSync('$STAMP_FILE','utf8'));process.stdout.write(s.commit||'')}catch(e){}" 2>/dev/null)

    if [ -z "\$stamp_hash" ]; then
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  Stamp file is invalid or unreadable.\\n'
      printf '  Run: ${PROJECT_CLI} docs-stamp\\n'
      printf '  Then commit the stamp and push again.\\n\\n'
      blocked=1
      continue
    fi

    if ! git rev-parse --verify "\$stamp_hash^{commit}" >/dev/null 2>&1; then
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  Stamp hash not found in history (rebase invalidated it).\\n'
      printf '  Re-verify docs and run: ${PROJECT_CLI} docs-stamp\\n'
      printf '  Then commit the stamp and push again.\\n\\n'
      blocked=1
      continue
    fi

    count=\$(git rev-list "\$stamp_hash..HEAD" --count 2>/dev/null || echo 999)

    if [ "\$count" -gt 1 ]; then
      short=\$(echo "\$stamp_hash" | cut -c1-7)
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  %s commits since last doc verification (stamp: %s).\\n' "\$count" "\$short"
      printf '\\n  Commits to review:\\n'
      git log --oneline "\$stamp_hash..HEAD" | sed 's/^/    /'
      printf '\\n  Files changed since stamp:\\n'
      git diff --stat "\$stamp_hash..HEAD" -- . ':(exclude)docs/project/.doc-stamp' | sed 's/^/    /'
      printf '\\n  Action required (coding agent):\\n'
      printf '    1. Read each file in docs/project/ (artifacts.md, features.md, workflows.md, troubleshooting.md)\\n'
      printf '    2. For each commit above, determine whether the changes affect those docs\\n'
      printf '    3. Update docs/project/ files where needed\\n'
      printf '    4. Run: ${PROJECT_CLI} docs-stamp\\n'
      printf '    5. git add docs/project/.doc-stamp && git commit -m "chore: update doc stamp"\\n'
      printf '    6. Push again.\\n\\n'
      blocked=1
    fi
  fi
done

exit \$blocked
`;

export const COMMIT_MSG_TEMPLATE = `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} commit message validator — Auto-generated by ${PROJECT_CLI} init
node --input-type=module - "$1" << 'HOOK_SCRIPT'
import fs from 'fs';

const msgFile = process.argv[2];
if (!msgFile) {
  console.error('No commit message file provided');
  process.exit(1);
}

const msg = fs.readFileSync(msgFile, 'utf-8').trim();
const firstLine = msg.split('\\n')[0];

const TYPES = ['feat', 'fix', 'docs', 'refactor', 'test', 'chore', 'perf', 'ci', 'build', 'style', 'revert'];
const pattern = new RegExp(\`^(\${TYPES.join('|')})(\\\\([^)]+\\\\))?!?: .+\`);

if (!pattern.test(firstLine)) {
  console.error('Invalid commit message format.');
  console.error(\`Expected: type(scope): description\`);
  console.error(\`Types: \${TYPES.join(', ')}\`);
  console.error(\`Example: feat(auth): add OAuth2 login flow\`);
  console.error(\`Got: \${firstLine}\`);
  process.exit(1);
}

if (firstLine.length > ${GIT_COMMIT_FIRST_LINE_LIMIT}) {
  console.error(\`Commit message first line too long: \${firstLine.length} chars (max ${GIT_COMMIT_FIRST_LINE_LIMIT})\`);
  process.exit(1);
}
HOOK_SCRIPT
`;

export const SKILL_YAML_VALIDATE_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} SKILL.md YAML frontmatter validator
// Checks staged SKILL.md files for valid YAML syntax AND schema-constrained fields.
// Mirrors src/schemas/skill.ts — update both when schema changes.
import fs from 'fs';

const SKILL_OUTPUT_PATTERNS = [
  '.claude/skills/',
  '.codi/skills/',
  '.agents/skills/',
  '.cursor/skills/',
  '.windsurf/skills/',
  '.clinerules/',
];

// Mirrors src/constants.ts — update when constants change.
const VALID_MANAGED_BY = ['codi', 'user'];
const VALID_CATEGORIES = [
  'Brand Identity', 'Code Quality', 'Content Creation', 'Content Refinement',
  'Creative and Design', 'Developer Tools', 'Developer Workflow',
  'Document Generation', 'File Format Tools', 'Planning', 'Productivity',
  'Testing', 'Workflow', '${PROJECT_NAME_DISPLAY} Platform',
];
// Mirrors SUPPORTED_PLATFORMS in src/constants.ts
const VALID_PLATFORMS = ['claude-code', 'cursor', 'codex', 'windsurf', 'cline', 'copilot'];
const VALID_EFFORT = ['low', 'medium', 'high', 'max'];
const VALID_SHELL = ['bash', 'powershell'];

const files = process.argv.slice(2).filter(f => f.endsWith('.md'));
const relevant = files.filter(f =>
  SKILL_OUTPUT_PATTERNS.some(pattern => f.includes(pattern))
);

if (relevant.length === 0) process.exit(0);

const { parse } = await import('yaml');

let failed = false;
const warnings = [];

for (const file of relevant) {
  if (!fs.existsSync(file)) continue;
  const content = fs.readFileSync(file, 'utf-8');
  const fmMatch = content.match(/^---\\n([\\s\\S]*?)\\n---/);
  if (!fmMatch) continue;

  let fm;
  try {
    fm = parse(fmMatch[1]);
  } catch (err) {
    console.error(\`\\u26a0 \${file}: invalid YAML: \${err.message}\`);
    failed = true;
    continue;
  }

  if (!fm || typeof fm !== 'object') continue;

  // Required fields
  if (!fm.name || typeof fm.name !== 'string') {
    console.error(\`\\u26a0 \${file}: missing or invalid 'name' field\`);
    failed = true;
  }
  if (!fm.description || typeof fm.description !== 'string') {
    console.error(\`\\u26a0 \${file}: missing or invalid 'description' field\`);
    failed = true;
  }

  // Enum / type-constrained optional fields (blocking errors — mirror Zod schema)
  if (fm.compatibility !== undefined) {
    const compat = Array.isArray(fm.compatibility) ? fm.compatibility : [fm.compatibility];
    const invalid = compat.filter(v => !VALID_PLATFORMS.includes(v));
    if (invalid.length > 0) {
      console.error(\`\\u26a0 \${file}: 'compatibility' contains invalid platform(s): \${invalid.join(', ')}. Valid: \${VALID_PLATFORMS.join(', ')}\`);
      failed = true;
    }
  }
  if (fm['user-invocable'] !== undefined && typeof fm['user-invocable'] !== 'boolean') {
    console.error(\`\\u26a0 \${file}: 'user-invocable' must be a boolean (got \${JSON.stringify(fm['user-invocable'])})\`);
    failed = true;
  }
  if (fm['disable-model-invocation'] !== undefined && typeof fm['disable-model-invocation'] !== 'boolean') {
    console.error(\`\\u26a0 \${file}: 'disable-model-invocation' must be a boolean (got \${JSON.stringify(fm['disable-model-invocation'])})\`);
    failed = true;
  }
  if (fm.effort !== undefined && !VALID_EFFORT.includes(fm.effort)) {
    console.error(\`\\u26a0 \${file}: 'effort' must be one of [\${VALID_EFFORT.join(', ')}] (got "\${fm.effort}")\`);
    failed = true;
  }
  if (fm.shell !== undefined && !VALID_SHELL.includes(fm.shell)) {
    console.error(\`\\u26a0 \${file}: 'shell' must be one of [\${VALID_SHELL.join(', ')}] (got "\${fm.shell}")\`);
    failed = true;
  }
  if (fm.context !== undefined && fm.context !== 'fork') {
    console.error(\`\\u26a0 \${file}: 'context' must be "fork" if set (got "\${fm.context}")\`);
    failed = true;
  }

  // Non-blocking warnings
  if (fm.version !== undefined && (typeof fm.version !== 'number' || !Number.isInteger(fm.version) || fm.version <= 0)) {
    warnings.push(\`\${file}: 'version' should be a positive integer (got \${JSON.stringify(fm.version)})\`);
  }
  if (fm.managed_by !== undefined && !VALID_MANAGED_BY.includes(fm.managed_by)) {
    warnings.push(\`\${file}: 'managed_by' should be one of [\${VALID_MANAGED_BY.join(', ')}] (got "\${fm.managed_by}")\`);
  }
  if (fm.category !== undefined && !VALID_CATEGORIES.includes(fm.category)) {
    warnings.push(\`\${file}: 'category' "\${fm.category}" is not a recognized category. Valid: \${VALID_CATEGORIES.join(', ')}\`);
  }

  // Non-blocking: user-invocable skills must have a trigger clause in their description
  // so the agent knows when to activate them. Intent routing degrades without one.
  if (fm['user-invocable'] === true) {
    const desc = typeof fm.description === 'string' ? fm.description : '';
    const triggerPhrases = ['Use when', 'TRIGGER when', 'Activate when', 'Use for'];
    const hasTrigger = triggerPhrases.some(p => desc.includes(p));
    if (!hasTrigger) {
      warnings.push(\`\${file}: 'user-invocable' is true but description has no trigger clause. Add a "Use when..." sentence so the agent knows when to activate this skill.\`);
    }
  }
}

if (warnings.length > 0) {
  console.warn('\\n${PROJECT_NAME_DISPLAY} SKILL.md metadata warnings (non-blocking):');
  for (const w of warnings) console.warn('  \\u26a0 ' + w);
}

if (failed) {
  console.error('');
  console.error('SKILL.md YAML frontmatter validation failed.');
  console.error('Common causes: unquoted colon in description, invalid platform in compatibility, wrong type for boolean fields.');
  console.error('Fix: run "${PROJECT_CLI} generate" to regenerate files with proper quoting.');
  process.exit(1);
}
`;

export const IMPORT_DEPTH_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} import depth checker
// Blocks commits that introduce ../../ relative imports — use #src/* path aliases instead.
import fs from 'fs';

const IMPORT_RE = /^\\s*(?:import|export)(?:[^'"\\n]*from)?\\s+['"](\\.\\.\\/\\.\\.\\/[^'"]*)['"]/m;

const EXCLUDED = [
  /\\.d\\.ts$/,
  /\\/references\\//,
  /\\/scripts\\//,
  /\\.md$/,
];

const files = process.argv.slice(2).filter(f =>
  /\\.(ts|tsx|js|jsx|mts|mjs)$/.test(f) && !EXCLUDED.some(p => p.test(f))
);

const findings = [];

for (const file of files) {
  let content;
  try { content = fs.readFileSync(file, 'utf-8'); } catch { continue; }
  const lines = content.split('\\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!IMPORT_RE.test(line)) continue;
    const trimmed = line.trimStart();
    if (!trimmed.startsWith('import') && !trimmed.startsWith('export') && !trimmed.startsWith('} from')) continue;
    findings.push({ file, line: i + 1, text: trimmed.substring(0, 100) });
  }
}

if (findings.length > 0) {
  console.error('[import-depth] Deep relative imports found — use #src/* path aliases instead:');
  for (const f of findings) {
    console.error(\`  \${f.file}:\${f.line}  \${f.text}\`);
  }
  console.error('\\nFix: replace ../../ with #src/ (e.g. "../../types/result.js" → "#src/types/result.js")');
  process.exit(1);
}
`;
