import { GIT_COMMIT_FIRST_LINE_LIMIT } from '../../constants.js';

// These are template strings for generated hook scripts.
// They are written to disk as standalone Node.js scripts, not executed in this process.
// The use of execSync in templates is intentional for git hook runners.

export const RUNNER_TEMPLATE = `#!/bin/sh
# Codi pre-commit hook runner — Auto-generated by codi init
node --input-type=module << 'HOOK_SCRIPT'
import { execSync } from 'child_process';

const hooks = {{HOOKS_JSON}};

function getStagedFiles(filter) {
  try {
    const output = execSync('git diff --cached --name-only --diff-filter=ACMR', { encoding: 'utf-8' });
    const files = output.trim().split('\\n').filter(Boolean);
    if (!filter) return files;
    const re = new RegExp(filter.replace(/\\*\\*/g, '.*').replace(/\\*/g, '[^/]*'));
    return files.filter(f => re.test(f));
  } catch { return []; }
}

let exitCode = 0;
for (const hook of hooks) {
  const files = getStagedFiles(hook.stagedFilter);
  if (files.length === 0) continue;
  console.log(\`Running \${hook.name}...\`);
  try {
    execSync(\`\${hook.command} \${files.join(' ')}\`, { stdio: 'inherit' });
  } catch (e) {
    console.error(\`\${hook.name} failed\`);
    exitCode = 1;
  }
}
process.exit(exitCode);
HOOK_SCRIPT
`;

export const SECRET_SCAN_TEMPLATE = `#!/usr/bin/env node
// Codi secret scanner
import fs from 'fs';

const PATTERNS = [
  /(?:api[_-]?key|apikey)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /(?:secret|password|passwd|pwd)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /(?:token|bearer)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /-----BEGIN (?:RSA |EC |DSA )?PRIVATE KEY-----/,
  /ghp_[a-zA-Z0-9]{36}/,
  /sk-[a-zA-Z0-9]{32,}/,
];

const files = process.argv.slice(2);
let found = false;
for (const file of files) {
  try {
    const content = fs.readFileSync(file, 'utf-8');
    for (const pattern of PATTERNS) {
      if (pattern.test(content)) {
        console.error(\`Potential secret found in \${file}\`);
        found = true;
        break;
      }
    }
  } catch {}
}
if (found) process.exit(1);
`;

export const VERSION_CHECK_TEMPLATE = `#!/usr/bin/env node
// Codi version and freshness checker
// Auto-generated by codi init

import { execFileSync } from 'child_process';

try {
  execFileSync('npx', ['codi', 'doctor', '--ci'], { stdio: 'inherit' });
} catch (e) {
  process.exit(1);
}
`;

export const FILE_SIZE_CHECK_TEMPLATE = `#!/usr/bin/env node
// Codi file size checker
import fs from 'fs';

const maxLines = {{MAX_LINES}};
const files = process.argv.slice(2);
let failed = false;
for (const file of files) {
  try {
    const content = fs.readFileSync(file, 'utf-8');
    const lines = content.split('\\n').length;
    if (lines > maxLines) {
      console.error(\`\${file}: \${lines} lines (max: \${maxLines})\`);
      failed = true;
    }
  } catch {}
}
if (failed) process.exit(1);
`;

export const COMMIT_MSG_TEMPLATE = `#!/bin/sh
# Codi commit message validator — Auto-generated by codi init
node --input-type=module - "$1" << 'HOOK_SCRIPT'
import fs from 'fs';

const msgFile = process.argv[2];
if (!msgFile) {
  console.error('No commit message file provided');
  process.exit(1);
}

const msg = fs.readFileSync(msgFile, 'utf-8').trim();
const firstLine = msg.split('\\n')[0];

const TYPES = ['feat', 'fix', 'docs', 'refactor', 'test', 'chore', 'perf', 'ci', 'build', 'style', 'revert'];
const pattern = new RegExp(\`^(\${TYPES.join('|')})(\\\\([^)]+\\\\))?!?: .+\`);

if (!pattern.test(firstLine)) {
  console.error('Invalid commit message format.');
  console.error(\`Expected: type(scope): description\`);
  console.error(\`Types: \${TYPES.join(', ')}\`);
  console.error(\`Example: feat(auth): add OAuth2 login flow\`);
  console.error(\`Got: \${firstLine}\`);
  process.exit(1);
}

if (firstLine.length > ${GIT_COMMIT_FIRST_LINE_LIMIT}) {
  console.error(\`Commit message first line too long: \${firstLine.length} chars (max ${GIT_COMMIT_FIRST_LINE_LIMIT})\`);
  process.exit(1);
}
HOOK_SCRIPT
`;
