import { PROJECT_CLI, PROJECT_NAME_DISPLAY } from "#src/constants.js";

// These are template strings for generated hook scripts.
// They are written to disk as standalone Node.js scripts, not executed in this process.
// The use of execSync in templates is intentional for git hook runners.

export const RUNNER_TEMPLATE = `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} pre-commit hook runner — Auto-generated by ${PROJECT_CLI} init
node --input-type=module << 'HOOK_SCRIPT'
import { execFileSync } from 'child_process';

const hooks = {{HOOKS_JSON}};

function getStagedFiles(filter) {
  try {
    const output = execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' });
    const files = output.trim().split('\\n').filter(Boolean);
    if (!filter) return files;
    const re = new RegExp(filter.replace(/\\*\\*/g, '.*').replace(/\\*/g, '[^/]*'));
    return files.filter(f => re.test(f));
  } catch { return []; }
}

let exitCode = 0;
let lastLang = '';
for (const hook of hooks) {
  const files = getStagedFiles(hook.stagedFilter);
  if (files.length === 0) continue;
  const hookLang = hook.language ?? '';
  if (hookLang !== lastLang) {
    console.log(hookLang ? \`\\n[\${hookLang}]\` : \`\\n[global]\`);
    lastLang = hookLang;
  }
  console.log(\`  Running \${hook.name}...\`);
  const [bin, ...baseArgs] = hook.command.split(/\\s+/);
  const args = hook.passFiles === false ? baseArgs : [...baseArgs, ...files];
  try {
    execFileSync(bin, args, { stdio: 'inherit' });
    if (hook.modifiesFiles) {
      execFileSync('git', ['add', ...files], { stdio: 'inherit' });
    }
  } catch (e) {
    console.error(\`\${hook.name} failed\`);
    exitCode = 1;
  }
}
process.exit(exitCode);
HOOK_SCRIPT
`;

export const SECRET_SCAN_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} secret scanner
import fs from 'fs';

const PATTERNS = [
  /(?:api[_-]?key|apikey)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /(?:secret|password|passwd|pwd)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /(?:token|bearer)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /-----BEGIN (?:RSA |EC |DSA )?PRIVATE KEY-----/,
  /ghp_[a-zA-Z0-9]{36}/,
  /gho_[a-zA-Z0-9]{36}/,
  /github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}/,
  /sk-[a-zA-Z0-9]{32,}/,
  /xox[bpors]-[a-zA-Z0-9-]{10,}/,
  /AKIA[0-9A-Z]{16}/,
];

// Lines matching any of these are safe (env var refs, placeholders, examples)
const FALSE_POS = [
  /['"](?:your-|example-|test-|dummy-|fake-|placeholder)/i,
  /\\\\*\\$\\{/,
  /process\\.env/,
  /os\\.environ/,
  /import\\.meta\\.env/,
  /\\bgetenv\\b/,
  /['"](?:changeme|replace.?me|xxx+|\\*{3,}|TODO|FIXME)/i,
  /sk-[a-z]{3,6}\\d{2,4}(?:\\.\\.\\.|\\*)/,
];

const EXCLUDED = [
  /tests?\\//,
  /\\.test\\.[jt]sx?$/,
  /\\.spec\\.[jt]sx?$/,
  /__tests__\\//,
  /\\/references\\//,
  /\\/templates\\//,
  /docs\\//,
  /\\.md$/,
];

/**
 * Shannon entropy: real secrets have high entropy (>3.5),
 * env var names and placeholders have low entropy.
 */
function entropy(s) {
  if (s.length === 0) return 0;
  const freq = {};
  for (const c of s) freq[c] = (freq[c] || 0) + 1;
  let e = 0;
  for (const k in freq) {
    const p = freq[k] / s.length;
    e -= p * Math.log2(p);
  }
  return e;
}

/** Extract the quoted value from a matched line */
function extractQuotedValue(line) {
  const m = line.match(/[:=]\\s*['"]([^'"]{8,})['"]/);
  return m ? m[1] : null;
}

const files = process.argv.slice(2).filter(f => !EXCLUDED.some(p => p.test(f)));
const findings = [];
for (const file of files) {
  try {
    const content = fs.readFileSync(file, 'utf-8');
    const lines = content.split('\\n');
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const matchedPattern = PATTERNS.find(p => p.test(line));
      if (!matchedPattern) continue;
      if (FALSE_POS.some(fp => fp.test(line))) continue;

      // For key=value patterns, check entropy of the value
      const val = extractQuotedValue(line);
      if (val && entropy(val) < 3.0) continue;

      findings.push({ file, line: i + 1, text: line.trim().substring(0, 80) });
    }
  } catch {}
}
if (findings.length > 0) {
  for (const f of findings) {
    console.error(\`[secret-scan] \${f.file}:\${f.line}  \${f.text}\`);
  }
  console.error(\`\\n\${findings.length} potential secret(s) found. If these are false positives, move them to a file excluded by the scanner (tests/, templates/, references/, docs/).\`);
  process.exit(1);
}
`;

export const VERSION_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} version and freshness checker
// Auto-generated by ${PROJECT_CLI} init

import { execFileSync } from 'child_process';

try {
  execFileSync('npx', ['${PROJECT_CLI}', 'doctor', '--ci'], { stdio: 'inherit' });
} catch (e) {
  process.exit(1);
}
`;

export const FILE_SIZE_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} file size checker
import fs from 'fs';

const maxLines = {{MAX_LINES}};
const EXCLUDED = [/^\\.(clinerules|cursorrules|windsurfrules)$/, /^AGENTS\\.md$/, /^CLAUDE\\.md$/, /^\\.(claude|cursor|windsurf|cline|codex|agents)\\//, /-lock\\.json$/, /\\.lock$/, /-lock\\.yaml$/, /^pnpm-lock\\.yaml$/, /\\/assets\\//, /\\/references\\//, /\\/scripts\\/office\\//, /\\.xsd$/, /\\.ttf$/, /\\.woff2?$/, /\\.pdf$/, /\\.html$/];
const files = process.argv.slice(2).filter(f => !EXCLUDED.some(p => p.test(f)));
let failed = false;
for (const file of files) {
  try {
    const content = fs.readFileSync(file, 'utf-8');
    const lines = content.split('\\n').length;
    if (lines > maxLines) {
      console.error(\`\${file}: \${lines} lines (max: \${maxLines})\`);
      failed = true;
    }
  } catch {}
}
if (failed) process.exit(1);
`;

export const TEMPLATE_WIRING_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} template wiring checker
// Validates that all artifact template files are registered in index.ts and loader TEMPLATE_MAP.
import fs from 'fs';
import path from 'path';

const ARTIFACT_TYPES = [
  {
    name: 'rules',
    templateDir: 'src/templates/rules',
    indexFile: 'src/templates/rules/index.ts',
    loaderFile: 'src/core/scaffolder/template-loader.ts',
    excludeFiles: [],
    deprecated: [],
    useDirs: false,
  },
  {
    name: 'skills',
    templateDir: 'src/templates/skills',
    indexFile: 'src/templates/skills/index.ts',
    loaderFile: 'src/core/scaffolder/skill-template-loader.ts',
    excludeFiles: ['types.ts', 'resolve-static-dir.ts'],
    deprecated: ['presentation'],
    useDirs: true,
  },
  {
    name: 'agents',
    templateDir: 'src/templates/agents',
    indexFile: 'src/templates/agents/index.ts',
    loaderFile: 'src/core/scaffolder/agent-template-loader.ts',
    excludeFiles: [],
    deprecated: [],
    useDirs: false,
  },
];

function getFilesystemEntries(dir, useDirs, excludeFiles) {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const names = new Set();
    for (const entry of entries) {
      if (entry.name === 'index.ts' || excludeFiles.includes(entry.name)) continue;
      if (useDirs && entry.isDirectory()) {
        names.add(entry.name);
      } else if (!useDirs && entry.isFile() && entry.name.endsWith('.ts')) {
        names.add(entry.name.replace(/\\.ts$/, ''));
      }
    }
    return names;
  } catch { return new Set(); }
}

function getIndexExports(indexFile) {
  try {
    const content = fs.readFileSync(indexFile, 'utf-8');
    // Strip comment lines to avoid matching commented-out exports
    const active = content.split('\\n').filter(l => !l.trimStart().startsWith('//')).join('\\n');
    const names = new Set();
    // Match: from "./xxx.js" or from "./xxx/index.js" (works for both single and multiline exports)
    const re = /from\\s+["']\\.\\/([-a-z0-9]+)(?:\\/index)?\\.js["']/g;
    let match;
    while ((match = re.exec(active)) !== null) {
      names.add(match[1]);
    }
    return names;
  } catch { return new Set(); }
}

function getLoaderEntries(loaderFile) {
  try {
    const content = fs.readFileSync(loaderFile, 'utf-8');
    const names = new Set();
    // Match: prefixedName("xxx") or devArtifactName("xxx")
    const re = /(?:prefixedName|devArtifactName)\\(["']([-a-z0-9]+)["']\\)/g;
    let match;
    while ((match = re.exec(content)) !== null) {
      names.add(match[1]);
    }
    return names;
  } catch { return new Set(); }
}

const errors = [];

for (const art of ARTIFACT_TYPES) {
  const fsEntries = getFilesystemEntries(art.templateDir, art.useDirs, art.excludeFiles);
  const indexEntries = getIndexExports(art.indexFile);
  const loaderEntries = getLoaderEntries(art.loaderFile);
  const deprecated = new Set(art.deprecated);

  // Check: file exists but not in index.ts
  for (const name of fsEntries) {
    if (deprecated.has(name)) continue;
    if (!indexEntries.has(name)) {
      errors.push(art.name + ': "' + name + '" exists on disk but is NOT exported in ' + art.indexFile);
    }
  }

  // Check: exported in index.ts but not in loader TEMPLATE_MAP
  for (const name of indexEntries) {
    if (!loaderEntries.has(name)) {
      errors.push(art.name + ': "' + name + '" exported in ' + art.indexFile + ' but NOT in ' + art.loaderFile + ' TEMPLATE_MAP');
    }
  }

  // Check: in loader but not in index.ts (belt-and-suspenders — TypeScript catches this too)
  for (const name of loaderEntries) {
    if (!indexEntries.has(name) && !deprecated.has(name)) {
      errors.push(art.name + ': "' + name + '" in ' + art.loaderFile + ' TEMPLATE_MAP but NOT exported in ' + art.indexFile);
    }
  }
}

// Additionally check that every skill template has a 'category' field in its frontmatter.
// This prevents contributors from shipping skills without proper catalog metadata.
const skillType = ARTIFACT_TYPES.find(a => a.name === 'skills');
if (skillType) {
  const skillDirs = getFilesystemEntries(skillType.templateDir, true, skillType.excludeFiles);
  for (const dirName of skillDirs) {
    const templateFile = path.join(skillType.templateDir, dirName, 'template.ts');
    try {
      const content = fs.readFileSync(templateFile, 'utf-8');
      // Look for category: inside a template literal frontmatter block
      if (!content.includes('category:')) {
        errors.push('skills: template "' + dirName + '" is missing category in frontmatter (template.ts has no category: field)');
      }
    } catch { /* template.ts missing — wiring check above will catch it */ }
  }
}

if (errors.length > 0) {
  console.error('Template wiring errors found:');
  for (const e of errors) console.error('  ' + e);
  console.error('\\nFix: export the template in index.ts AND add it to the loader TEMPLATE_MAP.');
  console.error('For missing category: add a category field to the skill frontmatter in template.ts.');
  process.exit(1);
}
`;

export const SKILL_RESOURCE_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} skill resource reference checker
// Validates that files referenced in skill files actually exist on disk.
// Covers two circuits:
//   User circuit:      .codi/skills/*/{SKILL.md,**/*.md}   -> checks file existence in skill dir
//   Developer circuit: src/templates/skills/*/{template.ts,**/*.md} -> checks staticDir + file presence
// Convention: wrap resource paths with [[/path]] markers so this hook can validate them.
// The parser also tolerates [[ /path ]] to avoid false negatives from older examples.
// The adapter strips [[...]] at generate time; markdown files keep them as-is.
import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();

// One pattern: [[/path]] markers with optional inner whitespace.
// This avoids false positives from TOML [[section]] and PHP arrays while accepting
// both the canonical compact form and older spaced examples like [[ /path ]].
const REFERENCE_PATTERNS = [
  /\\[\\[\\s*(\\/[^[\\]]*?)\\s*\\]\\]/g,
];

const EXCLUDED = [/^\\/evals\\//, /[*?{}[\\]]/, /^https?:\\/\\//, /^path$/];

function extractRefs(content) {
  // Strip <example>...</example> blocks so documented examples of [[/path]] syntax are not validated.
  const cleaned = content.replace(/<example>[\\s\\S]*?<\\/example>/g, '');
  const refs = new Set();
  for (const re of REFERENCE_PATTERNS) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(cleaned)) !== null) {
      const raw = m[1].trim().replace(/[.,;)]+$/, '');
      const ref = raw.startsWith('/') ? raw.slice(1) : raw; // strip leading slash
      if (ref && !EXCLUDED.some(p => p.test(ref))) refs.add(ref);
    }
  }
  return refs;
}

// Collect all .md files recursively under dir
function collectMdFiles(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...collectMdFiles(full));
    else if (entry.isFile() && entry.name.endsWith('.md')) results.push(full);
  }
  return results;
}

const errors = [];

// User circuit: .codi/skills/
const codiSkillsDir = path.join(ROOT, '.codi', 'skills');
if (fs.existsSync(codiSkillsDir)) {
  for (const entry of fs.readdirSync(codiSkillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillDir = path.join(codiSkillsDir, entry.name);
    const skillMd = path.join(skillDir, 'SKILL.md');
    if (!fs.existsSync(skillMd)) continue;
    // Check SKILL.md and all *.md files in the skill directory
    const mdFiles = [skillMd, ...collectMdFiles(skillDir).filter(f => f !== skillMd)];
    for (const mdFile of mdFiles) {
      for (const ref of extractRefs(fs.readFileSync(mdFile, 'utf-8'))) {
        if (!fs.existsSync(path.join(skillDir, ref))) {
          errors.push({ source: path.relative(ROOT, mdFile), ref });
        }
      }
    }
  }
}

// Developer circuit: src/templates/skills/
const tmplSkillsDir = path.join(ROOT, 'src', 'templates', 'skills');
if (fs.existsSync(tmplSkillsDir)) {
  for (const entry of fs.readdirSync(tmplSkillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillTemplateDir = path.join(tmplSkillsDir, entry.name);
    const tmplFile = path.join(skillTemplateDir, 'template.ts');
    if (!fs.existsSync(tmplFile)) continue;

    const indexFile = path.join(skillTemplateDir, 'index.ts');
    let hasStatic = false;
    try { hasStatic = fs.readFileSync(indexFile, 'utf-8').includes('staticDir'); } catch {}

    // Check template.ts and all *.md files under the skill template directory
    const filesToCheck = [{ file: tmplFile, isTemplate: true }, ...collectMdFiles(skillTemplateDir).map(f => ({ file: f, isTemplate: false }))];
    for (const { file, isTemplate } of filesToCheck) {
      const refs = extractRefs(fs.readFileSync(file, 'utf-8'));
      for (const ref of refs) {
        if (!hasStatic && isTemplate) {
          errors.push({ source: path.relative(ROOT, file), ref, extra: 'no staticDir — resource will not be copied to scaffolded skills' });
        } else if (!fs.existsSync(path.join(skillTemplateDir, ref))) {
          errors.push({ source: path.relative(ROOT, file), ref });
        }
      }
    }
  }
}

// Generated agent circuits: validate [[/path]] markers in generated skill directories.
// .claude/skills/ is excluded — Claude Code strips markers at generate time by design.
const AGENT_SKILL_DIRS = ['.agents/skills', '.windsurf/skills', '.cline/skills'];
for (const relDir of AGENT_SKILL_DIRS) {
  const agentSkillsDir = path.join(ROOT, relDir);
  if (!fs.existsSync(agentSkillsDir)) continue;
  for (const entry of fs.readdirSync(agentSkillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillDir = path.join(agentSkillsDir, entry.name);
    const mdFiles = collectMdFiles(skillDir);
    for (const mdFile of mdFiles) {
      for (const ref of extractRefs(fs.readFileSync(mdFile, 'utf-8'))) {
        if (!fs.existsSync(path.join(skillDir, ref))) {
          errors.push({ source: path.relative(ROOT, mdFile), ref });
        }
      }
    }
  }
}

if (errors.length > 0) {
  console.error('\\nSkill resource reference errors found:\\n');
  const bySource = {};
  for (const { source, ref, extra } of errors) {
    if (!bySource[source]) bySource[source] = [];
    bySource[source].push(extra ? ref + ' (' + extra + ')' : ref);
  }
  for (const [source, refs] of Object.entries(bySource)) {
    console.error('  ' + source + ':');
    for (const ref of refs) console.error("    references '" + ref + "' — file does not exist");
  }
  console.error('\\nFix: create the missing resource files, or remove the references.');
  console.error('     Wrap resource paths with [[/path]] markers so the hook can validate them.');
  console.error('     Example: \${CLAUDE_SKILL_DIR}[[/scripts/run.py]]  — non-Claude-Code agents keep [[]] markers.');
  console.error('     For templates: export staticDir in index.ts and place files in the template directory.');
  process.exit(1);
}
`;

export const DOC_NAMING_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} doc naming check
// Validates docs/ filenames follow YYYYMMDD_HHMMSS_[CATEGORY]_filename.ext when docs are staged.
import { execFileSync } from 'child_process';

const staged = (() => {
  try {
    return execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' })
      .trim().split('\\n').filter(Boolean);
  } catch { return []; }
})();

const hasDocs = staged.some(f => f.startsWith('docs/'));
if (!hasDocs) process.exit(0);

try {
  execFileSync('python3', ['scripts/validate-docs.py', '--quiet'], { stdio: 'inherit' });
} catch {
  console.error('');
  console.error('Documentation naming validation failed.');
  console.error('Run: python3 scripts/validate-docs.py  to see which files need renaming.');
  console.error('Format: YYYYMMDD_HHMMSS_[CATEGORY]_filename.ext');
  process.exit(1);
}
`;

export const ARTIFACT_VALIDATE_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} artifact validator
// Runs codi validate when .codi/ files are staged, blocking commits with broken artifacts.
import { execFileSync } from 'child_process';

const staged = (() => {
  try {
    return execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' })
      .trim().split('\\n').filter(Boolean);
  } catch { return []; }
})();

const hasCodi = staged.some(f => f.startsWith('.codi/'));
if (!hasCodi) process.exit(0);

console.log('Validating .codi/ artifacts...');

try {
  execFileSync('npx', ['codi', 'validate', '--ci'], { stdio: 'inherit' });
} catch {
  console.error('');
  console.error('codi artifact validation failed.');
  console.error('Run: npx codi validate  to see full details.');
  console.error('Fix the errors above, then re-stage the files and commit again.');
  process.exit(1);
}
`;

/**
 * Pre-push documentation checkpoint hook.
 * Blocks pushes to protected branches when docs/project/.doc-stamp is outdated.
 * {{PROTECTED_BRANCHES}} is replaced with a space-separated list of branch patterns at install time.
 */
