import {
  GIT_COMMIT_FIRST_LINE_LIMIT,
  PROJECT_CLI,
  PROJECT_NAME,
  PROJECT_NAME_DISPLAY,
} from "#src/constants.js";

// These are template strings for generated hook scripts.
// They are written to disk as standalone Node.js scripts, not executed in this process.
// The use of execSync in templates is intentional for git hook runners.

export const RUNNER_TEMPLATE = `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} pre-commit hook runner — Auto-generated by ${PROJECT_CLI} init
node --input-type=module << 'HOOK_SCRIPT'
import { execFileSync } from 'child_process';

const hooks = {{HOOKS_JSON}};

function getStagedFiles(filter) {
  try {
    const output = execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' });
    const files = output.trim().split('\\n').filter(Boolean);
    if (!filter) return files;
    const re = new RegExp(filter.replace(/\\*\\*/g, '.*').replace(/\\*/g, '[^/]*'));
    return files.filter(f => re.test(f));
  } catch { return []; }
}

let exitCode = 0;
let lastLang = '';
for (const hook of hooks) {
  const files = getStagedFiles(hook.stagedFilter);
  if (files.length === 0) continue;
  const hookLang = hook.language ?? '';
  if (hookLang !== lastLang) {
    console.log(hookLang ? \`\\n[\${hookLang}]\` : \`\\n[global]\`);
    lastLang = hookLang;
  }
  console.log(\`  Running \${hook.name}...\`);
  const [bin, ...baseArgs] = hook.command.split(/\\s+/);
  const args = hook.passFiles === false ? baseArgs : [...baseArgs, ...files];
  try {
    execFileSync(bin, args, { stdio: 'inherit' });
    if (hook.modifiesFiles) {
      execFileSync('git', ['add', ...files], { stdio: 'inherit' });
    }
  } catch (e) {
    console.error(\`\${hook.name} failed\`);
    exitCode = 1;
  }
}
process.exit(exitCode);
HOOK_SCRIPT
`;

export const SECRET_SCAN_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} secret scanner
import fs from 'fs';

const PATTERNS = [
  /(?:api[_-]?key|apikey)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /(?:secret|password|passwd|pwd)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /(?:token|bearer)\\s*[:=]\\s*['"][^'"]{8,}/i,
  /-----BEGIN (?:RSA |EC |DSA )?PRIVATE KEY-----/,
  /ghp_[a-zA-Z0-9]{36}/,
  /gho_[a-zA-Z0-9]{36}/,
  /github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}/,
  /sk-[a-zA-Z0-9]{32,}/,
  /xox[bpors]-[a-zA-Z0-9-]{10,}/,
  /AKIA[0-9A-Z]{16}/,
];

// Lines matching any of these are safe (env var refs, placeholders, examples)
const FALSE_POS = [
  /['"](?:your-|example-|test-|dummy-|fake-|placeholder)/i,
  /\\\\*\\$\\{/,
  /process\\.env/,
  /os\\.environ/,
  /import\\.meta\\.env/,
  /\\bgetenv\\b/,
  /['"](?:changeme|replace.?me|xxx+|\\*{3,}|TODO|FIXME)/i,
  /sk-[a-z]{3,6}\\d{2,4}(?:\\.\\.\\.|\\*)/,
];

const EXCLUDED = [
  /tests?\\//,
  /\\.test\\.[jt]sx?$/,
  /\\.spec\\.[jt]sx?$/,
  /__tests__\\//,
  /\\/references\\//,
  /\\/templates\\//,
  /docs\\//,
  /\\.md$/,
];

/**
 * Shannon entropy: real secrets have high entropy (>3.5),
 * env var names and placeholders have low entropy.
 */
function entropy(s) {
  if (s.length === 0) return 0;
  const freq = {};
  for (const c of s) freq[c] = (freq[c] || 0) + 1;
  let e = 0;
  for (const k in freq) {
    const p = freq[k] / s.length;
    e -= p * Math.log2(p);
  }
  return e;
}

/** Extract the quoted value from a matched line */
function extractQuotedValue(line) {
  const m = line.match(/[:=]\\s*['"]([^'"]{8,})['"]/);
  return m ? m[1] : null;
}

const files = process.argv.slice(2).filter(f => !EXCLUDED.some(p => p.test(f)));
const findings = [];
for (const file of files) {
  try {
    const content = fs.readFileSync(file, 'utf-8');
    const lines = content.split('\\n');
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const matchedPattern = PATTERNS.find(p => p.test(line));
      if (!matchedPattern) continue;
      if (FALSE_POS.some(fp => fp.test(line))) continue;

      // For key=value patterns, check entropy of the value
      const val = extractQuotedValue(line);
      if (val && entropy(val) < 3.0) continue;

      findings.push({ file, line: i + 1, text: line.trim().substring(0, 80) });
    }
  } catch {}
}
if (findings.length > 0) {
  for (const f of findings) {
    console.error(\`[secret-scan] \${f.file}:\${f.line}  \${f.text}\`);
  }
  console.error(\`\\n\${findings.length} potential secret(s) found. If these are false positives, move them to a file excluded by the scanner (tests/, templates/, references/, docs/).\`);
  process.exit(1);
}
`;

export const VERSION_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} version and freshness checker
// Auto-generated by ${PROJECT_CLI} init

import { execFileSync } from 'child_process';

try {
  execFileSync('npx', ['${PROJECT_CLI}', 'doctor', '--ci'], { stdio: 'inherit' });
} catch (e) {
  process.exit(1);
}
`;

export const FILE_SIZE_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} file size checker
import fs from 'fs';

const maxLines = {{MAX_LINES}};
const EXCLUDED = [/^\\.(clinerules|cursorrules|windsurfrules)$/, /^AGENTS\\.md$/, /^CLAUDE\\.md$/, /^\\.(claude|cursor|windsurf|cline|codex|agents)\\//, /-lock\\.json$/, /\\.lock$/, /\\/assets\\//, /\\/references\\//, /\\/scripts\\/office\\//, /\\.xsd$/, /\\.ttf$/, /\\.woff2?$/, /\\.pdf$/, /\\.html$/];
const files = process.argv.slice(2).filter(f => !EXCLUDED.some(p => p.test(f)));
let failed = false;
for (const file of files) {
  try {
    const content = fs.readFileSync(file, 'utf-8');
    const lines = content.split('\\n').length;
    if (lines > maxLines) {
      console.error(\`\${file}: \${lines} lines (max: \${maxLines})\`);
      failed = true;
    }
  } catch {}
}
if (failed) process.exit(1);
`;

export const TEMPLATE_WIRING_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} template wiring checker
// Validates that all artifact template files are registered in index.ts and loader TEMPLATE_MAP.
import fs from 'fs';
import path from 'path';

const ARTIFACT_TYPES = [
  {
    name: 'rules',
    templateDir: 'src/templates/rules',
    indexFile: 'src/templates/rules/index.ts',
    loaderFile: 'src/core/scaffolder/template-loader.ts',
    excludeFiles: [],
    deprecated: [],
    useDirs: false,
  },
  {
    name: 'skills',
    templateDir: 'src/templates/skills',
    indexFile: 'src/templates/skills/index.ts',
    loaderFile: 'src/core/scaffolder/skill-template-loader.ts',
    excludeFiles: ['types.ts', 'resolve-static-dir.ts'],
    deprecated: ['presentation'],
    useDirs: true,
  },
  {
    name: 'agents',
    templateDir: 'src/templates/agents',
    indexFile: 'src/templates/agents/index.ts',
    loaderFile: 'src/core/scaffolder/agent-template-loader.ts',
    excludeFiles: [],
    deprecated: [],
    useDirs: false,
  },
];

function getFilesystemEntries(dir, useDirs, excludeFiles) {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const names = new Set();
    for (const entry of entries) {
      if (entry.name === 'index.ts' || excludeFiles.includes(entry.name)) continue;
      if (useDirs && entry.isDirectory()) {
        names.add(entry.name);
      } else if (!useDirs && entry.isFile() && entry.name.endsWith('.ts')) {
        names.add(entry.name.replace(/\\.ts$/, ''));
      }
    }
    return names;
  } catch { return new Set(); }
}

function getIndexExports(indexFile) {
  try {
    const content = fs.readFileSync(indexFile, 'utf-8');
    // Strip comment lines to avoid matching commented-out exports
    const active = content.split('\\n').filter(l => !l.trimStart().startsWith('//')).join('\\n');
    const names = new Set();
    // Match: from "./xxx.js" or from "./xxx/index.js" (works for both single and multiline exports)
    const re = /from\\s+["']\\.\\/([-a-z0-9]+)(?:\\/index)?\\.js["']/g;
    let match;
    while ((match = re.exec(active)) !== null) {
      names.add(match[1]);
    }
    return names;
  } catch { return new Set(); }
}

function getLoaderEntries(loaderFile) {
  try {
    const content = fs.readFileSync(loaderFile, 'utf-8');
    const names = new Set();
    // Match: prefixedName("xxx") or devArtifactName("xxx")
    const re = /(?:prefixedName|devArtifactName)\\(["']([-a-z0-9]+)["']\\)/g;
    let match;
    while ((match = re.exec(content)) !== null) {
      names.add(match[1]);
    }
    return names;
  } catch { return new Set(); }
}

const errors = [];

for (const art of ARTIFACT_TYPES) {
  const fsEntries = getFilesystemEntries(art.templateDir, art.useDirs, art.excludeFiles);
  const indexEntries = getIndexExports(art.indexFile);
  const loaderEntries = getLoaderEntries(art.loaderFile);
  const deprecated = new Set(art.deprecated);

  // Check: file exists but not in index.ts
  for (const name of fsEntries) {
    if (deprecated.has(name)) continue;
    if (!indexEntries.has(name)) {
      errors.push(art.name + ': "' + name + '" exists on disk but is NOT exported in ' + art.indexFile);
    }
  }

  // Check: exported in index.ts but not in loader TEMPLATE_MAP
  for (const name of indexEntries) {
    if (!loaderEntries.has(name)) {
      errors.push(art.name + ': "' + name + '" exported in ' + art.indexFile + ' but NOT in ' + art.loaderFile + ' TEMPLATE_MAP');
    }
  }

  // Check: in loader but not in index.ts (belt-and-suspenders — TypeScript catches this too)
  for (const name of loaderEntries) {
    if (!indexEntries.has(name) && !deprecated.has(name)) {
      errors.push(art.name + ': "' + name + '" in ' + art.loaderFile + ' TEMPLATE_MAP but NOT exported in ' + art.indexFile);
    }
  }
}

if (errors.length > 0) {
  console.error('Template wiring errors found:');
  for (const e of errors) console.error('  ' + e);
  console.error('\\nFix: export the template in index.ts AND add it to the loader TEMPLATE_MAP.');
  process.exit(1);
}
`;

export const ARTIFACT_VALIDATE_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} artifact validator
// Runs codi validate when .codi/ files are staged, blocking commits with broken artifacts.
import { execFileSync } from 'child_process';

const staged = (() => {
  try {
    return execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' })
      .trim().split('\\n').filter(Boolean);
  } catch { return []; }
})();

const hasCodi = staged.some(f => f.startsWith('.codi/'));
if (!hasCodi) process.exit(0);

console.log('Validating .codi/ artifacts...');

try {
  execFileSync('npx', ['codi', 'validate', '--ci'], { stdio: 'inherit' });
} catch {
  console.error('');
  console.error('codi artifact validation failed.');
  console.error('Run: npx codi validate  to see full details.');
  console.error('Fix the errors above, then re-stage the files and commit again.');
  process.exit(1);
}
`;

/**
 * Pre-push documentation checkpoint hook.
 * Blocks pushes to protected branches when docs/project/.doc-stamp is outdated.
 * {{PROTECTED_BRANCHES}} is replaced with a space-separated list of branch patterns at install time.
 */
export const PRE_PUSH_DOC_CHECK_TEMPLATE = `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} documentation checkpoint — Auto-generated by ${PROJECT_CLI} init
# Blocks pushes to protected branches when documentation has not been verified.
# To verify: review docs/project/, update if needed, then run: codi docs-stamp

STAMP_FILE="docs/project/.doc-stamp"
PROTECTED_BRANCHES="{{PROTECTED_BRANCHES}}"

is_protected() {
  target="$1"
  for pat in $PROTECTED_BRANCHES; do
    case "$target" in
      $pat) return 0 ;;
    esac
  done
  return 1
}

blocked=0

while IFS=' ' read -r _local_ref _local_sha remote_ref _remote_sha; do
  [ -z "$remote_ref" ] && continue
  branch="\${remote_ref#refs/heads/}"

  if is_protected "$branch"; then
    if [ ! -f "$STAMP_FILE" ]; then
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  No stamp found at %s\\n' "$STAMP_FILE"
      printf '  Run: ${PROJECT_CLI} docs-stamp\\n'
      printf '  Then commit the stamp and push again.\\n\\n'
      blocked=1
      continue
    fi

    stamp_hash=\$(node -e "try{const s=JSON.parse(require('fs').readFileSync('$STAMP_FILE','utf8'));process.stdout.write(s.commit||'')}catch(e){}" 2>/dev/null)

    if [ -z "\$stamp_hash" ]; then
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  Stamp file is invalid or unreadable.\\n'
      printf '  Run: ${PROJECT_CLI} docs-stamp\\n'
      printf '  Then commit the stamp and push again.\\n\\n'
      blocked=1
      continue
    fi

    if ! git rev-parse --verify "\$stamp_hash^{commit}" >/dev/null 2>&1; then
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  Stamp hash not found in history (rebase invalidated it).\\n'
      printf '  Re-verify docs and run: ${PROJECT_CLI} docs-stamp\\n'
      printf '  Then commit the stamp and push again.\\n\\n'
      blocked=1
      continue
    fi

    count=\$(git rev-list "\$stamp_hash..HEAD" --count 2>/dev/null || echo 999)

    if [ "\$count" -gt 1 ]; then
      short=\$(echo "\$stamp_hash" | cut -c1-7)
      printf '\\n[${PROJECT_NAME}] Documentation checkpoint\\n'
      printf '  %s commits since last doc verification (stamp: %s).\\n' "\$count" "\$short"
      printf '  Review docs in docs/project/ and run: ${PROJECT_CLI} docs-stamp\\n'
      printf '  Then commit the stamp and push again.\\n\\n'
      blocked=1
    fi
  fi
done

exit \$blocked
`;

export const COMMIT_MSG_TEMPLATE = `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} commit message validator — Auto-generated by ${PROJECT_CLI} init
node --input-type=module - "$1" << 'HOOK_SCRIPT'
import fs from 'fs';

const msgFile = process.argv[2];
if (!msgFile) {
  console.error('No commit message file provided');
  process.exit(1);
}

const msg = fs.readFileSync(msgFile, 'utf-8').trim();
const firstLine = msg.split('\\n')[0];

const TYPES = ['feat', 'fix', 'docs', 'refactor', 'test', 'chore', 'perf', 'ci', 'build', 'style', 'revert'];
const pattern = new RegExp(\`^(\${TYPES.join('|')})(\\\\([^)]+\\\\))?!?: .+\`);

if (!pattern.test(firstLine)) {
  console.error('Invalid commit message format.');
  console.error(\`Expected: type(scope): description\`);
  console.error(\`Types: \${TYPES.join(', ')}\`);
  console.error(\`Example: feat(auth): add OAuth2 login flow\`);
  console.error(\`Got: \${firstLine}\`);
  process.exit(1);
}

if (firstLine.length > ${GIT_COMMIT_FIRST_LINE_LIMIT}) {
  console.error(\`Commit message first line too long: \${firstLine.length} chars (max ${GIT_COMMIT_FIRST_LINE_LIMIT})\`);
  process.exit(1);
}
HOOK_SCRIPT
`;

export const IMPORT_DEPTH_CHECK_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} import depth checker
// Blocks commits that introduce ../../ relative imports — use #src/* path aliases instead.
import fs from 'fs';

// Regex matches real import/export from statements with ../../ paths
const IMPORT_RE = /^\\s*(?:import|export)(?:[^'"\\n]*from)?\\s+['"](\\.\\.\\/\\.\\.\\/[^'"]*)['"]/m;

const EXCLUDED = [
  /\\.d\\.ts$/,
  /\\/references\\//,
  /\\/scripts\\//,
  /\\.md$/,
];

const files = process.argv.slice(2).filter(f =>
  /\\.(ts|tsx|js|jsx|mts|mjs)$/.test(f) && !EXCLUDED.some(p => p.test(f))
);

const findings = [];

for (const file of files) {
  let content;
  try { content = fs.readFileSync(file, 'utf-8'); } catch { continue; }
  const lines = content.split('\\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!IMPORT_RE.test(line)) continue;
    // Skip lines inside template literals (doc examples) — they are indented with backtick context
    const trimmed = line.trimStart();
    if (!trimmed.startsWith('import') && !trimmed.startsWith('export') && !trimmed.startsWith('} from')) continue;
    findings.push({ file, line: i + 1, text: trimmed.substring(0, 100) });
  }
}

if (findings.length > 0) {
  console.error('[import-depth] Deep relative imports found — use #src/* path aliases instead:');
  for (const f of findings) {
    console.error(\`  \${f.file}:\${f.line}  \${f.text}\`);
  }
  console.error('\\nFix: replace ../../ with #src/ (e.g. "../../types/result.js" → "#src/types/result.js")');
  process.exit(1);
}
`;
