import { PROJECT_CLI, PROJECT_NAME_DISPLAY } from "#src/constants.js";

/**
 * Standalone pre-commit hook runner. Written to .git/hooks/pre-commit when
 * the runner is "none" or "lefthook". Reads from the new HookSpec shape
 * (post-#85): hooks come pre-filtered to stages.includes("pre-commit") by
 * the installer, then the script reads each hook's `shell.command`,
 * `shell.passFiles`, `shell.modifiesFiles`, `shell.toolBinary`, plus the
 * top-level `name`, `language`, `category`, `files`, `required`, and
 * `installHint` fields.
 *
 * Extracted from `hook-templates.ts` to keep that file under the per-file
 * LOC limit (matches the pattern used by `conflict-marker-template.ts`,
 * `version-bump-template.ts`, `version-verify-pre-push-template.ts`).
 */
export const RUNNER_TEMPLATE = `#!/bin/sh
# ${PROJECT_NAME_DISPLAY} pre-commit hook runner — Auto-generated by ${PROJECT_CLI} init
node --input-type=module << 'HOOK_SCRIPT'
import { execFileSync, execSync } from 'child_process';

const hooks = {{HOOKS_JSON}};

/** Convert a HookSpec.files glob (e.g. **\\/*.{ts,tsx}) to a JS RegExp, or null if no recognizable extension pattern. */
function globToRegex(glob) {
  if (!glob) return null;
  const m = glob.match(/\\*\\*\\/\\*\\.(?:\\{([^}]+)\\}|(\\w+))$/);
  if (!m) return null;
  const exts = m[1] ? m[1].split(',') : [m[2]];
  return new RegExp('\\\\.(' + exts.join('|') + ')$');
}

function getStagedFiles() {
  try {
    const out = execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' });
    return out.trim().split('\\n').filter(Boolean);
  } catch { return []; }
}

/** Single-quote a path for safe inclusion in a shell command. */
function shellQuote(p) {
  return "'" + String(p).replace(/'/g, "'\\\\''") + "'";
}

/** Resolve a tool binary, preferring local node_modules/.bin then PATH. */
function hasTool(bin) {
  if (!bin) return true;
  try { execFileSync('command', ['-v', bin], { stdio: 'ignore', shell: true }); return true; }
  catch {}
  try { execFileSync('test', ['-f', './node_modules/.bin/' + bin], { stdio: 'ignore', shell: true }); return true; }
  catch {}
  return false;
}

const allStaged = getStagedFiles();
let exitCode = 0;
let lastLang = '';

for (const hook of hooks) {
  // Defense in depth: filter by stage at runtime too. Installer pre-filters,
  // but if the JSON ever ships a wrong-stage hook this prevents it firing.
  if (Array.isArray(hook.stages) && !hook.stages.includes('pre-commit')) continue;

  const shell = hook.shell || {};
  const cmd = shell.command;
  if (typeof cmd !== 'string' || cmd.length === 0) continue;

  const passFiles = shell.passFiles !== false; // default true
  const modifiesFiles = shell.modifiesFiles === true;
  const tool = shell.toolBinary || cmd.split(/\\s+/)[0];

  // Filter staged files by hook.files glob; empty glob = global (always run).
  const re = globToRegex(hook.files);
  const isGlobal = !hook.files;
  const matched = re ? allStaged.filter(f => re.test(f)) : allStaged;
  if (!isGlobal && matched.length === 0) continue;

  // Language-group banner for diagnostic output.
  const hookLang = hook.language ?? '';
  if (hookLang !== lastLang) {
    console.log(hookLang ? \`\\n[\${hookLang}]\` : \`\\n[global]\`);
    lastLang = hookLang;
  }
  console.log(\`  Running \${hook.name}...\`);

  // Tool-presence pre-flight (mirrors shell-renderer's command -v + node_modules/.bin check).
  if (!hasTool(tool)) {
    const hint = hook.installHint && hook.installHint.command;
    const url = hook.installHint && hook.installHint.url;
    if (hook.required === true) {
      console.error(\`  ✗ BLOCKING — install \${hook.name} to commit:\`);
      if (hint) console.error(\`    \${hint}\`);
      if (url) console.error(\`    See: \${url}\`);
      exitCode = 1;
    } else {
      console.warn(\`  ⚠ WARNING — install \${hook.name} to enable \${hook.category ?? 'this check'} (optional)\`);
      if (hint) console.warn(\`    \${hint}\`);
    }
    continue;
  }

  // Build the final command line. Generated by Codi (not user input) — shell is safe.
  let finalCmd = cmd;
  if (passFiles && !isGlobal) {
    finalCmd = cmd + ' ' + matched.map(shellQuote).join(' ');
  } else if (passFiles && isGlobal && allStaged.length > 0) {
    finalCmd = cmd + ' ' + allStaged.map(shellQuote).join(' ');
  }

  try {
    execSync(finalCmd, { stdio: 'inherit' });
    if (modifiesFiles) {
      const toRestage = isGlobal ? allStaged : matched;
      if (toRestage.length > 0) {
        execFileSync('git', ['add', ...toRestage], { stdio: 'inherit' });
      }
    }
  } catch {
    console.error(\`  ✗ \${hook.name} failed\`);
    exitCode = 1;
  }
}

process.exit(exitCode);
HOOK_SCRIPT
`;
