import { PROJECT_NAME, PROJECT_NAME_DISPLAY, PROJECT_CLI } from "#src/constants.js";

/**
 * Pre-push hook that verifies every artifact change in the push range
 * has a version bump. Read-only — never mutates files. Catches commits
 * that bypassed the pre-commit auto-bump (--no-verify, missing hook).
 *
 * Reads pre-push args from stdin per git protocol:
 *   <local_ref> <local_oid> <remote_ref> <remote_oid>
 * one line per ref.
 */
export const VERSION_VERIFY_PRE_PUSH_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} pre-push artifact version verifier
// Auto-generated by ${PROJECT_CLI} init
import { execFileSync } from 'child_process';

const ZERO_OID = '0000000000000000000000000000000000000000';
const PREFIX = '${PROJECT_NAME}';

function isArtifactPath(p) {
  return (
    /^src\\/templates\\/(skills|agents)\\/[^/]+\\/template\\.ts$/.test(p) ||
    (/^src\\/templates\\/rules\\/[^/]+\\.ts$/.test(p) && !p.endsWith('/index.ts')) ||
    /^\\.codi\\/(rules|agents)\\/[^/]+\\.md$/.test(p) ||
    /^\\.codi\\/skills\\/[^/]+\\/SKILL\\.md$/.test(p)
  );
}

function gitShow(ref, path) {
  try {
    return execFileSync('git', ['show', ref + ':' + path], {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch { return null; }
}

function parseVersion(content) {
  const m = content.match(/^version:\\s*(\\d+)\\s*$/m);
  return m ? Number(m[1]) : 1;
}

function stripVersion(s) {
  return s.replace(/^version:\\s*\\d+\\s*$/m, 'version: 0');
}

function defaultBranchTip() {
  try {
    const ref = execFileSync('git', ['symbolic-ref', '--short', 'refs/remotes/origin/HEAD'], {
      encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'],
    }).trim();
    return execFileSync('git', ['rev-parse', ref], { encoding: 'utf-8' }).trim();
  } catch { return null; }
}

function resolveBase(localOid, remoteOid) {
  if (remoteOid !== ZERO_OID) return remoteOid;
  const tip = defaultBranchTip();
  if (!tip) return localOid;
  try {
    return execFileSync('git', ['merge-base', localOid, tip], { encoding: 'utf-8' }).trim();
  } catch { return localOid; }
}

function verifyRef(localOid, remoteOid) {
  if (localOid === ZERO_OID) return [];

  const baseOid = resolveBase(localOid, remoteOid);
  let diffOut = '';
  try {
    diffOut = execFileSync('git', ['diff', '--name-only', '--diff-filter=ACMR', baseOid + '..' + localOid], {
      encoding: 'utf-8',
    });
  } catch { return []; }

  const files = diffOut.trim().split('\\n').filter(Boolean).filter(isArtifactPath);
  const offenders = [];

  for (const path of files) {
    const baseContent = gitShow(baseOid, path);
    const headContent = gitShow(localOid, path);
    if (!baseContent || !headContent) continue;
    if (stripVersion(baseContent) === stripVersion(headContent)) continue;

    const baseVer = parseVersion(baseContent);
    const headVer = parseVersion(headContent);

    if (headVer < baseVer) {
      offenders.push({ path, base: baseVer, head: headVer, reason: 'regression' });
    } else if (headVer === baseVer) {
      offenders.push({ path, base: baseVer, head: headVer, reason: 'no-bump' });
    }
  }
  return offenders;
}

async function readStdin() {
  let buf = '';
  for await (const chunk of process.stdin) buf += chunk;
  return buf;
}

const stdin = await readStdin();
const lines = stdin.trim().split('\\n').filter(Boolean);

const allOffenders = [];
for (const line of lines) {
  const parts = line.split(/\\s+/);
  if (parts.length < 4) continue;
  const localOid = parts[1];
  const remoteOid = parts[3];
  allOffenders.push(...verifyRef(localOid, remoteOid));
}

if (allOffenders.length === 0) process.exit(0);

console.error('');
console.error('\\u2717 [version-verify] ' + allOffenders.length + ' artifact(s) need version bumps before push');
console.error('  files:');
for (const o of allOffenders) {
  const tag = o.reason === 'regression'
    ? '(v' + o.base + ' -> v' + o.head + ', version regression)'
    : '(v' + o.base + ' -> v' + o.head + ', content changed)';
  console.error('    - ' + o.path + ' ' + tag);
}
console.error('  reason: pre-commit hook did not run or was bypassed');
console.error('  fix: git add <files> && git commit --amend --no-edit');
console.error('       (or re-install the hook: ${PROJECT_CLI} init --reinstall-hooks)');
console.error('');
process.exit(1);
`;
