import { PROJECT_NAME, PROJECT_NAME_DISPLAY, PROJECT_CLI } from "#src/constants.js";

/**
 * Pre-commit hook that auto-bumps artifact version in template frontmatter
 * when template content changes. Runs BEFORE tests so the baseline stays in sync.
 *
 * Flow:
 * 1. Detect staged template files (skills, rules, agents)
 * 2. Compare current frontmatter version against baseline
 * 3. If version not already bumped, increment it
 * 4. Regenerate artifact-version-baseline.json
 * 5. Re-stage modified files + baseline
 */
export const VERSION_BUMP_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} artifact version auto-bump
// Auto-generated by ${PROJECT_CLI} init
// Bumps frontmatter version when template content changes, then regenerates baseline.
import fs from 'fs';
import { execFileSync } from 'child_process';
import path from 'path';

const BASELINE_PATH = 'src/core/version/artifact-version-baseline.json';
const PREFIX = '${PROJECT_NAME}';

// --- Helpers ---

function getStagedFiles() {
  try {
    return execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' })
      .trim().split('\\n').filter(Boolean);
  } catch { return []; }
}

/** Derive artifact name from template file path */
function toArtifactName(filePath) {
  const skillMatch = filePath.match(/^src\\/templates\\/skills\\/([^/]+)\\/template\\.ts$/);
  if (skillMatch) return PREFIX + '-' + skillMatch[1];

  const agentMatch = filePath.match(/^src\\/templates\\/agents\\/([^/]+)\\/template\\.ts$/);
  if (agentMatch) return PREFIX + '-' + agentMatch[1];

  const ruleMatch = filePath.match(/^src\\/templates\\/rules\\/([^/]+)\\.ts$/);
  if (ruleMatch && ruleMatch[1] !== 'index') return PREFIX + '-' + ruleMatch[1];

  return null;
}

function parseVersion(content) {
  const m = content.match(/^version:\\s*(\\d+)\\s*$/m);
  return m ? parseInt(m[1], 10) : 1;
}

// --- Main ---

const staged = getStagedFiles();
const templateFiles = staged.filter(f =>
  /^src\\/templates\\/(skills|agents)\\/[^/]+\\/template\\.ts$/.test(f) ||
  (/^src\\/templates\\/rules\\/[^/]+\\.ts$/.test(f) && !f.endsWith('/index.ts'))
);

if (templateFiles.length === 0) process.exit(0);

let baseline;
try {
  baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf-8'));
} catch {
  // No baseline yet — first-time setup, nothing to bump against
  process.exit(0);
}

const bumped = [];

for (const file of templateFiles) {
  const name = toArtifactName(file);
  if (!name) continue;

  const entry = baseline[name];
  if (!entry) continue; // New template — baseline:update will add it

  const content = fs.readFileSync(file, 'utf-8');
  const currentVersion = parseVersion(content);

  if (currentVersion <= entry.version) {
    const newVersion = entry.version + 1;
    const updated = content.replace(/^version:\\s*\\d+\\s*$/m, 'version: ' + newVersion);
    fs.writeFileSync(file, updated, 'utf-8');
    bumped.push({ name, file, from: currentVersion, to: newVersion });
  }
}

if (bumped.length === 0) process.exit(0);

// Regenerate baseline with new hashes
try {
  execFileSync('npm', ['run', 'baseline:update'], { stdio: 'pipe' });
} catch (e) {
  console.error('[version-bump] Failed to regenerate baseline');
  console.error(e.stderr ? e.stderr.toString() : e.message);
  process.exit(1);
}

// Re-stage modified templates + baseline
const filesToStage = [...bumped.map(b => b.file), BASELINE_PATH];
execFileSync('git', ['add', ...filesToStage], { stdio: 'inherit' });

for (const b of bumped) {
  console.log('  [version-bump] ' + b.name + ': ' + b.from + ' \\u2192 ' + b.to);
}
console.log('  [version-bump] Baseline regenerated, ' + bumped.length + ' artifact(s) bumped');
`;
