import { PROJECT_NAME, PROJECT_NAME_DISPLAY, PROJECT_CLI } from "#src/constants.js";

/**
 * Pre-commit hook that auto-bumps artifact version when content changed.
 * Works on both layers:
 *   - source: src/templates/{rules,skills,agents}/...
 *   - .codi/: user-managed → auto-bump + update artifact-manifest.json
 *             codi-managed → REJECT with fork-instead message
 * Uses `git show HEAD:path` as the source of "previous version" — no
 * baseline file is read or written.
 */
export const VERSION_BUMP_TEMPLATE = `#!/usr/bin/env node
// ${PROJECT_NAME_DISPLAY} artifact version auto-bump
// Auto-generated by ${PROJECT_CLI} init
import fs from 'fs';
import { execFileSync } from 'child_process';
import { createHash } from 'crypto';

const PREFIX = '${PROJECT_NAME}';
const MANIFEST = '.codi/artifact-manifest.json';

function staged() {
  try {
    return execFileSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], { encoding: 'utf-8' })
      .trim().split('\\n').filter(Boolean);
  } catch { return []; }
}

function detect(p, content) {
  let m;
  if ((m = p.match(/^src\\/templates\\/skills\\/([^/]+)\\/template\\.ts$/))) return { mode: 'source', name: PREFIX + '-' + m[1], type: 'skill' };
  if ((m = p.match(/^src\\/templates\\/agents\\/([^/]+)\\/template\\.ts$/))) return { mode: 'source', name: PREFIX + '-' + m[1], type: 'agent' };
  if ((m = p.match(/^src\\/templates\\/rules\\/([^/]+)\\.ts$/)) && m[1] !== 'index') return { mode: 'source', name: PREFIX + '-' + m[1], type: 'rule' };

  let codiMatch;
  let type = null;
  if ((codiMatch = p.match(/^\\.codi\\/rules\\/([^/]+)\\.md$/))) type = 'rule';
  else if ((codiMatch = p.match(/^\\.codi\\/skills\\/([^/]+)\\/SKILL\\.md$/))) type = 'skill';
  else if ((codiMatch = p.match(/^\\.codi\\/agents\\/([^/]+)\\.md$/))) type = 'agent';
  if (codiMatch && type) {
    const mb = (content.match(/^managed_by:\\s*(codi|user)\\s*$/m) || [, 'user'])[1];
    return { mode: mb === 'codi' ? 'codi-managed' : 'user-managed', name: codiMatch[1], type };
  }
  return { mode: 'skip' };
}

function parseVersion(c) {
  const m = c.match(/^version:\\s*(\\d+)\\s*$/m);
  return m ? Number(m[1]) : null;
}

function injectVersion(c, v) {
  if (/^version:\\s*\\d+\\s*$/m.test(c)) return c.replace(/^version:\\s*\\d+\\s*$/m, 'version: ' + v);
  return c.replace(/^---$/m, '---\\nversion: ' + v);
}

function strip(c) { return c.replace(/^version:\\s*\\d+\\s*$/m, 'version: 0'); }

function readManifest() {
  try { return JSON.parse(fs.readFileSync(MANIFEST, 'utf-8')); }
  catch { return null; }
}

function writeManifest(m) {
  fs.writeFileSync(MANIFEST, JSON.stringify(m, null, 2) + '\\n', 'utf-8');
}

function hash(c) { return createHash('sha256').update(c, 'utf-8').digest('hex'); }

// --- Main ---
const files = staged();
if (files.length === 0) process.exit(0);

const bumped = [];
const restage = [];
let manifest = readManifest();
let manifestDirty = false;

for (const file of files) {
  let stagedContent;
  try { stagedContent = fs.readFileSync(file, 'utf-8'); } catch { continue; }
  const det = detect(file, stagedContent);
  if (det.mode === 'skip') continue;

  if (det.mode === 'codi-managed') {
    console.error('');
    console.error('\\u2717 [version-bump] managed-by-codi artifact cannot be edited directly');
    console.error('  file: ' + file);
    console.error('  reason: managed_by: codi means this gets overwritten on \`${PROJECT_CLI} update\`');
    console.error('  fix: ${PROJECT_CLI} add ' + det.type + ' codi-' + det.name + ' --as my-' + det.name);
    console.error('');
    process.exit(1);
  }

  let prev;
  try {
    const headShow = execFileSync('git', ['show', 'HEAD:' + file], { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] });
    prev = { kind: 'found', content: headShow, version: parseVersion(headShow) || 1 };
  } catch (e) {
    const stderr = e.stderr ? e.stderr.toString() : '';
    if (stderr.includes('does not exist')) prev = { kind: 'new-file' };
    else prev = { kind: 'no-head' };
  }

  const stagedVer = parseVersion(stagedContent);

  if (prev.kind !== 'found') {
    if (stagedVer === null) {
      const updated = injectVersion(stagedContent, 1);
      fs.writeFileSync(file, updated, 'utf-8');
      bumped.push({ name: det.name, file, from: null, to: 1 });
      restage.push(file);
      if (det.mode === 'user-managed' && manifest) {
        manifest.artifacts[det.name] = {
          name: det.name, type: det.type,
          contentHash: hash(updated),
          installedArtifactVersion: 1,
          installedAt: new Date().toISOString(),
          managedBy: 'user',
        };
        manifestDirty = true;
      }
    }
    continue;
  }

  if (stagedVer !== null && stagedVer < prev.version) {
    console.error('\\u2717 [version-bump] version regression on ' + file + ': ' + prev.version + ' -> ' + stagedVer);
    console.error('  reason: artifact versions must monotonically increase');
    console.error('  fix: edit version: line to a value > ' + prev.version);
    process.exit(1);
  }

  if (stagedVer !== null && stagedVer > prev.version) continue; // user already bumped
  if (strip(stagedContent) === strip(prev.content)) continue; // content unchanged

  const newVer = prev.version + 1;
  const updated = injectVersion(stagedContent, newVer);
  fs.writeFileSync(file, updated, 'utf-8');
  bumped.push({ name: det.name, file, from: prev.version, to: newVer });
  restage.push(file);
  if (det.mode === 'user-managed' && manifest) {
    const existing = manifest.artifacts[det.name] || {};
    manifest.artifacts[det.name] = {
      name: det.name,
      type: det.type,
      contentHash: hash(updated),
      installedArtifactVersion: newVer,
      installedAt: existing.installedAt || new Date().toISOString(),
      managedBy: 'user',
    };
    manifestDirty = true;
  }
}

if (bumped.length === 0) process.exit(0);

if (manifestDirty) {
  writeManifest(manifest);
  restage.push(MANIFEST);
}

execFileSync('git', ['add', ...restage], { stdio: 'inherit' });

for (const b of bumped) {
  console.log('  [version-bump] ' + b.name + ': ' + (b.from === null ? 'new' : b.from) + ' \\u2192 ' + b.to);
}
console.log('  [version-bump] ' + bumped.length + ' artifact(s) bumped');
`;
