#!/usr/bin/env python3
"""
Validate documentation filenames in the docs/ directory.

Expected format: YYYYMMDD_HHMMSS_[CATEGORY]_filename.ext

Allowed categories:
    ARCHITECTURE, AUDIT, GUIDE, REPORT, ROADMAP,
    RESEARCH, SECURITY, TESTING, BUSINESS, TECH

Usage:
    python3 scripts/validate-docs.py          # Validate all docs
    python3 scripts/validate-docs.py --quiet  # Exit code only (0=pass, 1=fail)

Exit codes:
    0 — All files pass validation
    1 — One or more files fail validation
"""

import os
import re
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent.parent / "docs"

SKIP_FILES = {".DS_Store"}
# Directories excluded from timestamp-naming validation:
#   project/    — official project docs (architecture, features, etc.) — no timestamp convention
#   codi_docs/  — generated HTML/JSON output from codi docs commands
#   superpowers/ — brainstorming specs and plans generated by skills
SKIP_DIRS = {"DEPRECATED", "project", "codi_docs", "superpowers"}

ALLOWED_CATEGORIES = {
    "ARCHITECTURE",
    "AUDIT",
    "GUIDE",
    "REPORT",
    "ROADMAP",
    "RESEARCH",
    "SECURITY",
    "TESTING",
    "BUSINESS",
    "TECH",
    "PLAN",
}

# Full valid pattern: 8-digit date, underscore, 6-digit time, underscore,
# [CATEGORY] in brackets, underscore, then the rest of the filename
VALID_PATTERN = re.compile(
    r"^(\d{8})_(\d{6})_\[([A-Z]+)\]_(.+)$"
)

# Partial patterns for diagnosis
HAS_TIMESTAMP = re.compile(r"^\d{8}_\d{6}_")
HAS_CATEGORY = re.compile(r"^\d{8}_\d{6}_\[[A-Z]+\]_")


def diagnose(filename: str) -> str:
    """Return a human-readable explanation of what is wrong with the filename."""
    match = VALID_PATTERN.match(filename)
    if match:
        category = match.group(3)
        if category not in ALLOWED_CATEGORIES:
            allowed = ", ".join(sorted(ALLOWED_CATEGORIES))
            return (
                f"Invalid category [{category}]. "
                f"Allowed categories: {allowed}"
            )
        return ""  # Valid — should not reach here

    if HAS_TIMESTAMP.match(filename):
        # Has timestamp but category is missing or malformed
        if HAS_CATEGORY.match(filename):
            # Pattern matched but category check failed above — extract it
            cat_match = re.match(r"^\d{8}_\d{6}_\[([A-Z]+)\]_", filename)
            if cat_match:
                category = cat_match.group(1)
                allowed = ", ".join(sorted(ALLOWED_CATEGORIES))
                return (
                    f"Invalid category [{category}]. "
                    f"Allowed categories: {allowed}"
                )
        return (
            "Missing [CATEGORY] tag after timestamp. "
            "Expected format: YYYYMMDD_HHMMSS_[CATEGORY]_filename.ext"
        )

    return (
        "Missing timestamp and [CATEGORY] tag. "
        "Expected format: YYYYMMDD_HHMMSS_[CATEGORY]_filename.ext"
    )


def validate_file(filepath: Path, docs_dir: Path) -> str | None:
    """Validate a single file. Return error message or None if valid."""
    filename = filepath.name

    if filename in SKIP_FILES:
        return None

    # Check: file must be in docs/ root, not in a subdirectory
    if filepath.parent != docs_dir:
        return (
            "File is in a subdirectory. All docs must be in docs/ root. "
            "Move this file to docs/ and run flatten-docs.py if needed."
        )

    match = VALID_PATTERN.match(filename)
    if match:
        category = match.group(3)
        if category in ALLOWED_CATEGORIES:
            return None  # Valid
        allowed = ", ".join(sorted(ALLOWED_CATEGORIES))
        return (
            f"Invalid category [{category}]. "
            f"Allowed categories: {allowed}"
        )

    return diagnose(filename)


def collect_failures(docs_dir: Path) -> list[tuple[Path, str]]:
    """Walk docs/ and collect (filepath, error_message) for failing files."""
    failures: list[tuple[Path, str]] = []

    for root, dirs, files in os.walk(docs_dir):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fname in sorted(files):
            filepath = Path(root) / fname
            error = validate_file(filepath, docs_dir)
            if error is not None:
                failures.append((filepath, error))

    return failures


def print_results(
    failures: list[tuple[Path, str]], docs_dir: Path, quiet: bool
) -> None:
    """Print validation results to stdout."""
    if quiet:
        return

    if not failures:
        print("All documentation files pass naming validation.")
        return

    print(f"\n{'='*90}")
    print(f"  DOCUMENTATION NAMING VALIDATION — {len(failures)} file(s) FAILED")
    print(f"{'='*90}\n")

    for filepath, error in failures:
        rel_path = filepath.relative_to(docs_dir.parent)
        print(f"  FAIL: {rel_path}")
        print(f"        {error}")
        print()

    print(f"{'='*90}")
    print(f"  CORRECTION INSTRUCTIONS")
    print(f"{'='*90}\n")
    print("  Rename each failing file to match this format:\n")
    print("    YYYYMMDD_HHMMSS_[CATEGORY]_filename.ext\n")
    print("  Rules:")
    print("    1. YYYYMMDD_HHMMSS = timestamp (file creation date and time)")
    print("    2. [CATEGORY] = one of the allowed categories in UPPERCASE")
    print("       Allowed: ", ", ".join(sorted(ALLOWED_CATEGORIES)))
    print("    3. filename = descriptive name, lowercase, hyphens, no adjectives")
    print("    4. No other category values are allowed")
    print("    5. All files must be in docs/ root — no subdirectories\n")
    print("  Example:")
    print("    20260311_143000_[AUDIT]_trip-planner-audit.md\n")
    print(f"  Total failing: {len(failures)} file(s)")
    print(f"{'='*90}\n")


def main() -> None:
    quiet = "--quiet" in sys.argv

    if not DOCS_DIR.is_dir():
        print(f"Error: docs directory not found at {DOCS_DIR}")
        sys.exit(1)

    failures = collect_failures(DOCS_DIR)
    print_results(failures, DOCS_DIR, quiet)

    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
