import type { GitHookArtifact } from "../hook-artifact.js";

export const CSHARP_HOOKS: GitHookArtifact[] = [
  {
    bucket: "git",
    name: "dotnet-format",
    description: "C# formatter via dotnet format",
    version: "1",
    managed_by: "codi",
    required: false,
    default: true,
    category: "format",
    language: "csharp",
    files: "**/*.cs",
    stages: ["pre-commit"],
    shell: {
      command: "dotnet format --include",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "dotnet",
    },
    preCommit: {
      kind: "local",
      entry: "dotnet format --include",
      language: "system",
    },
    installHint: { command: "Install .NET SDK from https://dot.net" },
  },
  {
    bucket: "git",
    name: "dotnet-build",
    description: "C# build / type check",
    version: "1",
    managed_by: "codi",
    required: true,
    default: true,
    category: "type-check",
    language: "csharp",
    files: "**/*.cs",
    stages: ["pre-push"],
    shell: {
      command: "dotnet build --no-incremental -nologo",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "dotnet",
    },
    preCommit: {
      kind: "local",
      entry: "dotnet build --no-incremental -nologo",
      language: "system",
      passFilenames: false,
    },
    installHint: { command: "Install .NET SDK from https://dot.net" },
  },
];
