import { PROJECT_CLI, PROJECT_NAME } from "#src/constants.js";
import type { GitHookArtifact } from "../hook-artifact.js";

export const GLOBAL_HOOKS: GitHookArtifact[] = [
  {
    bucket: "git",
    name: "gitleaks",
    description: "Secret-leak scanner for staged content",
    version: "1",
    managed_by: "codi",
    required: true,
    default: true,
    category: "security",
    language: "global",
    files: "**/*",
    stages: ["pre-commit"],
    shell: {
      command: "gitleaks protect --staged --no-banner",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "gitleaks",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/gitleaks/gitleaks",
      rev: "v8.21.0",
      id: "gitleaks",
    },
    installHint: {
      command: "brew install gitleaks",
      url: "https://github.com/gitleaks/gitleaks#installing",
    },
  },
  {
    bucket: "git",
    name: "commitlint",
    description: "Conventional commit-message linter",
    version: "1",
    managed_by: "codi",
    required: false,
    default: true,
    category: "meta",
    language: "global",
    files: "",
    stages: ["commit-msg"],
    shell: {
      command: "npx --no -- commitlint --edit",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "commitlint",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/alessandrojcm/commitlint-pre-commit-hook",
      rev: "v9.23.0",
      id: "commitlint",
      additionalDependencies: ["@commitlint/config-conventional"],
    },
    installHint: {
      command: "npm install -D @commitlint/config-conventional @commitlint/cli",
    },
  },
  {
    bucket: "git",
    name: `${PROJECT_NAME}-doctor`,
    description: "codi self-check, runs codi doctor --ci",
    version: "1",
    managed_by: "codi",
    required: false,
    default: true,
    category: "meta",
    language: "global",
    files: "",
    stages: ["pre-commit"],
    shell: {
      command: `npx ${PROJECT_CLI} doctor --ci`,
      passFiles: false,
      modifiesFiles: false,
      toolBinary: PROJECT_CLI,
    },
    preCommit: {
      kind: "local",
      entry: `npx ${PROJECT_CLI} doctor --ci`,
      language: "system",
      passFilenames: false,
    },
    installHint: { command: "" },
  },
];
