import type { GitHookArtifact } from "../hook-artifact.js";

export const JAVASCRIPT_HOOKS: GitHookArtifact[] = [
  {
    bucket: "git",
    name: "eslint",
    description: "JS linter via eslint",
    version: "1",
    managed_by: "codi",
    required: false,
    default: true,
    category: "lint",
    language: "javascript",
    files: "**/*.{js,jsx,mjs,cjs}",
    stages: ["pre-commit"],
    shell: {
      command: "npx eslint --fix",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "eslint",
    },
    preCommit: {
      kind: "local",
      entry: "npx eslint --fix",
      language: "system",
    },
    installHint: { command: "npm install -D eslint" },
  },
  {
    bucket: "git",
    name: "prettier",
    description: "Code formatter for JS / JSON / MD / YAML",
    version: "1",
    managed_by: "codi",
    required: false,
    default: true,
    category: "format",
    language: "javascript",
    files: "**/*.{js,jsx,mjs,cjs,json,md,mdx,yaml,yml,css,scss,html}",
    stages: ["pre-commit"],
    shell: {
      command: "npx prettier --write",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "prettier",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/pre-commit/mirrors-prettier",
      rev: "v4.0.0-alpha.8",
      id: "prettier",
    },
    installHint: { command: "npm install -D prettier" },
  },
  {
    // Biome — see registry/typescript.ts for rationale. Duplicated here so
    // pure-JS projects (no tsconfig.json) can opt into Biome too.
    bucket: "git",
    name: "biome",
    description: "Rust-based lint+format (mutually exclusive with eslint+prettier)",
    version: "1",
    managed_by: "codi",
    required: false,
    default: false,
    category: "lint",
    language: "javascript",
    files: "**/*.{js,jsx,mjs,cjs,json,jsonc,css}",
    stages: ["pre-commit"],
    shell: {
      command: "npx @biomejs/biome check --write --no-errors-on-unmatched",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "biome",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/biomejs/pre-commit",
      rev: "v0.6.1",
      id: "biome-check",
      args: ["--write", "--no-errors-on-unmatched"],
      additionalDependencies: ["@biomejs/biome@2.3.0"],
    },
    installHint: { command: "npm install -D @biomejs/biome" },
  },
];
