import type { HookSpec } from "../hook-spec.js";

export const PYTHON_HOOKS: HookSpec[] = [
  {
    name: "ruff-check",
    language: "python",
    category: "lint",
    files: "**/*.py",
    stages: ["pre-commit"],
    required: true,
    shell: {
      command: "ruff check --fix",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "ruff",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/astral-sh/ruff-pre-commit",
      rev: "v0.15.12",
      id: "ruff-check",
      args: ["--fix"],
    },
    installHint: { command: "pip install ruff", url: "https://docs.astral.sh/ruff" },
  },
  {
    name: "ruff-format",
    language: "python",
    category: "format",
    files: "**/*.py",
    stages: ["pre-commit"],
    required: false,
    shell: {
      command: "ruff format",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "ruff",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/astral-sh/ruff-pre-commit",
      rev: "v0.15.12",
      id: "ruff-format",
    },
    installHint: { command: "pip install ruff" },
  },
  {
    name: "basedpyright",
    language: "python",
    category: "type-check",
    files: "**/*.py",
    stages: ["pre-push"],
    required: true,
    shell: {
      command: "basedpyright",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "basedpyright",
    },
    preCommit: {
      kind: "local",
      entry: "basedpyright",
      language: "python",
      additionalDependencies: ["basedpyright"],
      passFilenames: false,
    },
    installHint: { command: "pip install basedpyright" },
  },
  {
    name: "mypy",
    language: "python",
    category: "type-check",
    files: "**/*.py",
    stages: ["pre-push"],
    required: true,
    shell: {
      command: "mypy",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "mypy",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/pre-commit/mirrors-mypy",
      rev: "v1.13.0",
      id: "mypy",
      passFilenames: false,
    },
    installHint: { command: "pip install mypy" },
  },
  {
    name: "pyright",
    language: "python",
    category: "type-check",
    files: "**/*.py",
    stages: ["pre-push"],
    required: true,
    shell: {
      command: "npx pyright",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "pyright",
    },
    preCommit: {
      kind: "local",
      entry: "npx pyright",
      language: "system",
      passFilenames: false,
    },
    installHint: { command: "npm install -D pyright" },
  },
  {
    name: "bandit",
    language: "python",
    category: "security",
    files: "**/*.py",
    stages: ["pre-commit"],
    required: true,
    shell: {
      command: "bandit -c pyproject.toml -lll -r",
      passFiles: true,
      modifiesFiles: false,
      toolBinary: "bandit",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/PyCQA/bandit",
      rev: "1.8.0",
      id: "bandit",
      args: ["-c", "pyproject.toml", "-lll"],
      additionalDependencies: ["bandit[toml]"],
    },
    installHint: { command: 'pip install "bandit[toml]"' },
  },
];
