import type { GitHookArtifact } from "../hook-artifact.js";

export const RUBY_HOOKS: GitHookArtifact[] = [
  {
    bucket: "git",
    name: "rubocop",
    description: "Ruby linter and auto-formatter",
    version: "1",
    managed_by: "codi",
    required: true,
    default: true,
    category: "lint",
    language: "ruby",
    files: "**/*.rb",
    stages: ["pre-commit"],
    shell: {
      command: "rubocop -a",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "rubocop",
    },
    preCommit: {
      kind: "local",
      entry: "rubocop -a",
      language: "system",
    },
    installHint: { command: "gem install rubocop" },
  },
  {
    bucket: "git",
    name: "brakeman",
    description: "Ruby/Rails security scanner",
    version: "1",
    managed_by: "codi",
    required: true,
    default: true,
    category: "security",
    language: "ruby",
    files: "**/*.rb",
    stages: ["pre-commit"],
    shell: {
      command: "brakeman --no-pager -q",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "brakeman",
    },
    preCommit: {
      kind: "local",
      entry: "brakeman --no-pager -q",
      language: "system",
      passFilenames: false,
    },
    installHint: { command: "gem install brakeman" },
  },
];
