import type { GitHookArtifact } from "../hook-artifact.js";
import { MANAGED_BY_FRAMEWORK } from "#src/constants.js";

export const TYPESCRIPT_HOOKS: GitHookArtifact[] = [
  {
    bucket: "git",
    name: "eslint",
    description: "JS/TS linter via eslint",
    version: "1",
    managed_by: MANAGED_BY_FRAMEWORK,
    required: false,
    default: true,
    category: "lint",
    language: "typescript",
    files: "**/*.{ts,tsx,js,jsx}",
    stages: ["pre-commit"],
    shell: {
      command: "npx eslint --fix",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "eslint",
    },
    preCommit: {
      kind: "local",
      entry: "npx eslint --fix",
      language: "system",
    },
    installHint: { command: "npm install -D eslint" },
  },
  {
    bucket: "git",
    name: "prettier",
    description: "Code formatter for JS/TS/MD/YAML",
    version: "1",
    managed_by: MANAGED_BY_FRAMEWORK,
    required: false,
    default: true,
    category: "format",
    language: "typescript",
    files: "**/*.{ts,tsx,js,jsx,mjs,cjs,json,md,mdx,yaml,yml,css,scss,html}",
    stages: ["pre-commit"],
    shell: {
      command: "npx prettier --write",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "prettier",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/pre-commit/mirrors-prettier",
      rev: "v4.0.0-alpha.8",
      id: "prettier",
    },
    installHint: { command: "npm install -D prettier" },
  },
  {
    bucket: "git",
    name: "tsc",
    description: "TypeScript type checker (no emit)",
    version: "1",
    managed_by: MANAGED_BY_FRAMEWORK,
    required: true,
    default: true,
    category: "type-check",
    language: "typescript",
    files: "**/*.{ts,tsx}",
    stages: ["pre-push"],
    shell: {
      command: "npx tsc --noEmit",
      passFiles: false,
      modifiesFiles: false,
      toolBinary: "tsc",
    },
    preCommit: {
      kind: "local",
      entry: "npx tsc --noEmit",
      language: "system",
      passFilenames: false,
    },
    installHint: { command: "npm install -D typescript" },
  },
  {
    // Biome — single Rust-based tool covering both lint and format.
    // Mutually exclusive with the eslint+prettier pair: when js_format_lint
    // is set to 'biome' the filter logic in hook-config-generator drops
    // eslint and prettier from the spec list and keeps this hook instead.
    bucket: "git",
    name: "biome",
    description: "Rust-based lint+format (mutually exclusive with eslint+prettier)",
    version: "1",
    managed_by: MANAGED_BY_FRAMEWORK,
    required: false,
    default: false,
    category: "lint",
    language: "typescript",
    files: "**/*.{ts,tsx,js,jsx,mjs,cjs,json,jsonc,css}",
    stages: ["pre-commit"],
    shell: {
      command: "npx @biomejs/biome check --write --no-errors-on-unmatched",
      passFiles: true,
      modifiesFiles: true,
      toolBinary: "biome",
    },
    preCommit: {
      kind: "upstream",
      repo: "https://github.com/biomejs/pre-commit",
      rev: "v0.6.1",
      id: "biome-check",
      args: ["--write", "--no-errors-on-unmatched"],
      additionalDependencies: ["@biomejs/biome@2.3.0"],
    },
    installHint: { command: "npm install -D @biomejs/biome" },
  },
];
