import type { BuiltinPresetDefinition } from "./types.js";

export const preset: BuiltinPresetDefinition = {
  name: "codi-development",
  description:
    "Preset for developing the Codi CLI itself — strict TypeScript, anti-hardcoding, safe releases, and full QA tooling",
  version: "1.0.0",
  author: "codi",
  tags: ["codi", "cli", "typescript", "node", "development", "tooling"],
  compatibility: {
    codi: ">=0.7.0",
    agents: ["claude-code"],
  },
  flags: {
    auto_commit: { mode: "enabled", value: false },
    test_before_commit: { mode: "enforced", value: true },
    security_scan: { mode: "enforced", value: true },
    type_checking: { mode: "enforced", value: "strict" },
    max_file_lines: { mode: "enforced", value: 500 },
    require_tests: { mode: "enforced", value: true },
    allow_shell_commands: { mode: "enabled", value: true },
    allow_file_deletion: { mode: "enabled", value: false },
    lint_on_save: { mode: "enabled", value: true },
    allow_force_push: { mode: "enforced", value: false },
    require_pr_review: { mode: "enforced", value: true },
    mcp_allowed_servers: { mode: "enabled", value: [] },
    require_documentation: { mode: "enabled", value: true },
    allowed_languages: { mode: "enabled", value: ["*"] },
    max_context_tokens: { mode: "enabled", value: 50000 },
    progressive_loading: { mode: "enabled", value: "metadata" },
    drift_detection: { mode: "enabled", value: "error" },
    auto_generate_on_change: { mode: "enabled", value: true },
  },
  rules: [
    "typescript",
    "code-style",
    "testing",
    "architecture",
    "git-workflow",
    "error-handling",
    "performance",
    "security",
    "documentation",
    "production-mindset",
    "simplicity-first",
  ],
  skills: [
    "code-review",
    "codi-operations",
    "e2e-testing",
    "guided-qa-testing",
    "test-coverage",
    "refactoring",
    "security-scan",
    "codebase-onboarding",
    "documentation",
    "commit",
    "codi-contribute",
    "codi-preset-creator",
    "codi-skill-creator",
    "codi-rule-creator",
    "codi-agent-creator",
    "codi-command-creator",
    "codi-compare-preset",
  ],
  agents: ["code-reviewer", "test-generator", "security-analyzer"],
  commands: [
    "review",
    "test-run",
    "test-coverage",
    "security-scan",
    "commit",
    "refactor",
    "onboard",
  ],
  mcpServers: ["github"],
};
