import type { BuiltinPresetDefinition } from './types.js';

export const preset: BuiltinPresetDefinition = {
  name: 'codi-development',
  description: 'Preset for developing the Codi CLI itself — strict TypeScript, anti-hardcoding, safe releases, and full QA tooling',
  version: '1.0.0',
  extends: 'strict',
  author: 'codi',
  tags: ['codi', 'cli', 'typescript', 'node', 'development', 'tooling'],
  compatibility: {
    codi: '>=0.7.0',
    agents: ['claude-code'],
  },
  flags: {
    type_checking: { mode: 'enforced', value: 'strict' },
    require_tests: { mode: 'enforced', value: true },
    test_before_commit: { mode: 'enforced', value: true },
    security_scan: { mode: 'enforced', value: true },
    require_pr_review: { mode: 'enforced', value: true },
    allow_force_push: { mode: 'enforced', value: false },
    allow_shell_commands: { mode: 'enabled', value: true },
    lint_on_save: { mode: 'enabled', value: true },
    max_file_lines: { mode: 'enforced', value: 500 },
    require_documentation: { mode: 'enabled', value: true },
  },
  rules: [
    'typescript',
    'code-style',
    'testing',
    'architecture',
    'git-workflow',
    'error-handling',
    'performance',
    'security',
    'documentation',
    'production-mindset',
    'simplicity-first',
  ],
  skills: [
    'code-review',
    'codi-operations',
    'e2e-testing',
    'guided-qa-testing',
    'test-coverage',
    'refactoring',
    'security-scan',
    'codebase-onboarding',
    'documentation',
    'commit',
    'contribute',
    'preset-creator',
    'skill-creator',
    'rule-creator',
    'agent-creator',
    'command-creator',
  ],
  agents: ['code-reviewer', 'test-generator', 'security-analyzer'],
  commands: [
    'review',
    'test-run',
    'test-coverage',
    'security-scan',
    'commit',
    'refactor',
    'onboard',
  ],
};
