import { PROJECT_NAME, prefixedName } from "#src/constants.js";
import type { BuiltinPresetDefinition } from "./types.js";

export const preset: BuiltinPresetDefinition = {
  name: prefixedName("data-ml"),
  description: "Data engineering, data science, ML, and AI agent specialists",
  version: "1.0.0",
  author: PROJECT_NAME,
  tags: ["data", "ml", "ai", "analytics", "engineering"],
  compatibility: {
    engine: ">=0.4.0",
    agents: ["claude-code"],
  },
  flags: {
    auto_commit: { mode: "enabled", value: false },
    test_before_commit: { mode: "enabled", value: true },
    security_scan: { mode: "enabled", value: true },
    type_checking: { mode: "enabled", value: "strict" },
    max_file_lines: { mode: "enabled", value: 700 },
    require_tests: { mode: "enabled", value: false },
    allow_shell_commands: { mode: "enabled", value: true },
    allow_file_deletion: { mode: "enabled", value: true },
    lint_on_save: { mode: "enabled", value: true },
    allow_force_push: { mode: "enabled", value: false },
    require_pr_review: { mode: "enabled", value: true },
    mcp_allowed_servers: { mode: "enabled", value: [] },
    require_documentation: { mode: "enabled", value: false },
    allowed_languages: { mode: "enabled", value: ["*"] },
    max_context_tokens: { mode: "enabled", value: 50000 },
    progressive_loading: { mode: "enabled", value: "metadata" },
    drift_detection: { mode: "enabled", value: "warn" },
    auto_generate_on_change: { mode: "enabled", value: false },
  },
  rules: [
    prefixedName("python"),
    prefixedName("code-style"),
    prefixedName("testing"),
    prefixedName("error-handling"),
    prefixedName("performance"),
  ],
  skills: [prefixedName("code-review"), prefixedName("commit")],
  agents: [
    prefixedName("python-expert"),
    prefixedName("ai-engineering-expert"),
    prefixedName("data-engineering-expert"),
    prefixedName("data-science-specialist"),
    prefixedName("data-analytics-bi-expert"),
    prefixedName("data-intensive-architect"),
    prefixedName("mlops-engineer"),
  ],
  commands: [
    prefixedName("commit"),
    prefixedName("review"),
    prefixedName("check"),
  ],
  mcpServers: [],
};
