import {
  PROJECT_NAME,
  PROJECT_NAME_DISPLAY,
  prefixedName,
} from "../../constants.js";
import type { BuiltinPresetDefinition } from "./types.js";

export const preset: BuiltinPresetDefinition = {
  name: `${PROJECT_NAME}-dev`,
  description: `Preset for developing the ${PROJECT_NAME_DISPLAY} CLI itself — strict TypeScript, anti-hardcoding, safe releases, and full QA tooling`,
  version: "1.0.0",
  author: PROJECT_NAME,
  tags: [PROJECT_NAME, "cli", "typescript", "node", "development", "tooling"],
  compatibility: {
    engine: ">=0.7.0",
    agents: ["claude-code"],
  },
  flags: {
    auto_commit: { mode: "enabled", value: false },
    test_before_commit: { mode: "enforced", value: true },
    security_scan: { mode: "enforced", value: true },
    type_checking: { mode: "enforced", value: "strict" },
    max_file_lines: { mode: "enforced", value: 500 },
    require_tests: { mode: "enforced", value: true },
    allow_shell_commands: { mode: "enabled", value: true },
    allow_file_deletion: { mode: "enabled", value: false },
    lint_on_save: { mode: "enabled", value: true },
    allow_force_push: { mode: "enforced", value: false },
    require_pr_review: { mode: "enforced", value: true },
    mcp_allowed_servers: { mode: "enabled", value: [] },
    require_documentation: { mode: "enabled", value: true },
    allowed_languages: { mode: "enabled", value: ["*"] },
    max_context_tokens: { mode: "enabled", value: 50000 },
    progressive_loading: { mode: "enabled", value: "metadata" },
    drift_detection: { mode: "enabled", value: "error" },
    auto_generate_on_change: { mode: "enabled", value: true },
  },
  rules: [
    prefixedName("typescript"),
    prefixedName("code-style"),
    prefixedName("testing"),
    prefixedName("architecture"),
    prefixedName("git-workflow"),
    prefixedName("error-handling"),
    prefixedName("performance"),
    prefixedName("security"),
    prefixedName("documentation"),
    prefixedName("production-mindset"),
    prefixedName("simplicity-first"),
  ],
  skills: [
    prefixedName("code-review"),
    prefixedName("operations"),
    prefixedName("e2e-testing"),
    prefixedName("guided-qa-testing"),
    prefixedName("test-coverage"),
    prefixedName("refactoring"),
    prefixedName("security-scan"),
    prefixedName("codebase-onboarding"),
    prefixedName("documentation"),
    prefixedName("commit"),
    prefixedName("contribute"),
    prefixedName("preset-creator"),
    prefixedName("skill-creator"),
    prefixedName("rule-creator"),
    prefixedName("agent-creator"),
    prefixedName("command-creator"),
    prefixedName("compare-preset"),
  ],
  agents: [
    prefixedName("code-reviewer"),
    prefixedName("test-generator"),
    prefixedName("security-analyzer"),
  ],
  commands: [
    prefixedName("review"),
    prefixedName("test-run"),
    prefixedName("test-coverage"),
    prefixedName("security-scan"),
    prefixedName("commit"),
    prefixedName("refactor"),
    prefixedName("onboard"),
  ],
  mcpServers: [prefixedName("github")],
};
