import { PROJECT_NAME, prefixedName } from "#src/constants.js";
import { CORE_PLATFORM_RULES, CORE_PLATFORM_SKILLS } from "./core-platform.js";
import type { BuiltinPresetDefinition } from "./types.js";

export const preset: BuiltinPresetDefinition = {
  name: prefixedName("power-user"),
  description:
    "Daily workflow — graph exploration, day tracking, error diagnosis, enhanced commits",
  version: "1.0.0",
  author: PROJECT_NAME,
  tags: ["workflow", "mcp", "daily", "power-user"],
  compatibility: {
    engine: ">=0.4.0",
    agents: ["claude-code"],
  },
  flags: {
    auto_commit: { mode: "enabled", value: false },
    test_before_commit: { mode: "enabled", value: true },
    security_scan: { mode: "enabled", value: true },
    type_checking: { mode: "enabled", value: "strict" },
    require_tests: { mode: "enabled", value: false },
    allow_shell_commands: { mode: "enabled", value: true },
    allow_file_deletion: { mode: "enabled", value: true },
    lint_on_save: { mode: "enabled", value: true },
    allow_force_push: { mode: "enabled", value: false },
    require_pr_review: { mode: "enabled", value: true },
    mcp_allowed_servers: { mode: "enabled", value: [] },
    require_documentation: { mode: "enabled", value: true },
    doc_protected_branches: { mode: "enabled", value: ["main", "develop", "release/*"] },
    allowed_languages: { mode: "enabled", value: ["*"] },
    progressive_loading: { mode: "enabled", value: "metadata" },
    drift_detection: { mode: "enabled", value: "warn" },
    auto_generate_on_change: { mode: "enabled", value: false },
  },
  rules: [
    ...CORE_PLATFORM_RULES,
    prefixedName("workflow"),
    prefixedName("agent-usage"),
    prefixedName("code-style"),
    prefixedName("error-handling"),
    prefixedName("git-workflow"),
    prefixedName("testing"),
    prefixedName("output-discipline"),
  ],
  skills: [
    ...CORE_PLATFORM_SKILLS,
    prefixedName("code-review"),
    prefixedName("security-scan"),
    prefixedName("commit"),
    prefixedName("codebase-onboarding"),
    prefixedName("project-documentation"),
    prefixedName("test-suite"),
    prefixedName("session-log"),
    prefixedName("codebase-explore"),
    prefixedName("graph-sync"),
    prefixedName("roadmap"),
  ],
  agents: [prefixedName("codebase-explorer"), prefixedName("code-reviewer")],
  mcpServers: [prefixedName("github")],
};
