import type { BuiltinPresetDefinition } from './types.js';

export const preset: BuiltinPresetDefinition = {
  name: 'strict',
  description: 'Enforced — security locked, tests required, delete restricted, no force-push',
  version: '1.0.0',
  author: 'codi',
  tags: ['strict', 'enforced', 'security'],
  compatibility: {
    codi: '>=0.3.0',
    agents: ['claude-code', 'cursor', 'windsurf', 'codex', 'cline'],
  },
  flags: {
    auto_commit: { mode: 'enabled', value: false },
    test_before_commit: { mode: 'enforced', value: true, locked: true },
    security_scan: { mode: 'enforced', value: true, locked: true },
    type_checking: { mode: 'enforced', value: 'strict', locked: true },
    max_file_lines: { mode: 'enabled', value: 500 },
    require_tests: { mode: 'enforced', value: true, locked: true },
    allow_shell_commands: { mode: 'enabled', value: true },
    allow_file_deletion: { mode: 'enabled', value: false },
    lint_on_save: { mode: 'enabled', value: true },
    allow_force_push: { mode: 'enforced', value: false, locked: true },
    require_pr_review: { mode: 'enforced', value: true, locked: true },
    mcp_allowed_servers: { mode: 'enabled', value: [] },
    require_documentation: { mode: 'enabled', value: true },
    allowed_languages: { mode: 'enabled', value: ['*'] },
    max_context_tokens: { mode: 'enabled', value: 50000 },
    progressive_loading: { mode: 'enabled', value: 'metadata' },
    drift_detection: { mode: 'enabled', value: 'error' },
    auto_generate_on_change: { mode: 'enabled', value: true },
  },
  rules: ['code-style', 'testing', 'error-handling', 'security', 'git-workflow', 'codi-improvement'],
  skills: ['code-review', 'security-scan', 'commit', 'test-coverage', 'compare-preset'],
  agents: ['code-reviewer', 'security-analyzer', 'test-generator'],
  commands: ['review', 'commit', 'security-scan', 'test-run', 'test-coverage'],
  mcpServers: [],
};
