import type { BuiltinPresetDefinition } from './types.js';

export const preset: BuiltinPresetDefinition = {
  name: 'typescript-fullstack',
  description: 'TypeScript fullstack development with React/Next.js, strict typing, and CI best practices',
  version: '1.0.0',
  author: 'codi',
  tags: ['typescript', 'react', 'nextjs', 'fullstack', 'frontend', 'backend'],
  compatibility: {
    codi: '>=0.3.0',
    agents: ['claude-code', 'cursor', 'windsurf', 'codex', 'cline'],
  },
  flags: {
    auto_commit: { mode: 'enabled', value: false },
    test_before_commit: { mode: 'enabled', value: true },
    security_scan: { mode: 'enabled', value: true },
    type_checking: { mode: 'enforced', value: 'strict' },
    max_file_lines: { mode: 'enabled', value: 600 },
    require_tests: { mode: 'enabled', value: true },
    allow_shell_commands: { mode: 'enabled', value: true },
    allow_file_deletion: { mode: 'enabled', value: true },
    lint_on_save: { mode: 'enabled', value: true },
    allow_force_push: { mode: 'enabled', value: false },
    require_pr_review: { mode: 'enabled', value: true },
    mcp_allowed_servers: { mode: 'enabled', value: [] },
    require_documentation: { mode: 'enabled', value: false },
    allowed_languages: { mode: 'enabled', value: ['*'] },
    max_context_tokens: { mode: 'enabled', value: 50000 },
    progressive_loading: { mode: 'enabled', value: 'metadata' },
    drift_detection: { mode: 'enabled', value: 'warn' },
    auto_generate_on_change: { mode: 'enabled', value: false },
  },
  rules: ['typescript', 'react', 'nextjs', 'code-style', 'testing', 'architecture'],
  skills: ['code-review', 'e2e-testing', 'refactoring'],
  agents: ['code-reviewer', 'test-generator'],
  commands: [],
};
